apiVersion: v1
kind: Secret
metadata:
  name: falco-secrets
stringData:
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:zbccad0iqkzdemPNomAFOL8vAo7yfBE4Sf+h2BlMRZrn1pQ5IWcA7y+RTQIFoKZDnAuzaxcUuFQ8sijRJKt4Cy/BDISpOlaMveEnOSHwcgmAzyTUqUS7a+BHrLlbsQ8z1ySxBm2a5VVAIFCDG22A7r85Fh91y3Mz,iv:cjwyjtK+a1GP5rCJdrFTvlLsuyIsiFqpgWm7qnfwhQo=,tag:kfG3k1hD54J62ydtYuJAgQ==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTkpXKzhVVVhxRDFhNzhT
        ZmExN0w4L3QrZ2ZRMURyRUxXSDJhZzNIY3owCmtscTlrYTF2Yy9nTVBlVVB0bnBS
        ZDl1Z2hXdVlTRkxVZ1dPeXd0NytlcGsKLS0tIHVUNnZveWZXbjVRSWRRMTlnL3RW
        UEpzc2hES0dtUnE1dGZBbS9QUzFvSGsKYgYLajh599REhJjgzp6PVh/rTm1YZPEF
        i5qCT2Lgl3VLLBkNBmPT8mU8VvboDNkZOF92vYx53kHJo35i9uc6Ww==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T03:49:46Z"
  mac: ENC[AES256_GCM,data:KV0nn5QhIUV4+t+/MXw12pegh8BFb034+KpIhnWzj3HYcsWGHyrb0H3Pfz1a4qFwtsUYcVc/9CRSpr8wQaL+xweVowJF6xFrw1bBXflgw2JBaxplhvLIt+RDurXo0Re6Bo/gtKlqZQOf8b7Cpz8/P5CUQlPFkX/JtptZCExwI30=,iv:t0Of9msSsg31RyPBh7rQ9crUIyQVkNHZDTbrKrontVk=,tag:hIWAmC4ieOf6DXANzY3ekw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
