---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-dashboard-ca
  namespace: security
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDgzCCAmugAwIBAgIJAJfZVLhJPkgqMA0GCSqGSIb3DQEBCwUAMEgxCzAJBgNV
    BAYTAlVTMRMwEQYDVQQHDApDYWxpZm9ybmlhMRAwDgYDVQQKDAdDb21wYW55MRIw
    EAYDVQQDDAlkYXNoYm9hcmQwHhcNMjUxMjMwMTYyMTUzWhcNMjYxMjMwMTYyMTUz
    WjBIMQswCQYDVQQGEwJVUzETMBEGA1UEBwwKQ2FsaWZvcm5pYTEQMA4GA1UECgwH
    Q29tcGFueTESMBAGA1UEAwwJZGFzaGJvYXJkMIIBIjANBgkqhkiG9w0BAQEFAAOC
    AQ8AMIIBCgKCAQEAsU76EWMwSlNWV+vjhBEsokwvEm9Z0pxOOiyeyPiG++KUhP80
    UiIR0dyX9bJa0xvBDJjYxY68kp0pb2wge8ffZKwOxdAQngmkEDsn1up9NNPEtHG8
    O3qt2zavMV2s3gBW6cdjngf40PTTsZvhHr1L7wesJLDodhW7K5YKuFDovpO3sMzF
    Q7AaLTXO0sbM9DiQnXQLFAgrAYf+5QMQYUn4KyhtZep+6Ro+/M9JGXPdYlUKiQTg
    1ypfQ8PkFP3Zb236jZe9Y6ww+rkjqvk4dAnVQ05zRjt6kbCSGT1f4V2GGI1mvwxZ
    wrMRW09Nq81MYzmcVHVcKSN3VhetZTjdKfdi4QIDAQABo3AwbjBRBgNVHREESjBI
    gglkYXNoYm9hcmSCD3dhenVoLWRhc2hib2FyZIIqd2F6dWgtZGFzaGJvYXJkLnNl
    Y3VyaXR5LnN2Yy5jbHVzdGVyLmxvY2FsMAwGA1UdEwQFMAMBAf8wCwYDVR0PBAQD
    AgWgMA0GCSqGSIb3DQEBCwUAA4IBAQAqGM70p1vfkWc7uDa0uJydmbDGG1CHuBQ2
    gBg3jr/sMVQgGAN3Z8oSD16MyqDrPLrlHlSnkBfBADmcXhSFil+ZSp+YPPsJbHcH
    aI3tbj/Y30emCKPDBQS7FJWFEE+48TAQ99o6v2NywzIwW7L3/CEOZn/GHKyFuBg/
    g2UjTmaadzVyxSMLvtGas/NCG20z6MjopPvevDC5klxPZTXzxj9NYyY6WE159j54
    oO1G91nRdJNjTNvOWTgDggLuZDGEr/ZuZv7RMAE3Hf02DjVwED3dHWpGNWy2c4tK
    MLzYvL3yQ86IQN+JFxlXUhj/oW6Zwe0yOahyp2m4azjSjKQvgjPQ
    -----END CERTIFICATE-----
