---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-dashboard-ca
  namespace: security
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDDDCCAfQCCQCdROYFCSOzCzANBgkqhkiG9w0BAQsFADBIMQswCQYDVQQGEwJV
    UzETMBEGA1UEBwwKQ2FsaWZvcm5pYTEQMA4GA1UECgwHQ29tcGFueTESMBAGA1UE
    AwwJZGFzaGJvYXJkMB4XDTI1MTIzMDE0MTQwMloXDTI2MTIzMDE0MTQwMlowSDEL
    MAkGA1UEBhMCVVMxEzARBgNVBAcMCkNhbGlmb3JuaWExEDAOBgNVBAoMB0NvbXBh
    bnkxEjAQBgNVBAMMCWRhc2hib2FyZDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
    AQoCggEBALFO+hFjMEpTVlfr44QRLKJMLxJvWdKcTjosnsj4hvvilIT/NFIiEdHc
    l/WyWtMbwQyY2MWOvJKdKW9sIHvH32SsDsXQEJ4JpBA7J9bqfTTTxLRxvDt6rds2
    rzFdrN4AVunHY54H+ND007Gb4R69S+8HrCSw6HYVuyuWCrhQ6L6Tt7DMxUOwGi01
    ztLGzPQ4kJ10CxQIKwGH/uUDEGFJ+CsobWXqfukaPvzPSRlz3WJVCokE4NcqX0PD
    5BT92W9t+o2XvWOsMPq5I6r5OHQJ1UNOc0Y7epGwkhk9X+FdhhiNZr8MWcKzEVtP
    TavNTGM5nFR1XCkjd1YXrWU43Sn3YuECAwEAATANBgkqhkiG9w0BAQsFAAOCAQEA
    pEkbsUaSZyZAHZyiul+NMX4tGnEE7Mv9we15sjVp6pdBQN8qA8FPsuXd27CEuDTq
    wyUzT2ChXYdHhrLqy6slWKdUru8bl8MtAu9w+r5aKKMBP0tcVn055vVRl5tYlO0e
    WFc8/3bkCTvPS5w0c6uWzs1tE8vkHPxLEn760368AiFFVzC5qtGOhjmzAflpvdEU
    HM6ZQXVWKNahlAhnh2AZ4eup42MoJjVKesVHZYU8dPsaJaKAeh4IyAQyikZcX87L
    q+LADs89aLPg+4TXi9jrnIhPmV2deOaSA2XfzgX2cibCCwh6mAtmLYa97aZLb96b
    0KateII9JC5ga+GUAoOrNg==
    -----END CERTIFICATE-----
