---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-dashboard-ca
  namespace: security
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDCDCCAfACCQC6Y0GbXJrX0DANBgkqhkiG9w0BAQsFADBGMQswCQYDVQQGEwJV
    UzETMBEGA1UEBwwKQ2FsaWZvcm5pYTEQMA4GA1UECgwHQ29tcGFueTEQMA4GA1UE
    AwwHcm9vdC1jYTAeFw0yNTEyMzAwMDQ1MDhaFw0zNTEyMjgwMDQ1MDhaMEYxCzAJ
    BgNVBAYTAlVTMRMwEQYDVQQHDApDYWxpZm9ybmlhMRAwDgYDVQQKDAdDb21wYW55
    MRAwDgYDVQQDDAdyb290LWNhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
    AQEA9YuCwNOsFYK+l43hSztlRLX3Kna2f8hRHR/vhycciB3P3HF4yo5w819Qmjtn
    mXupTwkOc+KCGnGooMFiA7g3/0QbBIuE/pZFR2aW3z3MDwVYurGgyN/nyiKaFGqK
    O9mZoy8COFzrfvFo2dp94aNkoRHv6HKL6KVH43MQcfWICAnOt6mLqPLFVcQBzCq1
    LlCEGq4HBa9NhVwqir1KpZ/BNhCReAu8X9BrFRQc4OE2IngSwsuZErTyE/fi0IiV
    xbMzRTKLajDS8dm50mN6EBMTvvTFMF+e+SkuP9AwbS79ZSmto5ic1v0ch8MkYgga
    i8yKuJvOOEw7Lg+VSL/ZImk9CQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQDoTOvn
    ciXRiCZCnKPgqcoA1bPwwxrHw1pOoQTMwcozVPf0lowJ3aquzqmCs9/xPPATt9oY
    EToWl8QaHBYtD9ncoiW91lAUC5AL0VAwQmx/J+Jj2E3/PQVjnZ7jyWHmZLMBUpRg
    c8+0FOKHJtkj1Y4q19Oo22G6I8JdwLwAgsKjHU7EMYSHzoz5kMNuowGb5p3cjpD5
    9eDD32K6U8FTWDUnwl8QNK742ToO6xqd9f5NPaQoyKRxoeVFQoM2v4go1Zg/p17/
    cnhuR+gY9ue03yqOKHwkMiyNOafextvHBlJ6Lpo/oUNcTriZ9KRkhHh2uK9OvG9I
    l+Vk9Por3kZWTUkD
    -----END CERTIFICATE-----
