---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: wazuh-dashboard-tls
  namespace: security
spec:
  targetRefs:
  - group: ''
    kind: Service
    name: wazuh-dashboard
    sectionName: "443"
  validation:
    caCertificateRefs:
    - name: wazuh-dashboard-ca
      group: ''
      kind: ConfigMap
    hostname: wazuh-dashboard.security.svc.cluster.local
