---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wazuh
spec:
  hostnames:
    - wazuh.68cc.io
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: wazuh-dashboard
          port: 443
          namespace: security
      matches:
        - path:
            type: PathPrefix
            value: /
