---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/tcproute_v1alpha2.json
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: wazuh-agent-events
spec:
  parentRefs:
    - name: tcp-gateway
      namespace: network
      sectionName: wazuh-agent-events
  rules:
    - backendRefs:
        - name: wazuh-manager
          port: 1514
          namespace: security
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/tcproute_v1alpha2.json
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: wazuh-manager
spec:
  parentRefs:
    - name: tcp-gateway
      namespace: security
      sectionName: wazuh-registration
    - name: tcp-gateway
      namespace: security
      sectionName: wazuh-agent-enrollment
  rules:
    - backendRefs:
        - name: wazuh
          port: 1515
          namespace: security
        - name: wazuh
          port: 55000
          namespace: security
