---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/udproute_v1alpha2.json
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: wazuh-syslog
  namespace: security
spec:
  parentRefs:
    - name: tcp-gateway
      namespace: network
      sectionName: wazuh-syslog
  rules:
    - backendRefs:
        - name: wazuh-workers
          port: 514
          namespace: security
