---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app crowdsec
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: crowdsec
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      # renovate: datasource=docker depName=crowdsecurity/crowdsec
      tag: v1.7.3
      repository: crowdsecurity/crowdsec
      pullPolicy: Always
    container_runtime: containerd
    tls:
      enabled: true
      certManager:
        enabled: true
        issuerRef:
          name: letsencrypt-production
          kind: ClusterIssuer
        duration: 2160h
        renewBefore: 720h
      lapi:
        secret: crowdsec-lapi-tls
      agent:
        tlsClientAuth: true
        secret: crowdsec-agent-tls
      appsec:
        tlsClientAuth: true
        secret: "crowdsec-agent-tls"
    secrets:
      username: ""
      password: ""
      csLapiSecretKey: "" # Explicitly disable to prevent default "csLapiSecret" key lookup
    lapi:
      enabled: true
      replicas: 1
      strategy:
        type: Recreate
      persistentVolume:
        data:
          enabled: true
          storageClassName: nfs-client
          size: 10Gi
        config:
          enabled: true
          storageClassName: nfs-client
          size: 250Mi
      service:
        type: ClusterIP
        port: 8080
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      env:
        - name: ENROLL_KEY
          valueFrom:
            secretKeyRef:
              name: crowdsec-lapi-secrets
              key: enroll-key
        - name: ENROLL_INSTANCE_NAME
          value: "home-cluster"
        - name: ENROLL_TAGS
          value: "kubernetes homelab"
        - name: TZ
          value: "America/New_York"
      resources:
        limits:
          memory: 2Gi
        requests:
          cpu: 150m
          memory: 256Mi
    agent:
      acquisition:
        - namespace: "network"
          podName: "traefik-*"
          program: "traefik"
      # additionalAcquisition:
      #   - source: victorialogs
      #     mode: tail
      #     url: http://victoria-logs-server.monitoring.svc.cluster.local:9428/
      #     query: k8s.container.name:traefik
      #     labels:
      #       type: traefik
      env:
        - name: COLLECTIONS
          value: "crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/whitelist-good-actors crowdsecurity/appsec-virtual-patching crowdsecurity/unifi"
        # Parsers to install
        - name: PARSERS
          value: "crowdsecurity/cri-logs crowdsecurity/whitelists"
      resources:
        limits:
          memory: 2Gi
        requests:
          cpu: 150m
          memory: 128Mi
      persistentVolume:
        config:
          enabled: true
          storageClassName: nfs-client
          size: 100Mi
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
    appsec:
      acquisitions:
        - appsec_config: crowdsecurity/appsec-default
          labels:
            type: appsec
          listen_addr: 0.0.0.0:7422
          path: /
          source: appsec
      enabled: true
      env:
        - name: COLLECTIONS
          value: "crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules crowdsecurity/appsec-crs-inband"
