apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-lapi-secrets
  namespace: security
type: Opaque
stringData:
  csLapiSecret: ENC[AES256_GCM,data:balD6Bi5mfkW0ejnV2JrZ9hACJdSp/mDtUWarQ4xThtu/u70oKqsh6L2cM/HcgaC3/xcu10GKhHqtEce+tfNtw==,iv:W6AUX3YuDa96yEjYK2Fll6fmDI/ZTsgw3T96OlK/364=,tag:KW/aWDo7d9kn/EBegvNeIw==,type:str]
  enroll-key: ENC[AES256_GCM,data:2WNZ4lhTBXD1MeLfX5Em6hm03q/x8WTZJw==,iv:VJJnV61unjPg5sqYv0xY0ygDJh4I5GiwBrm/sev+bZ4=,tag:PQpoft6SwZXu2fkcu8Y82A==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MUZCUGtIT1U3eGU4VVRL
        WFhQbUNPQmxuVUJXUzhNQlNsSFBaZlRpVmtvClIyZ283THBVbVIyUGYveWJXKzIz
        VXorYUo4QnB3c0pPRDNpVU90RXVWaWcKLS0tIERDcHU0b3cyL2NzZFMyRklPV0tI
        RllxcS9zSHp1b1NrTzNXY2J3WkdoZzgKnEJrnO0Akt0dANqsXne+etnfyspe23jr
        uSyZ0QzFyiaqhderFwSv496ukIZeRA0hemmvb8I8JEJdYKGuhKKKJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T21:26:02Z"
  mac: ENC[AES256_GCM,data:j+HL4k3250BN7t95PN5DH6nWErUd2qKbL8LNIkZJ0Gs3PtXDJdoYIfNdLlq/qO86m/TRz3XiPF/zKGeVKtSPRMbAEV8vtA1Y/wQHwRBj/cjJoT6cdpDNNchPnrsEzm72f0OeojMEiqwfusxfloL7LeFqTicJQX4R4w2MR1z7+q4=,iv:qOInXMGjNyxBe9hhHW5m/0RoyqjicB57YvOCQ9V3O1M=,tag:NLtE2OgU980WNZm8HcTonw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-bouncer-secrets
  namespace: security
type: Opaque
stringData:
  traefik-bouncer-key: ENC[AES256_GCM,data:oxSWZ1FtivEWjRGfNnS9V1WO+eFK215oJa4tkbBJqG0zwGMPCEaxAUEhN+V94JYXSX1BzrNkgGrhP9UqiSLZIQ==,iv:mSkj1OPPtpWbK62SRHGo8BOcP/BSivRluOpWasXkOR4=,tag:HKmsZI/I8ytcYgRXaqeOSw==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MUZCUGtIT1U3eGU4VVRL
        WFhQbUNPQmxuVUJXUzhNQlNsSFBaZlRpVmtvClIyZ283THBVbVIyUGYveWJXKzIz
        VXorYUo4QnB3c0pPRDNpVU90RXVWaWcKLS0tIERDcHU0b3cyL2NzZFMyRklPV0tI
        RllxcS9zSHp1b1NrTzNXY2J3WkdoZzgKnEJrnO0Akt0dANqsXne+etnfyspe23jr
        uSyZ0QzFyiaqhderFwSv496ukIZeRA0hemmvb8I8JEJdYKGuhKKKJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T21:26:02Z"
  mac: ENC[AES256_GCM,data:j+HL4k3250BN7t95PN5DH6nWErUd2qKbL8LNIkZJ0Gs3PtXDJdoYIfNdLlq/qO86m/TRz3XiPF/zKGeVKtSPRMbAEV8vtA1Y/wQHwRBj/cjJoT6cdpDNNchPnrsEzm72f0OeojMEiqwfusxfloL7LeFqTicJQX4R4w2MR1z7+q4=,iv:qOInXMGjNyxBe9hhHW5m/0RoyqjicB57YvOCQ9V3O1M=,tag:NLtE2OgU980WNZm8HcTonw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
