apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-lapi-secrets
  namespace: security
type: Opaque
stringData:
  csLapiSecret: ENC[AES256_GCM,data:HrFC7rAjiSNoG26IN7qOwpdrH8E+O4qvQIE7wC3MIhurtPOhnwElUcpJxhS9aNutowyreW9qk105+3l4xupE/2wNeGRQfHp2YrSNZ9sykR8yaAeGv22q/w==,iv:u9nM13y8a1wSCZI1N72gnPG4lJ5B2331RNitQfcPEqI=,tag:t/p+hgphVAVk3SlGlKtcOQ==,type:str]
  registrationToken: ENC[AES256_GCM,data:YGUyRJ2SyT5vMX1/ZVMCvfst5YuOeOaf2Q==,iv:QhB/9U5T/Ib9C3ceM8ebBtclwpL54f/lqCYawPbOByM=,tag:loLLN1n3TN7CW4XK3GIfuQ==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNXpWczdQcXoxaitGelEx
        TGNaMzJGaUloMXB2eHFXcklUS0FaYU9vaUZFCmMyVkcycnV0WXpJQTJoOG9VU3Nk
        NzdwckRDYTRSQWFoWUU4SUNkb3hXaDQKLS0tIHoyaGxRelNGQnkwY09DMks4Ujlv
        TTVuSVdEYmR4cVFDK1RJT2dMMUFhWGMKZ7+kOsyoN9Lm3ZvCMBVrGNiHkPheMbMt
        U8WOu/BmrOUeMag6hRotJQ0hze2Wvxcm1Bf2ybYC3HoJPK20EawIQQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T21:44:52Z"
  mac: ENC[AES256_GCM,data:M5UcL942bqaHsMv1x8C8aQNApAcehgPCYEF8p76YGkCa5kntG94hLZvQryMgKUle6KMpm2PcyVjx5izu5royZWETSlKfdfU3m6ilkJIm5RNE+LNt7MJ+HThUKumgIk6YM55rvaysvKV9JjWZnWrDRrxxKd8R7AlbPfC7NHEyktA=,iv:W+KLt/WLrisbnSIU7aO4fVP4hmfsCtA+H0jvVD8tV+s=,tag:LHpq+DgI2ZbgHT2bVbZE6w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-bouncer-secrets
  namespace: security
type: Opaque
stringData:
  traefik-bouncer-key: ENC[AES256_GCM,data:aPiQkAW3a4LG/IEFUEm+hPVRzQdPheYMa9L6AP5TdQBt5pnqJAXt6IjV8NGAc5m+oj6y0iKI+R5JDEr8PLpyVA==,iv:tTUeZVRAaQwLIzo2pP/23de6ff/Fitz5+/ZZhMyADIw=,tag:lROaNqB8WYgrJV8PFeaO+w==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNXpWczdQcXoxaitGelEx
        TGNaMzJGaUloMXB2eHFXcklUS0FaYU9vaUZFCmMyVkcycnV0WXpJQTJoOG9VU3Nk
        NzdwckRDYTRSQWFoWUU4SUNkb3hXaDQKLS0tIHoyaGxRelNGQnkwY09DMks4Ujlv
        TTVuSVdEYmR4cVFDK1RJT2dMMUFhWGMKZ7+kOsyoN9Lm3ZvCMBVrGNiHkPheMbMt
        U8WOu/BmrOUeMag6hRotJQ0hze2Wvxcm1Bf2ybYC3HoJPK20EawIQQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T21:44:52Z"
  mac: ENC[AES256_GCM,data:M5UcL942bqaHsMv1x8C8aQNApAcehgPCYEF8p76YGkCa5kntG94hLZvQryMgKUle6KMpm2PcyVjx5izu5royZWETSlKfdfU3m6ilkJIm5RNE+LNt7MJ+HThUKumgIk6YM55rvaysvKV9JjWZnWrDRrxxKd8R7AlbPfC7NHEyktA=,iv:W+KLt/WLrisbnSIU7aO4fVP4hmfsCtA+H0jvVD8tV+s=,tag:LHpq+DgI2ZbgHT2bVbZE6w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
