apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-lapi-secrets
  namespace: security
type: Opaque
stringData:
  csLapiSecret: ENC[AES256_GCM,data:lCyjKiVr/esfAf/kNN3FmAq5TTPfUEJs0oalM6l/EfIo2bzrAS4g0ya+Typ1zOPUb3lsuv9/AE6ECCQh90VjOZceNyjK9XZL+dI9EpCG3hgd6H65lwA5gA==,iv:B+W0HKUbMiuamkwnGg5Bfj8U7jBpdsYiSya/kXTYCnY=,tag:tHSlC916LQtttJ4HNV/6+A==,type:str]
  enroll-key: ENC[AES256_GCM,data:1BQjk0YANM7VzXiOYqb3qraGWzBcPuV7Jg==,iv:pVrjXYqzi3K3elbjU6ZsyzimgIDgnIENoqAet40NJLU=,tag:neq0dQ2FSTnFMPXiaR2Uwg==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMDFyTFBobEJvSFdIRUpw
        RDlkYlo4Mi9xNjg5R0Z1WldSMjVXZjFvNVVjCjYzTWpjUzJxNVZGVGZ1MUR4NHdq
        ZWlTeGJvNjBGeUZnaFVsVzdtT2k4TU0KLS0tIFhDaktJaytDOFBuK2M5RmVqWXNV
        THVGck9VeHhDb3FUY3d0WFFzZ0dYOHcK8yuXfNASkrCWFk74uEheB2kr1d2Mbw2y
        +vvINk/KjTdMptCqt3280xER0B32OirUXPyG24Y5P53fWr5FvZoEcQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T21:31:28Z"
  mac: ENC[AES256_GCM,data:OCpYkEA/7sG3TQLIIqcQxpab9iAe4Y+zVGECOu1P+meC03II2Ar2UAyhimZFzvOrzBnwz037mQEKfIhMgWTOW867t5WEuiLOMgnNMTlrsLuKWFW8tpTvFvPLYiaRHmHL0J5R5UDcbwu0darxrVAI9CDq0AJpkf/1sUUhL4EqmGQ=,iv:wMVXhPg7tQ4gxUALlFnjmDLg0TbxAKsA3JLpBnuGSgE=,tag:KZ7U1l/QX0TCkD7wWRglqg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-bouncer-secrets
  namespace: security
type: Opaque
stringData:
  traefik-bouncer-key: ENC[AES256_GCM,data:0tnohhchno07ZfgPG1qcPqoGHg35CpT1MfaZurDrojLoAsDUOsB5Px6xjcEUQLoBJm3/szwFBooYoJTsU4gw6Q==,iv:4JmDfJf9/FXmRVePqfpd1I5QEX1VTk6l8SHIuBVJH68=,tag:Rx6fpJG++SC0Rgy4ycazfg==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMDFyTFBobEJvSFdIRUpw
        RDlkYlo4Mi9xNjg5R0Z1WldSMjVXZjFvNVVjCjYzTWpjUzJxNVZGVGZ1MUR4NHdq
        ZWlTeGJvNjBGeUZnaFVsVzdtT2k4TU0KLS0tIFhDaktJaytDOFBuK2M5RmVqWXNV
        THVGck9VeHhDb3FUY3d0WFFzZ0dYOHcK8yuXfNASkrCWFk74uEheB2kr1d2Mbw2y
        +vvINk/KjTdMptCqt3280xER0B32OirUXPyG24Y5P53fWr5FvZoEcQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T21:31:28Z"
  mac: ENC[AES256_GCM,data:OCpYkEA/7sG3TQLIIqcQxpab9iAe4Y+zVGECOu1P+meC03II2Ar2UAyhimZFzvOrzBnwz037mQEKfIhMgWTOW867t5WEuiLOMgnNMTlrsLuKWFW8tpTvFvPLYiaRHmHL0J5R5UDcbwu0darxrVAI9CDq0AJpkf/1sUUhL4EqmGQ=,iv:wMVXhPg7tQ4gxUALlFnjmDLg0TbxAKsA3JLpBnuGSgE=,tag:KZ7U1l/QX0TCkD7wWRglqg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
