apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-lapi-secrets
  namespace: security
type: Opaque
stringData:
  csLapiSecret: ENC[AES256_GCM,data:l8662M+ESQECAiYh+n17yLA4fKXmE3nDbIsTFQXhmTZdf3x3OGJz/CTuQ/mDP9mH0kYg1sGtt4Frd1GtGV4Ms11zpHNODKABPzJ83JEVz6LRfjCWYYpV9w==,iv:dkPVAkR0l4+3wJCABOwJZ0DqcSy8VQBQYFEGG0lxO84=,tag:WNpPUZX/S9qwNrD3PbNQIA==,type:str]
  registrationToken: ENC[AES256_GCM,data:w8JsRmgVU3+ceRwpDW3eWqfy9+gQaFZy+8AdnunUfr9UXWb6YYl6y6IHa8s=,iv:nsqPWEbruDqwj75oB/R75gGthJMshF8UHn/XngZXV0Y=,tag:CwtBuuZMCZUrDmFFbzQGfA==,type:str]
  enroll-key: ENC[AES256_GCM,data:VZJE/rwyP/bP+PKsCNgpWdSc0Ggkhguxpg==,iv:OgebPUS7fsvJCogCzjGV2XKr55VINh/+xk3TvzzvDDo=,tag:j9oLvTal4/PILjoPUybuug==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMEdvQjlNNStEbFFDeGdw
        KzJ1WS9ib2l3OWQrd21IQzBWVTFNOWM3bnpNCjI1d3ZiTmxKeU16QWNmaDdPWXk3
        bFlLMWNOMHB0dnZPUXJ6dGhveFFtUDQKLS0tIC90eDluRUVsMkpZS2lYalB3TTRO
        c2ZyV0dVOVozcjdOalBuQm5Jd0p6ZzgKyqXIBkQJ0okKrUDgBLHX/A14k5Jv9eqD
        OGVPp9K+pEVDoPn4f8xaoI08HUsnPirytrjCSqvugcKuVhQstkB3oA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-23T16:23:58Z"
  mac: ENC[AES256_GCM,data:9ewQCg4ZeeSdRbVvW/QwCu6baxq03Vy7vkxbE5wWmxx/U41XVPcgOBYBzJBt1kMyvx2HZw9CLhYazszitunB82wFHuCqPTAKApryworkPPxYuip/AqMyJKvbGKJRRx1bUbvBOcAQlJ2WGH9suqR8e33tIpztFoCiJe4RR/5ngMI=,iv:6bzswOCXmLooEQ9yPQ999vUXXtnLjcCIik3KmeLjTzo=,tag:unC2aSIXm4gw7gcGgRleSw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-bouncer-secrets
  namespace: security
type: Opaque
stringData:
  traefik-bouncer-key: ENC[AES256_GCM,data:d7fgZhKpFMGWRjdupXpMyh/6NMx60R+QqMPPAhd9bWVV0Y0MBw1xWmVahs7Tx9+eGlW+WSFtZ0n22GT2eklsmQ==,iv:npAogIBYjRUNc5HseZNb9LzMDOa0bKVQ+1y281z5IUA=,tag:ieR10Go2RhBS408nMRsUGQ==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMEdvQjlNNStEbFFDeGdw
        KzJ1WS9ib2l3OWQrd21IQzBWVTFNOWM3bnpNCjI1d3ZiTmxKeU16QWNmaDdPWXk3
        bFlLMWNOMHB0dnZPUXJ6dGhveFFtUDQKLS0tIC90eDluRUVsMkpZS2lYalB3TTRO
        c2ZyV0dVOVozcjdOalBuQm5Jd0p6ZzgKyqXIBkQJ0okKrUDgBLHX/A14k5Jv9eqD
        OGVPp9K+pEVDoPn4f8xaoI08HUsnPirytrjCSqvugcKuVhQstkB3oA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-23T16:23:58Z"
  mac: ENC[AES256_GCM,data:9ewQCg4ZeeSdRbVvW/QwCu6baxq03Vy7vkxbE5wWmxx/U41XVPcgOBYBzJBt1kMyvx2HZw9CLhYazszitunB82wFHuCqPTAKApryworkPPxYuip/AqMyJKvbGKJRRx1bUbvBOcAQlJ2WGH9suqR8e33tIpztFoCiJe4RR/5ngMI=,iv:6bzswOCXmLooEQ9yPQ999vUXXtnLjcCIik3KmeLjTzo=,tag:unC2aSIXm4gw7gcGgRleSw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
