apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-lapi-secrets
  namespace: security
type: Opaque
stringData:
  csLapiSecret: ENC[AES256_GCM,data:3mBT5qAF8AQ6Qkn0B7pWCGMQR5IOlxWQ9NWzLq6hn/Xsi4BJNBpX0xAygtTF2PK4YqGM8/h6DetBjYFdNeBXlHC3ug+BQQO5kOKxiKETbC4Q62J2AAAHzg==,iv:JL9ciWD4cCOPTvA4jnauqL0pqeaYPIMXBHuZNzAd06M=,tag:udHXbUau8KndzI1JlATE0Q==,type:str]
  registrationToken: ENC[AES256_GCM,data:C4n933dTIISuprMFHx72lQ04zsvcasuHDg==,iv:nhp/32fo9njFuVb7l2AMlmrC4mLwQOkRua+o7iWDE4o=,tag:v0b8QOs2fg6sqotkf1dyLA==,type:str]
  enroll-key: ENC[AES256_GCM,data:bqsvkKbR+OjcVnjGmPUXWoTRERVR0stPcL0y0x83Mpvgt9mkmLK5yNzOv0FzJKn3CT37zWL+j6PNVV9XhB8hbQ==,iv:OhO8oY7X7ztu58uZsOLMcmcuXilwowyby/wrcj9nfdI=,tag:myIsxKvmMegslGXspWrUiA==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdjNuNWJLckhCUXU2NVEz
        RUlqUGNyV095NW5wUE1WZCt2VzVMTGhmN0RNCkttd3VGVy9zbHBLRVBXNG5aeG5F
        Mmo2bTFXU0F4Rm9aMG9kVkxTYVV6N2sKLS0tIFUzcFM3VDQvWms1eWI3OCtVcmx5
        LzN0NFVpbXlKaE1sVkVick9ORCs0WkUK+K/lX0RJhluy6IRLUwW5XfsMjEAZ805Y
        eENXU8KHWISmhspmHFNE5gsf5jgp6lZ0ZDTU0fCx2BKO7FqobZ489Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T22:11:14Z"
  mac: ENC[AES256_GCM,data:+fb8D+Fmg+63kpNS7oqHshws6/Va9ODWjLTLvpZhBUWtXjy7ir/mbyjOKpMF8g2Zd8zjSHiYGuLPh0yX1KCFUbVIhXIJgPwiqqbZbM9J0lCit5j9mM7utJssN0WC9N2s8mwW4LGtNF3teQzlcyFJsFvkz5AuhTAcVZf3nQVpmYg=,iv:B4pi8qxypjeNDadkjoqAg1uoKmLx41k63020vGUdwUw=,tag:XcEG2tp3OSXjr9WXjSdPpQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-bouncer-secrets
  namespace: security
type: Opaque
stringData:
  traefik-bouncer-key: ENC[AES256_GCM,data:lVWAbK9vxEIVeBtwib15SAQeXogM9/c28PTHCrskg4iLz+H3yDpzgZPzjhKEBeta0PMrYns/3doJwM7CRkPbEg==,iv:QLYzmZREbiT9T1kJRpb41QcyrPe4/PHQWa2Zz6bDw2M=,tag:9H6hgo6iwqTsUXsuZuW1zA==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdjNuNWJLckhCUXU2NVEz
        RUlqUGNyV095NW5wUE1WZCt2VzVMTGhmN0RNCkttd3VGVy9zbHBLRVBXNG5aeG5F
        Mmo2bTFXU0F4Rm9aMG9kVkxTYVV6N2sKLS0tIFUzcFM3VDQvWms1eWI3OCtVcmx5
        LzN0NFVpbXlKaE1sVkVick9ORCs0WkUK+K/lX0RJhluy6IRLUwW5XfsMjEAZ805Y
        eENXU8KHWISmhspmHFNE5gsf5jgp6lZ0ZDTU0fCx2BKO7FqobZ489Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T22:11:14Z"
  mac: ENC[AES256_GCM,data:+fb8D+Fmg+63kpNS7oqHshws6/Va9ODWjLTLvpZhBUWtXjy7ir/mbyjOKpMF8g2Zd8zjSHiYGuLPh0yX1KCFUbVIhXIJgPwiqqbZbM9J0lCit5j9mM7utJssN0WC9N2s8mwW4LGtNF3teQzlcyFJsFvkz5AuhTAcVZf3nQVpmYg=,iv:B4pi8qxypjeNDadkjoqAg1uoKmLx41k63020vGUdwUw=,tag:XcEG2tp3OSXjr9WXjSdPpQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
