apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-lapi-secrets
  namespace: security
type: Opaque
stringData:
  csLapiSecret: ENC[AES256_GCM,data:4aIipNLXp6bNMVQD1ozGAVl6AbkujpiYMfzHNFncQt/Sjc/iOeQenfderbUb19rhj+lIDaLCvqjohRQObWOOa3fkfplJAO1vMSHq4e/KCbWaPYjtREQXdQ==,iv:d5cwQ5yVF2gWbR7UvClD7Ooc2if7KopF667sTbsfk1s=,tag:AdizHNrDd6vdM+nXIEgsgA==,type:str]
  registrationToken: ENC[AES256_GCM,data:q30qrZVEOdMeOEtmjW6Mbak/sRTaq1QBEFU+QxNfaQ+I6RXpuRayRsW12gQ=,iv:fDW4uqCLwQK12z8Bz6NWgdQ1YWIpy6kvGOAWloLoviY=,tag:P9LXz/WWc84u5Lzn8jHoNA==,type:str]
  enroll-key: ENC[AES256_GCM,data:/m3n99ulH5VZGjaUX6Gt0tQeoczJgrUeCA==,iv:IrARc74tb2vUL5s1AQfu0+hlxNy6+rH9f5w7wDL+74E=,tag:wP4wv1ClFRoSwsIruprJDQ==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTnJENmMyVTk1NVhhai9M
        QnViYXN2YkRBVkJaSk42RkhYRzJwcVltL0FZCjhYbHMrT2xLa1RGdjRkNmxwZ1Bt
        TnFnWHRLZGJWT3pGaUs5em1Zd2RjRmsKLS0tIEc5TEN3N0NuZFRBYlQwNmQ1dkVY
        blk1UENaMEFkL2ZYU0hTMUpkTUh6UGcKJbXNWK4W/3qrqUUCs9RjgUNIsFW0AzHy
        02n/QAD/bnjaZJAk8olJ6gCNtEkhJmHi/3x4BhQTPb3eyh1MnAG7Dw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T22:54:18Z"
  mac: ENC[AES256_GCM,data:UtxCbTZVWpoS+5JFHUK/tQymcamMb8riPoAu3pdkUt7FyQliOth6aQIpcPw9NReu87p8EL9wVCT7TZ8Fbkd1OHQI2pI9nKRLxx3Z7CUkK/vnbTqrgY5uyoi9sebCeV1MK73/nvyldop3WYBUMnE/duXwr9IVjPkFgyQJZwHg384=,iv:UXG9D2RO62zZRr3N8cVRN1n6Qt0UE3gfDnJgrGgrfeY=,tag:vLyII40dfnCkXnBrxEWSlw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-bouncer-secrets
  namespace: security
type: Opaque
stringData:
  traefik-bouncer-key: ENC[AES256_GCM,data:3e4XYhd3fC9Mkmb/vl/a7efC/ZvtjUU0SRYVUcuQUrSU3UtjefTLik1d5IDFFKCUf6Odq16QxsKNJMtei0b8vg==,iv:xE0+5pEWfOPM++evsrI3BIYy6U4M2+KWpSNWQb7WEPQ=,tag:38TrLFdm1TYfR+i3Lev9Kw==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTnJENmMyVTk1NVhhai9M
        QnViYXN2YkRBVkJaSk42RkhYRzJwcVltL0FZCjhYbHMrT2xLa1RGdjRkNmxwZ1Bt
        TnFnWHRLZGJWT3pGaUs5em1Zd2RjRmsKLS0tIEc5TEN3N0NuZFRBYlQwNmQ1dkVY
        blk1UENaMEFkL2ZYU0hTMUpkTUh6UGcKJbXNWK4W/3qrqUUCs9RjgUNIsFW0AzHy
        02n/QAD/bnjaZJAk8olJ6gCNtEkhJmHi/3x4BhQTPb3eyh1MnAG7Dw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T22:54:18Z"
  mac: ENC[AES256_GCM,data:UtxCbTZVWpoS+5JFHUK/tQymcamMb8riPoAu3pdkUt7FyQliOth6aQIpcPw9NReu87p8EL9wVCT7TZ8Fbkd1OHQI2pI9nKRLxx3Z7CUkK/vnbTqrgY5uyoi9sebCeV1MK73/nvyldop3WYBUMnE/duXwr9IVjPkFgyQJZwHg384=,iv:UXG9D2RO62zZRr3N8cVRN1n6Qt0UE3gfDnJgrGgrfeY=,tag:vLyII40dfnCkXnBrxEWSlw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
