apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-lapi-secrets
  namespace: security
type: Opaque
stringData:
  registrationToken: ENC[AES256_GCM,data:KUw68u0nYo2BZI+ei/evsWpOqa5HhOyW3kdElX4LvAXRNGwxfydQpCagz6U=,iv:1W+tyRzqnlsiEr3OMfo1RnMV6DrFPNJDiByC1r6ZF3k=,tag:O+dhuqbrIhDe9rrSmDVeHw==,type:str]
  enroll-key: ENC[AES256_GCM,data:I1KTE/xM/p1+d7Vrxo+DNUCD1FbqukcoCg==,iv:7YLVnZYgApTUAk0IOBHQLCBwu79IeotM973OVABp+CU=,tag:jLXh0W7BVSQHhK5e1ofGFw==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRVBhaG1TM1QwVnE0eUxr
        a3FsaW1ZT3Rsd3lJTnd1U2Vlekt6TUlSQlFJClBybHh6akRsSUVsUklqNDZJYndC
        T2pWZk5UT0RGZ3ZEZm9qVlozQnFWSFkKLS0tIFhDcWlzVHZGZ2k4eUJRVlZKWG53
        dFpqMmltbmlrZys0bTdNYW1ncm1mRnMKVPQIM63gPbrrGIqdiSRxVpAt+/JytEIb
        caJqycaZFJmX/9AgWCQf1Ks7awBkhQT8WJbHPT8wQSfzK/dheMkZNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T22:18:13Z"
  mac: ENC[AES256_GCM,data:IwEkLc1M4+MZSJ7sv/NynoYml5MNwiQzKTCzZ6iXQTtRQ2ymCPAnE8w//gB6CmHlZn04cs1mm1HTWQm/c3bxj6KJqC/o0JVd9K3Q1iGSPHeedh7YdbkYBxdU/Zgo6o8e9fXL/A8BhUPSfKTn+YUftGQ5p19fGF8PwgbvrXCMnpU=,iv:gOC4PNJj6+wA0Du+TNnPtdssT+WTOBatrxbE0XuMCaU=,tag:htrAmL+SrgTvG01KjTcSiw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-bouncer-secrets
  namespace: security
type: Opaque
stringData:
  traefik-bouncer-key: ENC[AES256_GCM,data:kjjvwxiR9qCcxqrI/NHuHCxacbXnCz20/vFigoXdRIFwkQBs9dGgTl5ywQT6o0Vsm3ilBhjQjzxb4W2BZZhdoA==,iv:eLHfQZp1SPC2fQdEAyEmojFvdgFQzAuOYtb4sDWt3qQ=,tag:KAHj02FrqyI9CK24BUagLQ==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRVBhaG1TM1QwVnE0eUxr
        a3FsaW1ZT3Rsd3lJTnd1U2Vlekt6TUlSQlFJClBybHh6akRsSUVsUklqNDZJYndC
        T2pWZk5UT0RGZ3ZEZm9qVlozQnFWSFkKLS0tIFhDcWlzVHZGZ2k4eUJRVlZKWG53
        dFpqMmltbmlrZys0bTdNYW1ncm1mRnMKVPQIM63gPbrrGIqdiSRxVpAt+/JytEIb
        caJqycaZFJmX/9AgWCQf1Ks7awBkhQT8WJbHPT8wQSfzK/dheMkZNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T22:18:13Z"
  mac: ENC[AES256_GCM,data:IwEkLc1M4+MZSJ7sv/NynoYml5MNwiQzKTCzZ6iXQTtRQ2ymCPAnE8w//gB6CmHlZn04cs1mm1HTWQm/c3bxj6KJqC/o0JVd9K3Q1iGSPHeedh7YdbkYBxdU/Zgo6o8e9fXL/A8BhUPSfKTn+YUftGQ5p19fGF8PwgbvrXCMnpU=,iv:gOC4PNJj6+wA0Du+TNnPtdssT+WTOBatrxbE0XuMCaU=,tag:htrAmL+SrgTvG01KjTcSiw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
