apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-lapi-secrets
  namespace: security
type: Opaque
stringData:
  csLapiSecret: ENC[AES256_GCM,data:r3embROlowANaoXgX4eyeiQWkpCsDx8jrSWIEOsuxv7myM4gu0wtvTgIYaxqaI1ugo4ZOvRXNbOM9kMCebAjquvtkhEtWwQxB0lRfIuBjA4gwzJ6DESmCA==,iv:IhR15cjzCW5SNI6+pigaswaHok4ZZPPir8SiH9IWd8w=,tag:HxNCwBSPtih+MId3mm8mtQ==,type:str]
  registrationToken: ENC[AES256_GCM,data:FBT+xHDWR5iU0HiOTuNi/JAGD1qzsqH1eF/7YiTiTAWb4HUJTTsCFbz8AcA=,iv:vjIe89xfJhjbSxgNs8pr61Ut5rbftUNTVQqFLm3dRks=,tag:HACp8SOCuymUpa82nf4pjg==,type:str]
  enroll-key: ENC[AES256_GCM,data:c7X4R7FOiiB2iP8LIVN5a9NiP8W9MiGp7roUTBx39JxfPf1D2pG+Zih1C2aI+cGmgWZ5DwvZ+x7qfOqTa3uKbA==,iv:uFh4tCigZudnf+5+CIxg9UzwePNggr6hm7qRd1PfiaM=,tag:ckfnAQmexYESKd+inD8NVA==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WFErVllWOVY3L3duYnFI
        UlNlYXY1QUJoaWs5Vyt1TE82QytXR3Y1T25zCkZSblZERUNuaU1rYzlpekx2S2VZ
        WmgrcmF2VG9ES3pFRVJoTU0weFoxZU0KLS0tIHRPWHBLS2txOHdIMy91dWMzdFda
        NmZ2ektZKzZaQkFBTzJCY1hvZDBXdEEKMiiz4YLeC/QeFrMkJ935ZnnbLVlQtCCu
        HWrLfIpT0CdCAKVJboj0KaQuZwAiWAdsKj46qOdQ6/ZIVtf82dqQdA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T22:45:25Z"
  mac: ENC[AES256_GCM,data:PbNhnVHMzVlEm/2HYOnQSOrcm35f/cLj5TIIRbHS8dS+929D29REEfzgbx9N7NjusKn0vfW8qfSfL/sXipHobM7+MLzSc4pGfK8ApVmAdJwy/kb4KlxzWGPorSA7kXx9DQEt/+sFh/sE1eF80YFaa1ofQItJSwr5cqH2lJOVoCk=,iv:gfPt/q6QtKTsH118YKaM77oN6cG29AyFgWu7Wqeerm4=,tag:eDfqCGPG/+Yf+KN4Zsm8LQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-bouncer-secrets
  namespace: security
type: Opaque
stringData:
  traefik-bouncer-key: ENC[AES256_GCM,data:up5DOPId36n34hSD+4cBXsUfRqLpfv3nw9ycEMlhcJSu53VrJO2VZli2mRgIwcOH71VtVn2BV37gg3yDUGQ6Ag==,iv:A19yDOk7n3jow8/564MCX9TP8KKGyyeJIqzbLPcA5PI=,tag:Y3GHLMC1AzqB1N8zzX5wCA==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WFErVllWOVY3L3duYnFI
        UlNlYXY1QUJoaWs5Vyt1TE82QytXR3Y1T25zCkZSblZERUNuaU1rYzlpekx2S2VZ
        WmgrcmF2VG9ES3pFRVJoTU0weFoxZU0KLS0tIHRPWHBLS2txOHdIMy91dWMzdFda
        NmZ2ektZKzZaQkFBTzJCY1hvZDBXdEEKMiiz4YLeC/QeFrMkJ935ZnnbLVlQtCCu
        HWrLfIpT0CdCAKVJboj0KaQuZwAiWAdsKj46qOdQ6/ZIVtf82dqQdA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T22:45:25Z"
  mac: ENC[AES256_GCM,data:PbNhnVHMzVlEm/2HYOnQSOrcm35f/cLj5TIIRbHS8dS+929D29REEfzgbx9N7NjusKn0vfW8qfSfL/sXipHobM7+MLzSc4pGfK8ApVmAdJwy/kb4KlxzWGPorSA7kXx9DQEt/+sFh/sE1eF80YFaa1ofQItJSwr5cqH2lJOVoCk=,iv:gfPt/q6QtKTsH118YKaM77oN6cG29AyFgWu7Wqeerm4=,tag:eDfqCGPG/+Yf+KN4Zsm8LQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
