---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-gateway
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/network/traefik/gateway
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: traefik
  wait: true
  timeout: 5m
