apiVersion: v1
kind: Secret
metadata:
  name: talos-s3-secret
  namespace: kube-system
type: Opaque
stringData:
  AWS_REGION: ENC[AES256_GCM,data:1HhfXbA=,iv:RfYZanvPjgr+DZMADPJGhnAbclb5yDedaK43GEOJM0s=,tag:RlwRS0wZuxtGbNDYGu7LDw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ZEuYYOk=,iv:rITO/oYaSSLrk+N4SGfJH4L3pOzxpDpVv4uwn/YIktM=,tag:AGOM2KZ8NXQ7nXEI8so1AA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:woa/vwp8aCk=,iv:KnOAFolPCmxLbhmrNhyP3fNWq1dtHNb2k2Ug/uSwXZE=,tag:Qw3pnlMoe2uCbZdjNH8y6w==,type:str]
  CUSTOM_S3_ENDPOINT: ENC[AES256_GCM,data:kQicfzjlLhdKlGRg7OedKaB/,iv:D3vg5kFro8ORtm+Vsn4ct0TO0P4WKMN+xe9bHqM+dLQ=,tag:wc96q3Ul8XT9/A+1mE2ySA==,type:str]
  BUCKET: ENC[AES256_GCM,data:kOPNL2LfXVjCzVPxIQ==,iv:rRbUlmYW0xX7gV14qH2tUqHd2uhVCZa3252esC5xMtQ=,tag:0vV20jnRPHIaWPAfTqcWGg==,type:str]
  CLUSTER_NAME: ENC[AES256_GCM,data:jiusK50=,iv:Jetpa2Esg6KibmQtHjveMxgXHuLGtNClwEEFDX2x8zc=,tag:dMlp4r2MQf8b8o8TA+s8gA==,type:str]
  S3_PREFIX: ENC[AES256_GCM,data:jomZSjnFqw==,iv:jXYmO0IjEpbz4B5vt+CL5KyMWgjl54X/33uIwafOUh0=,tag:H7JrylMK0Acip2IMNDLvQQ==,type:str]
  AGE_X25519_PUBLIC_KEY: ENC[AES256_GCM,data:pkc3jvIkYRNBCQQaWPlw3KMWog4J6OWiUBVuDOddqGAV426vOrB5k4kZMsSak0blp8FPZBoJR13IEMZK2Aw=,iv:Zdc7oCqHJWMC9tP0S1NXqMPhx7rj0m+K8KSvWx6XXTo=,tag:FEwdsslYMMD6+Y/c+asYQw==,type:str]
  ENABLE_COMPRESSION: ENC[AES256_GCM,data:N+5Ivg==,iv:OaVO4/+UtxaPVqy8gCZlgkmNK+aATio0Sk6o3h+uvWg=,tag:Z8689j4TkOqplIu6AyOYNA==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUzkyS25WYUZOd29iNWM5
        VWZGeUNBV3o4YVB4YzF1T1JsT1pMWXU4Vng4CkpGVHFnTFFOUlgyQ3lNQUhwbmxF
        MkRPcmpnN29LVmRtOHE1V2NjTHN0L0kKLS0tIHBhcFlhRklOdTJDVWVQWkdrK2ha
        UEtKWThoOXE0LzVRZkdrWjVwSHFUVFEKNZAR6rYGw6A3D9yEgE1Dt8lCClhGuLkg
        iq4z4UuiW+nnKFtUZVKDIK1ougepxFkc+hPx/C8wcohpKrcHhAe8Ng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-22T18:50:15Z"
  mac: ENC[AES256_GCM,data:4YARX1UO/SJkT+uPUs6V4mPtG6qmX60TdKAnC43QbWpRcX9gHpJb5KHPGcqQ6yAfMHwcyGvUtVNwUa3W86nhyV2vyGOoAMTc4KxiUgndzlUvsCyLtlY7k3YIgjNAPuUGSAZo5EukPv93yrp+1J9b/H6uL8iPT3riDxfkiiOvNGQ=,iv:mkKcxJqgB+HELhAncxu9xoB4DwwdLpQ5nZ8Y6Tz8T0U=,tag:Fa13Xl0kWYr+24G5YZ12Ng==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: talos-backup-secrets
  annotations:
    kubernetes.io/service-account.name: talos-backup-secrets
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUzkyS25WYUZOd29iNWM5
        VWZGeUNBV3o4YVB4YzF1T1JsT1pMWXU4Vng4CkpGVHFnTFFOUlgyQ3lNQUhwbmxF
        MkRPcmpnN29LVmRtOHE1V2NjTHN0L0kKLS0tIHBhcFlhRklOdTJDVWVQWkdrK2ha
        UEtKWThoOXE0LzVRZkdrWjVwSHFUVFEKNZAR6rYGw6A3D9yEgE1Dt8lCClhGuLkg
        iq4z4UuiW+nnKFtUZVKDIK1ougepxFkc+hPx/C8wcohpKrcHhAe8Ng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-22T18:50:15Z"
  mac: ENC[AES256_GCM,data:4YARX1UO/SJkT+uPUs6V4mPtG6qmX60TdKAnC43QbWpRcX9gHpJb5KHPGcqQ6yAfMHwcyGvUtVNwUa3W86nhyV2vyGOoAMTc4KxiUgndzlUvsCyLtlY7k3YIgjNAPuUGSAZo5EukPv93yrp+1J9b/H6uL8iPT3riDxfkiiOvNGQ=,iv:mkKcxJqgB+HELhAncxu9xoB4DwwdLpQ5nZ8Y6Tz8T0U=,tag:Fa13Xl0kWYr+24G5YZ12Ng==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
