apiVersion: v1
kind: Secret
metadata:
  name: talos-s3-secret
  namespace: kube-system
type: Opaque
stringData:
  AWS_REGION: ENC[AES256_GCM,data:2EO01G8=,iv:AmTD3J2T/GZ89yp5kLs1KWybxTnR/bNj41GQxE26wMs=,tag:dLUqNtcbA5E+h07yygZKcA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:aiGFjxg=,iv:jQNF2bv7oUQA1Re8Jx96VCstKQyO1pFQcZW9L4n5eJc=,tag:7SWvC6Irs2VwJKDx9u8PDQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+ucImshyeo4=,iv:EnpgTClX6McxRz87XBgX5I5lpql2v7PFk8s6UzttDo0=,tag:5+/Mg4xNvqqPU+BMP4QQ9w==,type:str]
  CUSTOM_S3_ENDPOINT: ENC[AES256_GCM,data:6xwhelHiYC9lSeXlgHOnpYFK,iv:OAtSIOVPxn3Kh1obG909kiIi61YL1icEyOVYg+5YTOU=,tag:bda1a9UNygUyiAwV8LCpZg==,type:str]
  BUCKET: ENC[AES256_GCM,data:nMOBzb7DCXm+CRgDrg==,iv:UeUIf+05HGYGZWy9YnFyH2B3e1I0Qk16s2/U7CBTvHc=,tag:EJE9/s8nQKxSkzMzSt4Azg==,type:str]
  CLUSTER_NAME: ENC[AES256_GCM,data:vQNA6bI=,iv:g/Tj8w/EZLB7Xn7d5X+MfnTKiQPUlJodod+EzbJSDsc=,tag:iZnGFMg76867Rd+5R4at6w==,type:str]
  S3_PREFIX: ENC[AES256_GCM,data:3OD+47e7cA==,iv:l04xxyfuDfqVsdcmXmb33UaIQgXC86R+2z5kcNa38BU=,tag:1lrPiW9Cb1rhiErLNYlXag==,type:str]
  AGE_X25519_PUBLIC_KEY: ENC[AES256_GCM,data:3Lm72Ihna7xw7bi0p80md88tdLrBaAV9ciiq7SaIrovnZnAD+57OWa23CbTzBxpQ0kj14VKFYo9cAMuXIlw=,iv:Jk8WzHmV6Mz8WCskuLNLjTjrWCZr+KflJOdty8cIgYg=,tag:Ai4jC8C2QMfmlckc0/EaKw==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBc1JuN25NM2VxQlh4OVJN
        ZGRIVDUxL3NUSVlYSWl5MVFTZ3IrL2NEM3kwClNNTVd6Q1NRN1FKSkpQWnhTanQ0
        b1poYVFSS3RTeDFqRmVWMzVFSzN1WUEKLS0tIDlobUVNc1lTZHAzeU55YUwvd3gz
        cnRoanlBa3JaVTB4WWdlVGlNKzlqZ1EKbDxq3FZPG+yiewumSNyyvM+1ihKNQjhL
        myRjZzyUaSg91yPAyl8yI66bRxTKh7g12QPKT4LkkoXSIIJqwTwr+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-22T16:03:04Z"
  mac: ENC[AES256_GCM,data:Puw8cTgYvsANC7YTVc+bZoGWZeUhziWKBFZ0D2n7FxsVcRkN0fT4y+57IAY7ldF9A3+dKWI7/6Zn5YMHALMgX0BxxdwaNMjtdlWSZv4d/goNcq9wKTW2PQ4ZobrE82ZUefmlUs3LhHIN0044msPqFmwfF1abGYH+yUU09X4G8HM=,iv:iRSizInIrAyF76Awq/bjNqrbJhVEwnu/TUC+cdENqd8=,tag:IjGKbVwOIss7NoXIArjERg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
