---
# yaml-language-server: $schema=https://crd.movishell.pl/talos.dev/serviceaccount_v1alpha1.json
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: talos-backup-secrets
spec:
  roles: [os:etcd:backup]
