apiVersion: v1
kind: Secret
metadata:
  name: forgejo-runner-secret
type: Opaque
stringData:
  RUNNER_TOKEN: ENC[AES256_GCM,data:K5km05wmfno4HgiYwEQeP8Lnd9Dktp2LVqeVAhXIyt9Co+onaTXewA==,iv:I4LGl99NYuarnk57MTZbHQ2ld+0t/UJOMuVAdl15c+U=,tag:BlGaNheCADplUat3uPdXYA==,type:str]
  FORGEJO_INSTANCE_URL: ENC[AES256_GCM,data:cGs17yKNLhJV6UQ8x7qWLi0BB0A=,iv:X25FLv0SJQx3FluC81VFletY7dnnjlYPaJeuxO39rGc=,tag:3M0VBUQWdGKziVZrEKsIMw==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aE40VnpmeENpS2E4VWV1
        YllBQmExd1RYcFpwaTdjd25zWk8rdlM0TmxZClVRTDd4MXR2NDJTd0NLbHg3VnZq
        YTNCWlo1bzFadWtIMDZqQngyRVRFWGcKLS0tIGFNS3NjbkJDd0MwMDM0VnplblIz
        Z09jcXc5UXBaY3dHYzZpNysrUGEwSE0KtuyPrgrFQ2vPWVv26qs/go/fF+iUcwW2
        SxedBjlmyoG0b8NqKcBOmai7fXe0NmJY7ggfrSpK8KV0RTZz6jdQdA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-02T19:40:13Z"
  mac: ENC[AES256_GCM,data:GJ9xN2qn9zJC2jMz25H2rzODT2Hs52TuZMIaPv/yNyR6qcydbzRxIYfwXhyRNGWDJPRTJVwev9pjSEEsquO07hpMevAeNbSL2TKNM4pu4cG8GXmQrbBtgU34w9m5BU9+ifCbN5hfckBtmczAXSrqMD+0/+WnGTc/9cw4CgEL0iQ=,iv:U89eWH1L1KLeYo8SqGhK8uW5W8/Ps2quMmC344xXpfc=,tag:NPIEljUKDs5/JdwOSmRBTQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
