apiVersion: v1
kind: Secret
metadata:
  name: forgejo-runner-secret
type: Opaque
stringData:
  RUNNER_TOKEN: ENC[AES256_GCM,data:V/vQ9QwEJDmSa7bWOBsKQuptdprIYUd0ap8EJt47zpr6W9HwI1V5,iv:4svLtnVCF3Ze2072uDwPAYmfWJ++KvXxEl0nK8w1obU=,tag:r+83iDztZmHJDQ83sbBI4Q==,type:str]
  FORGEJO_INSTANCE_URL: ENC[AES256_GCM,data:Md3D0uohhxT/JyEy68RJyCuiGnk=,iv:FJ7YuijnXKZrRlAiuL/G0OZe83dbm9hu4mvgi4n8jkM=,tag:Z8sQle4lcvfqC8qcHDB14w==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOS1FDQUxtdjRXOTNFRHJu
        RE9iaTFxbUtjalpoaUdnSWcwVFNCZXUrYVIwCnQ3NWRKYWdVQ0JzdWJMUGpvSUF1
        R21mVlY0L3lnUzRNeklDUG84LzQwc28KLS0tIDdhL0FRMUFzeVVobGdZSy96TEZm
        N2VwVGVBL0NaS2grT1k4OTdmNEVsMk0KnEUUBLaSwYjj062XjDLNS59jVqiJuOqn
        WUVNDessklQJFbLZTKQ+u37WAZ9XxcStg9d7PLYdx4EjejGPPZqJSw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-02T19:00:52Z"
  mac: ENC[AES256_GCM,data:ya6c6xqLHbg7xBoFur62rzqzcPRd4tb9Jm19eZQQLgjGyPT/qu3o+zI4NhPAWbKWDRumZJOiVLQiDHu1Nqz1aI9U1SSSEERzsjbdHK/fduhq3kQdwQEjBa7fQulHlK1tAsUYcYeF0f5bfAns3b5IpuDwHKxv5nb62tVyInkOgX4=,iv:dHEti5Jpc9MZkGT6AEyTRG2G6hVcuEbfu+52VbIec+U=,tag:wB6eLRLyQsKo5h90nKk+UA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
