---
originRequest:
  originServerName: "external.bth.wtf"

ingress:
  - hostname: "bth.wtf"
    service: &svc https://external.network.svc.cluster.local
  - hostname: "*.bth.wtf"
    service: *svc
  - service: http_status:404
