apiVersion: v1
kind: Secret
metadata:
  name: wazuh-secrets
  namespace: security
type: Opaque
stringData:
  wazuhApiPassword: ENC[AES256_GCM,data:o62Jnz9ttA6+jPxpaIUrjIwQKPwaI4poX/EsC6Sc,iv:pEcykVUZ2I1sc1waWqznmQd3pUkVyzz3LY7ldj2alOM=,tag:fd4+8dadXQg1sNrYhRAX7A==,type:str]
  indexerAdminPassword: ENC[AES256_GCM,data:Be6zV3IXGPcTiZBYx/tAQROhf3kaNM4ZxK4Ba0VX,iv:YN3tLztPlTvQU1gN5S8RzuJBRh+iFYjTihPDHkIxT+8=,tag:jitWeSLHRTwRXQgPoQphOA==,type:str]
  wazuhAuthdPassword: ENC[AES256_GCM,data:GGb417wgUnBXFBobExroe7MIg7Gqu7LZSsdNrv2H,iv:ov/OEBAFGL61VLBDxH3dO1Uf4zktFq4Cvle2sUYDgL4=,tag:1OemOUvY0vFEDOdJLzhbGg==,type:str]
  accessKeyId: ENC[AES256_GCM,data:+sY/k60Yu10Y7FFbKA==,iv:MHHrYjNcWZkf7OSePq7t7cVQVa9UqCv3+BmNo++qnNI=,tag:lodjf3uabPcIbMdXRvgNTA==,type:str]
  secretAccessKey: ENC[AES256_GCM,data:U5PP2P7JfGjVMExzxr2SCQ==,iv:fUqRmKGcsRisc2tf1ib/6GSe7NagNcc6yWNyOrdlXvY=,tag:wwPvsiiRE93v6p9E804bCQ==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSlFra2FjTGhGeU5sVWY4
        cmZqNVREUVpuVkswWmN4VWlWdHFiNjR5OWlVCm1vdHo3TzU5T2dHRld1Q3lvS2dp
        ZVBzQk8rNkx0RUZTMDNrMER6SnZ4VEkKLS0tIGszWFBSY2E3cFZGbVhiT2ZyZGxB
        akx4TUFURFo1VHdXT1NzOTJ2N3J6Q1EK/Cb1Feb5vVQ5l9gRpRkPC3yEmTMY7rCU
        NgKta//NCssSQWon0IfOCYFrHvciGm5ONJAdj39l4FBcCwt5GNP2zA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-14T01:51:18Z"
  mac: ENC[AES256_GCM,data:Gxo4GMYuuLFVEmD79jHYPbNJK7+D2FhTHY83Kk3jbsTVV2MhQRBL15ehVuUDrGQKdjRnGIupTU2/zh/dUyzpeT8dAiEjGYpB8LTdKP2NCWsGZAvf0QMEhz2XlEIGeYB8sxmBLgX3VrIaKpHZ/DONBC1NOSU1BVu/eEgOoLl/Ies=,iv:uFh8ahXX9G8qPnk54qlANPfzLt/c/vwSwXxBJRcntCw=,tag:HNPu1vaNCEDF/comjPn5sg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
