apiVersion: v1
kind: Secret
metadata:
  name: wazuh-secrets
  namespace: security
type: Opaque
stringData:
  wazuhApiPassword: ENC[AES256_GCM,data:lruvHsSO8ztilTNrdO44O5cjdNJexkdmjYwpWd+F,iv:l1+IyyrUHeWDaPERHPy6gQT/7rfaMcbxrgV7LJEjzjQ=,tag:bv28UKcg5Pduw+da13H4TA==,type:str]
  indexerAdminPassword: ENC[AES256_GCM,data:ILOtqE4he6SfJpWlDipf59dSin4OIXe0u42WFRWY,iv:dOG41c5FlQ4PpafPL3BB2XMmffhh7OkjBG6BFd626Us=,tag:h11fnyh6ky1P3JYJgPrJTw==,type:str]
  wazuhAuthdPassword: ENC[AES256_GCM,data:MrudsI2w67trmRzHOeER94t+VjIPsag2TyusiPUB,iv:ddTBn1rwLUq50EzKBXh39BZo0fU4YZ0QrrN0D9yN2gA=,tag:ctWYyvQFJaMZrXGmFiWE2w==,type:str]
  accessKeyId: ENC[AES256_GCM,data:Ths8PY0=,iv:3+pMJGzHGRkoOzMGCOdF0DQPJdsMaK/DFRCA3odc/Tg=,tag:NTLffJoD7Mp9OfFRqLrsTg==,type:str]
  secretAccessKey: ENC[AES256_GCM,data:qOMaeom4CzU=,iv:dcUrqrojOt3RwLmvWBjZYxH9H0tSbnBn6MX6717H/jk=,tag:3d16npmta1WU1uzK3Am6fQ==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZ2l2ZjZ0ZEZJUWNZSXRD
        K003VDRtbU5aUk42ekJLOXUveExEZkF3bFFVCjdHcWVONXVGcXJzVzB5UjZ6eG93
        YXAxOUpoMy9zYXdxV1NubWJOaElKd28KLS0tIHpLRktPNk9xSDhEZ1NsTTZLcW1T
        eHN0Ykt5NVRuRWQ0WW9CTzBkSk8xbU0KnV+tMr9NOS6tSZi92qT0Ewk2/Xbt9XbA
        8leUboSCbogssXdMKa3fKON20JSgTFG8o5eVkSi50Fc8Rm9HwziQYA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-29T15:27:39Z"
  mac: ENC[AES256_GCM,data:owkefgrlTbAifHcP09bVE53h+YXAA3M3AlERVcafR476aAo+nxGLRls+0FK6Q1QHXofg3H71N8YdWbXPk8OyhBTEdR+SjeLggksiy6is52PA9cXXcbVogYQw84CznZlKTSR6DTTn6nB4qQW0HvCQOjbVDyR/gCaX8eSuVlvwGGw=,iv:uXF4Vb7IkvaylxQXVwp/wqylHhoGfsHvXI5opi1HqKI=,tag:0RdQCv4ZqEPcJdy4Xx15+w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
