apiVersion: v1
kind: Secret
metadata:
  name: wazuh-secrets
  namespace: security
type: Opaque
stringData:
  wazuhApiPassword: ENC[AES256_GCM,data:i+myf6C4fFwMTHmg7EEMqng6h1Rj5DfA7YBkybQlNLk+3BfSDrnL4bmlICIwmTMozv22Jcff7PKCCyynBnHb1A==,iv:X9G/oE5LLtz0loK+9rQZQO3qJJlNFBfADCKWZO/qVrs=,tag:XyRICxsQwvR1GYL4MDsNRg==,type:str]
  indexerAdminPassword: ENC[AES256_GCM,data:Zl+ylPCAtMZc7kVqqxMvPY+xIvI/55LRJaq4gpsRT3ixL7nycASvP0+SR1vRG7Y/H/kkrQ2Yn7fQyKf+JEx0ag==,iv:Rhgn59zn6a0CidSFZmwVnFUzHA1oITgbccCHqXcTZOc=,tag:b0aNQO5v3VQPQ9xwJnq5/g==,type:str]
  wazuhAuthdPassword: ENC[AES256_GCM,data:nmWFnA5Z256wW3Qjy4I37Ed2VfEC5RgTmZtCpJexqeWwvEoFzh3nZBtikuf6qcMR2IJ3EODMIQ3mkBetk9IjBQ==,iv:P9ulEiAVp16NZZwpgVllQu/RzprEzHXAZBFnB47WHTw=,tag:SWtzBkEFfeEJeOGO0g0ATg==,type:str]
  accessKeyId: ENC[AES256_GCM,data:TdB9l3ftJmM0388nzA==,iv:65cX5w6XFEVDg9UsUM+apBdNjJKmRpEg/1JDED8Gess=,tag:Aaow5w17pFX0RbM1CqDSbQ==,type:str]
  secretAccessKey: ENC[AES256_GCM,data:20XqlO3QDN+eAZd5eFoRmw==,iv:LxqCtThocMlzjv+ttBYNbi7zm2dh6LoL5DbEXz6SEx0=,tag:KbMK8oD1BFrsNifIr7Mq2g==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWms1bDVCeThGT21ucExy
        dzZYcnVWS3NJWG1Ybll6MHgzRmZrQml6L3prCjA0R04zK05CZmxRMFhsbzZIZ2gy
        aEh4TnREa0picEJidWRBNjNDTE5GeG8KLS0tIFNqRFpTT3JQWlJLVWlaak1iNmkw
        UnFCSnYybEdrTk9pcWRBQ3VsOWFBaEUKd4LzIkpPjZp4WDT6Lj32uVQhatdUU4m1
        CV7IIeben6+twnq52VBkjPB8OxoOW1SoJ7W+DaQozYl3cYjS808e1w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-14T01:38:02Z"
  mac: ENC[AES256_GCM,data:63YTZTFwt8T3tnLFbKTBy80L9/DqzVfFFq2y3mNiEmtltj/8BMUyvHLp9PvEORviXIPKTcqQVlRhL9S5JVYnh1fxhrMwBDzaSXQgPnQcgFsGzEG4Sh8kx7PKxoPIxDxagw6Qc8NDEow+bpCdNEkqlV1O9JvDECEQvxMumgn3vEI=,iv:5B/UG1GSyRcKgrU8hhWWWfJglj1yTu4gHCEiBzV0ONs=,tag:gnBjKDQfxz6kyhr2ZFU1qA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
