apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
  labels:
    cnpg.io/reload: "true"
stringData:
  password: ENC[AES256_GCM,data:OgsKJrvwbEuoWVDxYMQ=,iv:X+LHfMsA5j9eHxPL2vVKxcwXUkZYzvhNZx9/9sTbw+Q=,tag:zgILnKYp9/JWFjZueo6uPQ==,type:str]
  username: ENC[AES256_GCM,data:t/YUfC2q/WM=,iv:0ArLUDHyhRQ02AqDoQJ1Mfu+l37A9J0GdAJRe76In0o=,tag:UpfkIJFbdKSPGv7CsAeHZw==,type:str]
  S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:7yc18obF8MLAp9lZTg==,iv:RYSokzRkuMgjilzuOOoCSpRoVjZo0htd+ZqpL0tAtmY=,tag:FjAZTVf8PMG41qlQLcytLw==,type:str]
  S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:oPl1K++fPlNDaEdwYphhRQ==,iv:Q8k5jZ3m+fnA+1nVfdzV/DhOVrJHMuxkOr+2vsOu15c=,tag:V0pVBV6kZ8hJNYAGY7Q4mw==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWkJzek5GSkcyWTVpblNE
        ZFYzSWFUcm4rdmN6YkFObW5KeEZEK3dGMWp3CmZOWHVBbzdvdVE2WnpoZi9ydEc0
        aFhaaFZlU2x0aGpiU1lHcHp2bWxJakUKLS0tIE5waFVKRjREZlNIRFVPNURKOFUz
        aDRLUTRnTm13Y2JkbTlka2hSWkVEZkEKxV0R/Vo3gm5kLV5UCiFrteOXtfG8Isra
        TY4Sk0sDqgSOSv9WXXCsXQC3E2SkMN4A8bAXLxoscR9/Z2RzpR382g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-08T20:31:25Z"
  mac: ENC[AES256_GCM,data:tufEXgHexcYSN1xHoCQ27zPTTZ+2BpXRjMGZbrKYDbdDACCXfEuOTJx8UHZCfWptW+2r704RaLrY1/LpKSs84keDnDVQiqSRX+vwOMiFmo3Hfr4HHU7Xj71jGn6RMdvmsEB4QH3Cy5cIcbNgobMgCCIlpVKqc+WEfMCxvSTz6jM=,iv:8ADLx2i8Fs5K/mgK8EqaBJi9g538/kT6p+0D8xCgq4s=,tag:Wn2BHTF+3YTKebgJWWKAfg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
