apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
  labels:
    cnpg.io/reload: "true"
stringData:
  password: ENC[AES256_GCM,data:ViHK0r0iZJarvvYD/90=,iv:HbosHqaKfU6TK5uAdCQTi/txh13utsAK+OcSHIATI8A=,tag:PqeFGRqXJ0A4RwCmmDNGCw==,type:str]
  username: ENC[AES256_GCM,data:3jsQXTprQM8=,iv:R3FyD+WnBiQN/VJHtsSj9wnhv3mbW1gYQeNtI3dSZWk=,tag:k+GO/e8/onB8Smx4IqIM3g==,type:str]
  S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:wWtKmUsiWQlvZ8rUQQ==,iv:ltoPENnW92iAhuPs37iapnkvhONVmuvblZBH8jmTqDc=,tag:QAXKSVL+kJiGWdVmtNONbA==,type:str]
  S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:sVAdobKbwqDT4aCMoDPMIw==,iv:0uAhCu14MthVVXOM16JKAutqHmSWeo83SmVNY/b072o=,tag:KtqUSUAcP5Bb87CvowpVfw==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1azdudXJadlBvYjdkaDlj
        K2RBMjdPSkpwTHU2SXZLbnhBTDMyZ2tuVUQ4CkVOVi9LOGVJTUthMzFUTjlYelZJ
        czVoUmlxSDRqaEppNWZ0Rjh0R1UrNXMKLS0tIFdxMDFaKzlneTU2Q3ZSL0FVc3JW
        aXZPcGtuSGJia1FpZkNkSVFxdlFTeGsK5+nFKfAQX2fiy75UGfcO1rZ5IjjUesoJ
        OX6heYZ97F5WtSfRda3HlSaPHKMl1yMqfQ9aGk7K26OBeTh0E3JA+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-07T14:49:25Z"
  mac: ENC[AES256_GCM,data:kP9MFIdb+QWxDPei2/9BDwRj5j1rYTVpLPzXOP+jFUXPp/G32dAV5VjJdxashYL7M5E61sTf0u+VhYM/WWMmbcxFV0dvwxy12deheUzFOcwoYUiYTOjRsPId/WStqi8lMS8UDS1viNL3eFGi/tjMudaImqiLNp36g0HuJPr9Uxg=,iv:xhhEIZ3fYaNMuWjM243gnmM69GF5+def7kSsmKak908=,tag:yGvf2/H8RaIIlURfZT9EMA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
