# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: mimir-s3-secret
type: Opaque
stringData:
  S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:0aFZg6t36rocRhqjIw==,iv:pZbHhNjr1DNZqlhtPVHbRlp0yuHCJb7q7GwMjy2ODv8=,tag:WmAN8DavIR0h/7NuxmSSjA==,type:str]
  S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Rg+6MP+ctrgw8YexDb12zg==,iv:VtSMHBoBNUIjVn5/RNK+oGutuwv2i85sXioC9bIWsV4=,tag:jY1ioTY1o2mlFqYc9EXvRw==,type:str]
  S3_ENDPOINT: ENC[AES256_GCM,data:/POxIQ0cDO65tce9XI3TwWsu,iv:J4cqgg0N/f+mHBi+RgwtK5B06wY3j1B22IQBzdeD2Fk=,tag:4eiJehEVLMi+0djy2kPFTQ==,type:str]
  S3_BUCKET: ENC[AES256_GCM,data:aP7nyiM=,iv:XoTE1fZtbNLSHNep0Ig+ardC7vRIjie70eYQ0tojYfs=,tag:s1vzS/lrPFy1Jr3jd+1zgA==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MGFuM2wwWEwxM2hEMHow
        YWNraVVvT2VJZitvSXVtbEVtWFlFaWRtNjJJClZjWDJFRFhiSkZwUGQ0b29MV3dZ
        N0J6YXl3Z2R6Ris5cFYvdGVnRmtZeEUKLS0tIFh1dG43TTlIcUJrQVJCcWtjLzlS
        dFdsSW9Va1ZSTEFNOHhHa3ZiM2ZhOFkKmH44wQzF4Lb7RKPNX/vzcYnBF7Bxsvk9
        cVCRPZVAsywCo+lfG0nzFWs4Ee6Y3r/IcWBtDzF8U9Ra7Xul0DpMnw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-07T14:50:02Z"
  mac: ENC[AES256_GCM,data:jTxqlpG5drtmkV8cCwgYy5xUKgmQI1k7sJPaOgOjoFokvwqRN06mC0UpgHRYMrpWcIN45R+Z7s8v+1XH2097TJFascnEQ9sPeE5ONRdo3gZYvM4ffi30kGaMqPERZ7ZvCtqkUoBKBVrQSfCssFHkSDsY7kJ+NDy1f8naL2uWVh0=,iv:awEIK2rpu8viZYCYhC1ZRpsNrgZr03DwW1Lrg3FLSSM=,tag:aLo3GqguM2hXMbGHZCFMEQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
