apiVersion: v1
kind: Secret
metadata:
  name: victoriametrics-s3-secret
  namespace: monitoring
type: Opaque
stringData:
  S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:pOr1E7BYEdZQi8OB+w==,iv:oU56BLGElhGn1H9SW39txQGEhwvk35+2+7UmATzbvqg=,tag:ysTD9opyc4e2fb9fsGfYiA==,type:str]
  S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:02kqveKoWjmoXQeXgzN8Ng==,iv:ipze6IQFAyNB020CVw+bByfVzbWJd+r/lsWE94ad7Y4=,tag:FHwOpDGCvdephKg97ghcSQ==,type:str]
  S3_ENDPOINT: ENC[AES256_GCM,data:1MbOdjxtrcyYzKERMXLFqvke,iv:O2Vxq+kqYHaZ0OdKsVNwilfO2KiFGu2Mt7L+iwvoNh8=,tag:+fBk5NxU+HPdvTJxFbO8uw==,type:str]
  S3_BUCKET: ENC[AES256_GCM,data:XvG9JOhHJUchWZv5TBNWvz+hn44=,iv:w9MUMgg8vll3PJTDJHoEjx5McLL1mtvXPA0s5X6EGDQ=,tag:YcPtUkgfRxFPmDQf84jaaw==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJREhwUUdtb1pSYUtXWjVM
        cHJqZVNDZGV6UmVrT1M2ZkgxbDZKTHBUZm1VCnBKUzYyTUQ5UUYwTlJzOEFZUkZG
        d3hRVUU5N2dyc2RHQzZFbXBRRVBpaEEKLS0tIGJVdk5pRmRyeEJPVW5veVl1cVJp
        ZkIwYTFGN0Q1MlNHcDY0STJ2VXBnUlUK9Foo9S88CFjiGP+SFwhylOwP+0r36GAm
        rsR9je4WbIo12wu0zuRX3YP7jXpomHfj3Djk8Cs9tE/5gzExC21bVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-11T22:24:06Z"
  mac: ENC[AES256_GCM,data:klnzhMRRw3BHYFXb7CEEqRXrCpjzGYK298a0gYBX3oh+aantqjeS3Chp7I92/v3zTjyfbs6FjXLRv1jKngThIqyHCBWGaarypqzffixzGoTf35uUfRbTknckSUvSNjoH1Th7KQ5ksG5fSv/py0wXZhR2/hnDi8RTqvnoZB8G4S4=,iv:TQH0sc3N4R+mIDyUboUvN+0NVGdWFy1ZqkUmc8a0I28=,tag:CoZCUqwv2QLDRtWyDRq6Nw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
