---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./crds.yaml
  - ./secret.sops.yaml
  - https://raw.githubusercontent.com/traefik/traefik/refs/heads/master/docs/content/reference/dynamic-configuration/kubernetes-gateway-rbac.yml
  - ./middleware/
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./grafanadashboard.yaml
