# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:KkBUAVZF3KMhdpfJ/cCI5ONGL7IZ5aBu4flXFoV5YZiom/MWyUNgrazGTmDumiq1sjt/gcaW8JtWVP3/VgVY6AMCa8YxlYQV22swv8A/WnA/NsrelO2ScxNS+ePWpVcqbKtsNOybG0OZzyZgUltAclZcD3UK8AAB5ruobfyzw5OIDvubylLoHpGxgC7Pp8DYp9qlFIfe91t2AL7aRrhHJSwd6BMOFW/KVxoze4ex208foDn0Rg==,iv:+KDOlnG91XHFWlQq7acuvLVv5ORfUqc8Mcsq4z/o+kM=,tag:gr+7LSGwy2cwxC02LWjcog==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYTdqTnh4b3pObGdTblp5
        V0xYTy9xeXlqTVZpREMybXpuT0JEZS9TYVRVCm10TXFlekJRc2dUUFNrWEI4d1Va
        dHBZc0wyeHFZRzNMb3Z2VG9RNkora0kKLS0tIGQwUDVndGlwMEIyMW15aTJnSjA5
        Tlg3SFRJZHkvUVBYc0FhQkpzRFgxUDAKlaapKp+yOY1o1GUTQlIqL3pwfsRREoQt
        xXgn3IrSIS5tszAMKSW41DguKJupZD9f0/B9Mo80axpnHnujFgcMFQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T01:37:49Z"
  mac: ENC[AES256_GCM,data:Iig2uVoVFSm6gTZ4UluPZn2ANGUclxNNCTSGJ0+rLmrPGJNOH50wSVnJYhC/9qFCGyFwRQsknxnDMWWzPjiUZx+2ttcJoeVu84Fy1eBTC6eHjK/dJ5loRTpjV3wWoFMwM2OSqUGxFeopAgI53arqWyCsTozGpRxB6uVGAWoREtg=,iv:JlBMq9QD3PguCz1gJ31uDnqGRkOJxGrvvV/tKdVOHes=,tag:v1StUJNHRKg1jBzk30ulPw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
