# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:L2W3IFiYUhb/EYXBBx5i4+5qBPKYGXCwlf4+fT1eI/y15wu5D4ly8gT1jphJwGnKdgE8o8eM/PaWK9YgMmPnyuLojxkx3BRuvVWC9juLLlo5jlX10LD7q7ot+QCl14c+s6oczl8RpSkD4vxt3J3ysEzRwq/3nlQnudtUZE5o5DQd6hBn7NVHBfbdiklWCw07WRiA2ZW8PGNjz0E5M2ok4HQYJ60D7cOQdKs2yWQtCQcre/h/ttNTu5A07oYbhG/yindOj03Lj8KjfREEbEJdguifkInfbcrHLvSbqKTnbIiiCkA6DOxDMenAqKuQ,iv:mGCpSI9lXFyZ7+NhSohzRmaqnP5R1NqQDtejCy8/Y5E=,tag:Hm2z5bqVtuPBvJrYhYxXAA==,type:str]
  ACCOUNT_ID: ENC[AES256_GCM,data:fulJHJ6dBFrzHoYM2lFOKb/3PFZv7kcYViBLXC4lotI=,iv:VcXzrqB+TYhv3aW4Y/i3dpn7jimROdef80Uy+AMa3Bw=,tag:7qyTUrj4jQvw5u2QmgzHWQ==,type:str]
  TUNNEL_NAME: ENC[AES256_GCM,data:5pJfyg==,iv:DyJvX/EAw7HcB51SbxSJNr2oeiF5RMcNUlbNxCAjOIA=,tag:KFOIYRwjJ4DeLBVjjvh+IA==,type:str]
  TUNNEL_ID: ENC[AES256_GCM,data:yAAd34KBPWMvtlE/yBU7vCo06QDAtI2SDHi+XRL40iMIbccw,iv:UBf7sFIvLqYRPapsIfFRBvpToqWeAdwkhrFqQer2ABY=,tag:HHx2+1qp/MXH+46KTDiHOw==,type:str]
  TUNNEL_SECRET: ENC[AES256_GCM,data:wKz9SCHdxge3GSZY/a3ww6gWSVKu6XGV8p21xO+TkKwRlV0gDAAyeSneUqY=,iv:I7Az2RvF8eRRTRgbIBHapQQmhxtYrWz6un2o6R/SmG4=,tag:WNCAZApR8ove5bdxCic4ew==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcjlvQ0RWWlY0am1sRDhp
        QTJQclZ1N28xSTVTSXVCT2N0djcwZnhvZXlNCjhyYnhtYXdaN3lHazJmcnE3cGV4
        dlMzRWZRYVUvRmZpWTRRTWNkQll5eTAKLS0tIHIvdzlqV1JZUzRQZDZTNE5UdjYw
        WUVlQ2hOektQYkkyWEV0dzhrQ1J4MG8KJjmYVQI4OnHgh8KkYjFwB2mKKRB+vz6P
        2pKd7ExJDLeCNZOBkdrxfmt2+8jXn8YLUkFFmM7ItrdcUCheS6PADQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T13:56:02Z"
  mac: ENC[AES256_GCM,data:uQPSlNWE3dYgkVTdZ8w1dUFdkkWBXGg+wyq8xwYHlgW8qKM3w53rTENL8ULDWGQlmKowF+T4NSePFUsIVzUwe2vCDk4F7QtBUoQrcJpKidbvTesVggX5PYFVTHgFjv914gB5AkT3kwEVnPv0TlQVOtOYUdX1o3UnPLWfD0duwLY=,iv:ooBh+MvtoO+Y7oL9chUVWj863WjYa2lXlXy9iZteKqU=,tag:3GKy2pYpH8EHBhSUTRiSiA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
