# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:aLaEyR6v43Dt4hObESbbz9FanQ3q2wAtem40Cl7AW/2HECpITAnfTHQakunmTgFe3/sbGaN+o1pEWp6RhE8ITYw70gOYHtYYUcUqd4WaKiWrkbFishUzHT64w/7K5y+UdsYr9T1dKEQFU8nnUWZG7s9Aubl9aHBdtt6V47RUOSSu1vP97YdedHrw/qkHjoLgUQtJ88lU5fWRutWPQo2Uoc1giusnUDeRLG6JN5CAtpk=,iv:2Blm2mAmKm+KU0l/05mkfeiV5PUr3dDY1HMqdIb6u04=,tag:dvZh/LZPvmLNTws97R/qpA==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVm1ORWRycUtBVmNkbFlv
        YlJmK2UvVWcvb0ZWNHBadzlxUGc0aUp6dWhzCjhOSVhHZ21ZYXN2ZEpHUUp0NHJm
        UE5EUi9VL3RxQTFkZGdQaURuRWdrRW8KLS0tIDh1aTl5QkZKTlVPd0l5N0kzTWNz
        N29JVHNsNXVrU2pDZ1gzdmYzTDFsS3cK4frseIciJsbtKYbIqjwcJLZAow9fGmsn
        YQobFKZJW9qxoefzeIXEwN+BuZXtd1LTDnEyLLYV8KtVUIBa907h3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T02:13:57Z"
  mac: ENC[AES256_GCM,data:GpmH3OFN/4NZYdrTCEFDCmobFP9vamm1/P1uzmo/73uFpAD5EhsOTblCyMCnd4NlJ5DcSZ6K7ld2wfZLIx6QLST760v4NcIdGoJ9eAABN3ZiRqeoQMurcWP7RYvu/9KcDadsgo3BmHOK/8HadJYfAlszFLgTMYwdwEAqqQ54rJg=,iv:l2Qmbtaq3x9mS5/iZ6aPVj6c6GdwLZ/wrM2GGK7a3Lc=,tag:NmvdtDtnLot7cXwSho7ppQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
