# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:j3VACm3zNOiEGDgsW8ztI8PC9e/lPOYQw04EhQtuKqpYCnP1VJU33U6KUZuMOYb4WOA+uOxxbu7Q8QmvkdbZzzyL1blC2P635MbcmvJmf3L0QTkvX6F8EYP7hkWF0qA/eZDLv7ArVKhlXTiSif3gKmyFByi1BLMoZtPbZAYnjpvMCrGqjoV7iMDcS2a5uuYNQDkdsBJGVZcRAICxp+f81Ct0UJuvVRAyKl416g2+YnKQtpCaYePjY39TwK0tLrR94gPlM+rXEzbs8/hf+jYHUikGxqkDPUhf48zGw2hH5wTYvGX02ItKPLnpJTGE,iv:Fzl93fp+OaD3HoqrBkuM9ygvxEQMC5TXc19IahoT7HI=,tag:wSU7ILpLW95Y3PM4ICOsNA==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMlNmOCttb3R3MTgvVnRT
        Z3NlclFUT1ZBdXpvQVF5UkhOQjgzRVVmR1JrClltZTVwZ2Q5dXJ0bFlVNUc0ZENh
        Yk5QSW4zYnhDWVd2eVd1NllQcTduOTAKLS0tIEdJVEh4dEhTUUxTQ0Z0NE1UZ2J0
        MENac2t6MFFaQkNNV0t5S0lnbGdHenMKepswlSBF3kETSiswrZq3+3f1+ZITRybR
        O6Idl9Qg/j8099sNQQ0pZ8Q0HJ8bUGM/pfCTN8LJoqB9yAHnKrUXqw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T02:18:27Z"
  mac: ENC[AES256_GCM,data:i5MSvw2nUYoLtyRCjrVr+Lkkjyk5JFhV4lh3yKTEQySkbNiJc/RQkCsY378y9CrOZDEpQhqsiWuz3LIzKR/icZ+u+epkFnXH7OebNamI9J9WYxEmVevdvd8t8uNL4xFl/VevWM7KXtJxMTE9NBrRDviZQofYcbjTfY4x9Q+Ifz0=,iv:Q+7zh9ZpXXo/uHecSBI0i4VP7Hjn3AsN1MBkcHKlmIs=,tag:du2cZYpPG7LTjxVI2zwWag==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
