# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:jW9YtuGC6Zu/UuOsNBUV7ESlJa87LJwW6vmdSuj0b2Z71XfyxO3D1g==,iv:y3wJM3Wp1F+292GQLktP2mm5PStqwZ3GiUKEkuZXmhM=,tag:TuorHuMA2+dxx0kAYmmjEQ==,type:str]
  CF_ZONE_ID: ENC[AES256_GCM,data:GFbzg8sWMe+Sn6Gg5uCqdl2iMR7auqpJT0QJ1Wns18Y=,iv:FP51UUr0e4f7ZmLCC+MDKqEqBq+EjUCDBa2fKrRL9oU=,tag:g2f20oxgbTFJkx+sRhsHxA==,type:str]
  CF_API_TOKEN: ENC[AES256_GCM,data:SPgSQkclg428c0aOB4W3FE5g1lNeoegeVd/MqKFDvK5iAXLyOqawpw==,iv:qRwjk54Ogcl/yLGIF67hoWaxLhzblZ8CX1YH9GYOsJA=,tag:uU30N+Bhz3A5lZlttdTA2Q==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUGpIU0wzMVJ4K09sR28r
        aXFlNUVOTldERlJGamJZOTVvUG5STnF2VTBrCm11R3JRZ3NTYzFrQkdLMHc5d0VL
        VkpCbjFIUmtxQlJUMDNVM08xMmtyUEkKLS0tIDlONDhUQVdoVitvYi9ZQW92OEZj
        bld2eUlqZ1lPRkM4RnAvMmpWcXU0QzQKKfY2L7NJeP0jovPTvNr+Ti5O1C3BaUx7
        VS8UAZK8Xu0BmKIaed+zcnaoP5awaYzsy0sxnLtAF/ZMtJhuWr1pxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T15:32:56Z"
  mac: ENC[AES256_GCM,data:90EziN5IdbFc/qBdPUPgGZcJX8IGpiJJdidT3w+0aE9sC8d1YV2qunyyUJKll46R7R4AHJpFEuURW+dsYjxwpzs96SW4uyYdYX/7zoyAeVo6W4zYrrlqLlSlnyKb+N0RVwPBNKYb8QrC2FV+5VeV6PQ7hkcjQT0VsMl3uLQR440=,iv:YdlVmm7sl9YHA/TaQaWQLYPdRhElP92rYgyUO8B+neg=,tag:C3tloIR/CQ83SErHAVN0Bg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
