apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: aws-iam
  namespace: toolhive-system
spec:
  image: mcp/iam-mcp-server:latest
  transport: stdio
  permissionProfile:
    type: builtin
    name: network
  secrets:
    - name: mcp-server-secrets
      key: AWS_ACCESS_KEY_ID
      targetEnvName: AWS_ACCESS_KEY_ID
    - name: mcp-server-secrets
      key: AWS_SECRET_ACCESS_KEY
      targetEnvName: AWS_SECRET_ACCESS_KEY
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 256Mi
