apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: datadog
  namespace: toolhive-system
spec:
  image: ghcr.io/datadog/datadog-mcp
  transport: stdio
  permissionProfile:
    type: builtin
    name: network
  secrets:
    - name: mcp-server-secrets
      key: DATADOG_API_KEY
      targetEnvName: DATADOG_API_KEY
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 256Mi
