---
# yaml-language-server: $schema=https://raw.githubusercontent.com/StackLok/toolhive/main/deploy/crds/toolhive.stacklok.dev_mcpservers.yaml
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: magic
  namespace: toolhive-system
spec:
  image: acuvity/mcp-server-21st-dev-magic:latest
  transport: stdio
  permissionProfile:
    type: builtin
    name: none
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
