apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: pagerduty-mcp
  namespace: toolhive-system
spec:
  image: ghcr.io/pagerduty/pagerduty-mcp
  transport: stdio
  permissionProfile:
    type: builtin
    name: network
  secrets:
    - name: mcp-server-secrets
      key: PAGERDUTY_API_TOKEN
      targetEnvName: PAGERDUTY_API_TOKEN
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 256Mi
