apiVersion: v1
kind: Secret
metadata:
  name: mcp-server-secrets
  namespace: toolhive-system
stringData:
  #ENC[AES256_GCM,data:kBC3/au5S/jmL3Q5iaI=,iv:wSScdxRBiydorQ42/zgZLAc2grDLUOdwfrhMQQ0wnFM=,tag:v6LYLnEvWLxSm4cE107dCg==,type:comment]
  GITHUB_PERSONAL_ACCESS_TOKEN: ENC[AES256_GCM,data:GVRZ3ugtyxYfI1uDDHHdggWkg0dj7LtfqY7ZIXQnLa1JOEc90/s+Uw==,iv:Ae278Z/jiBZAue/VdARShFKg6MSjcDbWTXvkbAc5kh8=,tag:a/pIkqjCgydB5bmIghpWYw==,type:str]
  CONTEXT7_API_KEY: ENC[AES256_GCM,data:XEZVfgG/EHNBtcbgH4HOQDsqeIpiakjQ5zM69tk9zMwhgPlxwbN+Dg==,iv:sGQ5Boo6J4TuIG4/rBJJYlYdWKa2isM+/wxyG3VL/X8=,tag:NPO+DNvF37OM+OMSRHAizg==,type:str]
  #ENC[AES256_GCM,data:tkfbpQBumVsZ4NYBJOM12Is+ODJG9l0qfk/k48Yq,iv:RE2399wx6nSH49EwCU3GTlS1QbO5v1PUcKyvLu8ox9I=,tag:Gmw5IF1NzQNIPV0Vq84mEg==,type:comment]
  PAGERDUTY_API_TOKEN: ENC[AES256_GCM,data:IPmhOCXbuIFl/BQbJvT2L97FlHC9Pks8V0I3UdXZJb5/WRsz2sYIm7ONRFujaeQ=,iv:nNkoyzrWDllyoHFEphvJvf3T7zC/xUiKXmtD9TKrxR8=,tag:x+i8ZOJ7hszkCeMQsQVj+w==,type:str]
  DATADOG_API_KEY: ENC[AES256_GCM,data:k8a4oU2Kg1BWr+kLndgT+fT8qzE0ncp5naDm0p6PYJzoRgM4GqngzXmIyw==,iv:IaupPwdAb6GpsaMvgulVsNVqs3yC4nacpCa7Li7rGd0=,tag:rPG5OS5s8gj2dE20kwD64Q==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:87XcssbmSPiEnPvuUz4hhnOvs7NUXvmPTlpt4RPn4xdLP7Vw5O82Xrgk9qkgO2lb2g==,iv:TfHWcTeNPvmCquOfevadbpD6pzhIh4sk90wxDUdr5d8=,tag:utzg+9S8CRBmVmFOWQhotA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:cEXnXWvlIuc8OOIXRX949dOlXI/Te5MybwKNO6iWuwbpjbYQR3wg5W3UCrtuQc630xfsf0g=,iv:Rj8ret7oiwivinYNajMQwkzSv84FAg0ueNUx/xt3fXM=,tag:1vns+6oc5cfkHOr3UzVAZw==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBreUFyRUU1ODJDUnBrZU5P
        d2Q5dDdjbzdxenFOUi96M3JtOG9aclRpcVdJCm9Zb1E1M0txbGtJK2VoRE02SG9O
        SXBxWnpvUTFZTTY2SHFnc1IrQ29BQjAKLS0tIEpVVGZxdVBVUkdJYmtIelR3ZWRX
        NkNLVVkyay9oRnZuV1AzdGZoNHBsNVEKNo0eJljk3mA/L14Q9q8x1/LZ4OeTMqCl
        v7Us4O4YVXk1HeIR8Vk7GoKE6E/NX8ml58n6YWWrt7wg3n48GRwZ+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-04T02:37:34Z"
  mac: ENC[AES256_GCM,data:QE/xi0IUNZ46vLmslGfXm5kbvE/wkKdk92t+pMsEUoMMsytY+72fvxV0GRP7L35vcaR81VYaDQiiOq/wMtSuNTSyBHvioi/fu+zoGK5YYFGf+/27OQVzI1SS+VgM6hUI8azTJNlWXPXhbNa8wvo7woW2P6/VFd90fIhSRAQTjIY=,iv:3+SufWBELAfQye3BBXb01WXFXZRI7CKHS1lDumlFus0=,tag:VzR2rtGy/na6XWSJpzVuuQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
