apiVersion: v1
kind: Secret
metadata:
  name: mcp-server-secrets
  namespace: toolhive-system
stringData:
  GITHUB_PERSONAL_ACCESS_TOKEN: ENC[AES256_GCM,data:tp587jExSC136EJLhks1cKJNrVm1DDKm6Byb1zcsbMboO9GgpUT/vg==,iv:1DMa1gTissLJAAAox9qF/4tOE2eeZyCYP6OW5BcvB9w=,tag:RR4xWjJoMdzLite7pVNBXw==,type:str]
  CONTEXT7_API_KEY: ENC[AES256_GCM,data:ry9KprxaboK+J2n3C/TIyjKfWdbHnlH92JFfewTUL627FSqvNZtx5g==,iv:gRAm/dEg8sX2AGtJCA7VB5ddlsKgiWT5ClYMxD/yWlQ=,tag:w6Hq1Y3z5JrBFifY3wOpwQ==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTElLNUdIa3dHdUowUW81
        NlFPNXFpd1BMSmJFZU1FOXh2cXAwYXN3YlJrClBtcEF3QnVKTlpaN2lLWXRnVEJn
        UFNVQ01zbjg1VHFKMzJPK3VpS3dZUzAKLS0tIEs3UW90eGtvL0tyOHRGY3FGV3di
        cmROWTArbVl2SDhYNWxJMGtmT2RDVlUKV6QI9aLY+mtUuHTPoFIfgohs9ZHiQPW6
        LwCtKZdxMizgMdhIMrzfYybr8zKfaazrd3Mq1b5Y2wdJyf/zSNp0qg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-04T00:50:06Z"
  mac: ENC[AES256_GCM,data:9sDfE6RKSdbMg9Y7L/Zzp2eVPMpTOHBOO0ZcCo0dJJdXZjZeoqGXxdMwbj4SgCfnWarx50RHCX8lNTomKF+8rBZzlPRpTqx23P6O+uG1faqzg73xosOIh+8I46B6DUGl3NDDjO+Mu6Me2LCr2r6xG9rjVCNwpFG44LPMvBewWr0=,iv:/AoxFEftfCmNbtvwb/46cpHL9VZzLUWqXstrYWmRiQU=,tag:mZapl8zp9hPPzw5i8vL2CQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
