apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: sequential-thinking
  namespace: toolhive-system
spec:
  image: mcp/sequentialthinking:latest
  transport: stdio
  permissionProfile:
    type: builtin
    name: none
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 256Mi
