# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: velero-s3-secret
  namespace: velero
type: Opaque
stringData:
  cloud: ENC[AES256_GCM,data:BTQjydSMBU33lefw440Gb4S6kzzRsjs2SxFIBPiCv80Ozr3TM37YAg8vADfsDsVTWDInsBfm5aW62M2ljVoqK4TXXcMJ5spM6EeQUuSL/T7y,iv:kZ7BcylQ8nAC0XKAEBYUeWzdXi1Q6yI8GFe2rT9uC94=,tag:x11ODIA0cxWZ4vXCwDv9nQ==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YUtMMVlrQzVwWUc5QUFr
        Slp0Mi9na2hqU3JpbXMzK0VnZUl3OFI4ZVQ0CnJmTmtTRWdxVHAyY0Q3KysvVStU
        T1hBbDZoUDIzaC96RXhEQzc3ZCtsQkEKLS0tIEpsc3FrazU5ZGQyT1N0RjVuM0tE
        RnFOR2c4c2Z2bVF5YnlySUdWN3hoOW8KyljFB5DWr670/SXkD4v0VvfU3843KGe9
        37DGE2kO6EFZQqyWIJ2KEzRQIx8D4U3e+jYFo3Ii8JpEOFRkpHi6Tg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-11T13:28:57Z"
  mac: ENC[AES256_GCM,data:gdM7YBYlJ3tfEOdKmM9oEliKxg4AkTQ7IB5scDAK12Li35O7OXw6K+lgrN+YOp0e70HsC9CI7arFMBNoXvakV+Zloft/Q6M1/vyJMAZ241C36guoXLzno/JRwdENK6hvOCFyXPW3trJ0g+WJOz21ifDauMN+sAb3jJLFezydQ3o=,iv:4sjYDz7y71+EvW2Dy2idTiiM/SIvGvM7+zqiFpW2t/Q=,tag:C/X8Vf/0JH5mmeh1ADStMg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
