# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: velero-s3-secret
  namespace: velero
type: Opaque
stringData:
  cloud: ENC[AES256_GCM,data:GrSyN+fyiqOxU1+xMDATFbUivOc75Uh4CdmGYfq80m4pHf/5HeWKkWW2vUcvzXb/GG14TmL5errB4i+V2NrZTqyBbA==,iv:fUokrUnQCwM+FPTnrKFswcSdNUuFNhzWIAGTPPtGzTI=,tag:KcweTGvsx0OOPU8383MpUg==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacVg3bHdVSFpITWJBemJo
        U0ZRUy9PTVMrMVNhUDBEbmp2cloySmNVcjFRClRvQTN2SmIzeG5jQjJFTFhWWGVn
        dFlJK0YyOElXSEhPOHB6V3k0SXc1aWsKLS0tIGUxcmt4bDY4VWIvZDhIeHpMR0Zo
        YnFRc1N5WW1lR095aS9TNlRvSGpsK0EKtE8xGcX9HWUEkAAglK1tB1qMTO7HxaIZ
        8ovfC8c+VKZwunGOpmTNn/+EiZVWoc3WaxAefz7AwqMX0PnaZMCDrw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-22T14:49:01Z"
  mac: ENC[AES256_GCM,data:Fo/h9nBuDMT7nWEP8fFku6hdfjSB++xFNlv++qG5U3V4AF/oJVYGcFg60cWh1Utpfvd4kgll2kLx+FEbjL4sjAuNUI6g9pyG57MkBbPFXaf6UoTCpJqFDctDvHzU6OxD9MNTTjEgPIX5o1bZEwtJ8DSlt93YzMK2us8C55tPeEU=,iv:QyruXop5zhP13jXdzQLRkAwmhEntLKtFzWTJc/n7IgY=,tag:lTVyt5/HqWBgxTybSAo9Tw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
