{
    "data": "ENC[AES256_GCM,data:lJOVKGQtbC8Lmxoxf70peRvSTKgzOIR8DkiTcZ79u/GDVVFHWQwpSYEXqJzUVhsi2Kh0+HIIeSAC+Os2Yn22JnDj06UNnJturfMceHGGrw04IO2oMCoMBjXw6QJUc+ragQgiD0njjFw2cM6mIQmUcqZggfACzeewL9N9tdMd35sbcU4PV6KiaMi7JuK+nCo8e4x9pckt5ce5M+QLJQT250VX9BlcjEsOnWukNmt/GBG0zjJmxz/hCAdAqhhUhhleNCr9FN4HHvj7FBWlzfQQ1ODGaNuDcDHZY59d877HNZjOJwq1IG0H6ZWKSnsOPqx4UbKivTLIdQ72vhfK8SymaagPkAoU6SHY8lisT4rUZl2FTfoBybNdiCiEG0Oepy+tpK6BzFoS3qSLGLztSEKjalTvb0SzFiTjLxXL4ifdGOd9sYiXja2Swq7Je6Md3M/4iGOC51uHTi6rNam4CnUtQy2tlIkCIlQJJ9XRfZvhtMmK+oePVTTiRpengTLlGWpwudXIDDw+oQ==,iv:SVIuFVlGhR7720aIGu6xZm/r+3IQawFWde2ivvpLkGs=,tag:wyxgehm5PpeuLTC/7oCOgQ==,type:str]",
    "sops": {
        "age": [
            {
                "recipient": "age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n",
                "enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqakEyVTc0bUVOcUVEczVU\ncjNiMjFaSnZaMWFkbEd5MHRsOFlPMGRINkhzCnB3S2VyVWllZCtzWllXQWNyYW90\nSjRqcVZHdnlPK2tPYXovMG8zeG94NncKLS0tIFA2eGgwekRPZmpFOWdmTHdUcDFR\ndzhNeUhVdEM4WG1JSm1TbHp5bTZPQTAKkIl226gX/Hb3XQwK8veatvOXEz/Nphdm\nGtWtATuETb0owAc/fHVtRSnAwor6GvVp9MvrlD8xgeEr9mh9NgBhGQ==\n-----END AGE ENCRYPTED FILE-----\n"
            }
        ],
        "lastmodified": "2025-11-11T13:18:14Z",
        "mac": "ENC[AES256_GCM,data:gDiALnivBYUiCzz4FhDXxPpIZ+dKSTrb7oLOnxcr08fXe4M2rGR1BzQSzW/K5FWVGi4GcLlRufEQWjcExbOn81X1HqvP8xj6Ah8n3jnSkh5o2c0KWbJuKWJ6FG96lUh0UFPD8p95V8Umd5sTQkHGQ59vl0ZUevu6TtMDaIj7sLc=,iv:fOB2E1TyP969/m4aIfaz5QLD4At8gaXDWOk9GIDij9I=,tag:3mVBrdTp+pA+Si4Fcqk44Q==,type:str]",
        "version": "3.11.0"
    }
}
