# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: velero-s3-secret
  namespace: velero
type: Opaque
stringData:
  S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:dmZJxthhS8iP3/s2kQ==,iv:2TZ1gH0kZZZxFWvV9lrh28ZlPHiQp+1MnpAXrEEYXl0=,tag:TbZl8JuyHW1rLCkyRGP8Xg==,type:str]
  S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:lGWwYboSC2meD6W+ExNd6g==,iv:wtNVi5f/lN9QMAGMJbNI8SD+KwHknNvvLIDOrok5IIY=,tag:4JLQjaKXQsgmkrVip9rT0w==,type:str]
  S3_ENDPOINT: ENC[AES256_GCM,data:C/z2MgEqbW6y3Arm/Ipstlwk,iv:qyHJAf58QDNu42AguCY1qqJF0rGopKrID4AjxINAcGM=,tag:uV6+wFDSKKHR2sEgsh9uBA==,type:str]
  S3_BUCKET: ENC[AES256_GCM,data:MlMZOusr,iv:S5PQ86BB/NA1I/IFxLTrIhmy5T0OPp91KmLVz58MO5U=,tag:YGObrlmsr04KRCSdM4j5sw==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0K1NDcElza1IzRHVoVHVQ
        ZFRMbnJaRXg5aDE1cUExa0xOQ1pmdENrdmlBCkF6QkU0Tk8yTnU3Nk5SVmp3VXR4
        UkxZbnZKVXZnaFJ3TXdYcG0zZ3RBbm8KLS0tIHM2UkRFMlpSeTlXWHdKczhCSTh6
        L3cvQldPOHd3ODdHVDZqeGdzenNza1UKjHBs0dabnhst3a1NR57/XuaXby6sZ8Bl
        H/dMD1TKeJs1/8Z9x5n9KOM2ZT030aZAJ8jvURw/faOHswcxmmDQtQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-11T01:34:33Z"
  mac: ENC[AES256_GCM,data:JYHZ3PrfmvBGde5gTBKFYZZsh8JOlUPoxVX1LRy5qQPsj9n1S2p2tCm/qbA3xg8mXDQnTefavZvvbKEWIhopeR/3p6pSUbpTvdFXfDmPX85QWbZ5Ybyt+ny5nSnEjW7z6TW27m82UKoC7jv3SW5Nc8frdJE/U2S8MdBKmy3BElc=,iv:aubGYL/1bpQdbHRYFplPG7icL8l2x4HC3tgLUhY5RA8=,tag:TD+2qaHVu10PeoHTzJjaAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
