apiVersion: v1
kind: Secret
metadata:
  name: memos-secrets
stringData:
  MEMOS_DRIVER: ENC[AES256_GCM,data:t73ijM+1qwY=,iv:79uck4/4MQmDnl8Dfk7tglBgl7ZgcpyT01/gv5r5vLM=,tag:oOqWKGk7sHUtNgSHs8uN5g==,type:str]
  MEMOS_DSN: ENC[AES256_GCM,data:ic8/ittP6ptXIJJn7tQQjtDYAiSWW4AHoRCwSS8MNs3ZwPKxnwT+7sxNdw58zcvjTUCPefFYdjwTayuNV4T73Wg3eWQJSX6k1HxNGh60bGdLb9b1JMouqv1bH2fubYqkTgq1QdShooPsL0nFIf8a7WcCMBL7vg==,iv:ATTOD66Z1gIAac3W75pWai2C8vakX5DK4LKt6ZNdB2Q=,tag:xbdw0tMgpBSNc+kZUHxjqw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:um9buZc=,iv:vY/eHAM1q25pSPfqrUcFJplH+ivxDtRy1tBr9SYO+4M=,tag:zXu6ju/Ob7E4HZKAJQheAg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:HMUgVrOXL4ZrnqxFOMd22BQ/rt097pnsk2D2ARm0bOMTE+9cGv2ZNfs=,iv:tCwRcvq+Orn2O1FhT/d6J5wr9KfVly4e6XTYLQjVY8A=,tag:ub19FnYs0QNM8OqCD/uzWA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:nHzPTys=,iv:Fbb+Z1/KZ79IdVixWsQycsAFPgUqup3Aw3/4wZM4+zc=,tag:CBweWFyCt/s8+nxxIr/7ug==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:l0DRSuQhaai2Os2RLklWqeL/G3NxI7VZw+ls+S50t96szgQxjvHMi/oR2hTcWMzSHU2PrTiGEWvIHyrZK8PEIQ==,iv:jXo8ZthPClrTf7bRpLy/dutBTGzMj/qnlgR6hEqDALA=,tag:7iRS4qBrI4CWn8gWAFaoNA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:DEenNKwMfgyUhWHyHaQ=,iv:x31er5qR6qI50MiAb46zLMhdDomGxDCEmH7EOvC5IBA=,tag:7x/jC5DMFAGsUkzUJjNWLA==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:8xvilQtSxdg=,iv:a3TmDCsPBUXvbcRIsEGw6XhaNE3tLzLr7zOFe6qhuyE=,tag:yqEONlVVaZX2zEIQ3illoA==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VzNzYUlkMUIwWkRCbnpZ
        Y2ZlZVM3WXdPZkNtSjZJSmN2Z3lBS3drT21JCkJ5YjFUbGxLRXJiaFJNNGVmRGFs
        VExBcnk5ZTZEQUxSQVhxekxXck5kQ2cKLS0tIFNLRHVhMjR2Q3hOUE5aOWE5L1dE
        S21MbGc0U2R0NXpvRHJ4S3V5NUtsN28KTQCbd4o0BryYBii/BzH3sZjUFh/LlRoh
        0OcvNwk0K1PoG2PHA2Qds92/RT4Gpy+ioaE1/ColZMR5VtyODNqmhg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-13T14:04:02Z"
  mac: ENC[AES256_GCM,data:6jG/UwyrzzZkrXA9fj8SjQ3kTtuMFbQipuHFfkIu3Ww+9vkwxrlQWcSvwLqQt0KNMVayEmkNnMGW4KfppNh3In9M7dpDnC9UTiQXhHHWTnPFxeLmu730ih2s18uJcg7RPi87h/Np/ZSGCDKleamR3UUk7dkBLOOsOkAHUDj+bTI=,iv:vGo1buMYipZEWfr6hzCKPjy8xkfwIbRSSJjJpEU+MQM=,tag:tygYEUAKtmJY0TO3BuR5mg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
