apiVersion: v1
kind: Secret
metadata:
  name: memos-secrets
stringData:
  MEMOS_DRIVER: ENC[AES256_GCM,data:PZVOXyAnHwc=,iv:ZrgN6GL3GItzCSNCbKotdf2gp0CL2bsoPWOeuMCtAGk=,tag:NnFuLCnP6Sub40O/j52Auw==,type:str]
  MEMOS_DSN: ENC[AES256_GCM,data:+T74ismBpWcbo11iI2w/qRB8+JOX4tvj4UyQliYFoLqWXZCkUD3jIGmEKbQgZMQiEHTWNqEw+Hl3olU/8LvJi6oBdPJJS10XaYCUxBxYAAFp7FS+pbQmbek9JcfI0OiaAcSOOy0ZksJphurd41FvbrlxXeIYcw==,iv:+3KxGQtEToxQCWws5vwN4T/kPhVNUxNUeP9fYRiA+fw=,tag:8Z5O571rLl+vg2o0Do+W9Q==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:6J7TWMc=,iv:gCVd/xC790b8SVv+ROw/hT+eJm1ik7OlxNG19p5WvFU=,tag:dTURnX/Q9ogzmKbvyd2giw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:92QRMiEUMc7IFenQDcMKUlP38NxZQOrPhIVY720Sa9CChPklmRqunDM=,iv:9kAIHSxHfTdoLpmOGRIQXqH70Yg117cssTDXU4Le0so=,tag:/AfQEBnheZ02DQQ3gFH8sg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:FCq3V6w=,iv:6gdKDUHclmoMUpGoCCJAjizLEMCv1S2FX2+60QSrJMg=,tag:1MmcvRXUfl/sStYlOE20fw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:6U1bcV2tHahQecD7vYG5VWNrjp1t6evYwltZAH/uY/9Eul+nuC8vMEgLaMAJjmuKIyBWw4SrXAEw32PooFzZ3Q==,iv:Al/SJqwKHyTzoaK6o/dQs7U7mqMLFIg9ib7+DJlJSAw=,tag:bAJSMl14ejReh+VUayJk7A==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:kPHDtp3lBT3YwlFmAFk=,iv:QBhHus1keBIjoC91O7F121dpd8VBulLbggIpv1WPaxk=,tag:3dRxRSdH6mIq/Sfu/vyJ4w==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:qQozXrWCS7g=,iv:kN8XeJOWUBWY0OlPk1F/z4bqEe4lcAmA8E+Lq7nTP0k=,tag:9QtJo+LA9YKFf7tFs53CkQ==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWHI4TG5XTEl6TTY1djZR
        WXA5cUV6KzVwYVJGSWdObVZNTmJTVFhtOWlFCkluUEVzbk82ZjdUTG12dGhCeUE0
        UGg4ajRKaHkrMkR0Zk16OE1EUzNuS2cKLS0tIDlFSmxScGZyYnlHVGxOV1Rtd2NG
        VlhBekpTWFl4UzhmeVVUK1VYeUtsVkkKjkPLKrUGD9HSBJlpSv7PLiLcaf2k7MAr
        EbQ9T7Jbc0NTFmCqRmV3gV3bcWDdd8fuudC5PQsrXZ/BQdLA5xtKsQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-13T14:12:04Z"
  mac: ENC[AES256_GCM,data:6ZDAjUIlVSC0LUWwFVkg+XmNpQZY+fjqCN5PO4gK1GARX0mIuEsaapZyCxr4VbsKmCQGwulaXQkclXiclbsUA+FhTYx6yDUNCCWGH+r1Ozn29o0jOZWYKg97sGZYKL6RvtowzfIzf1aufrFopB28QdET7eKbLoez+66pN1OHfF0=,iv:DeqGBB8qw7DwfdJVNWcuSzmhGt6LcUtPJcLgaaKqaa0=,tag:v/H2stEmdV3BNb++QhMs5w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
