apiVersion: v1
kind: Secret
metadata:
  name: authelia-secrets
  namespace: security
type: Opaque
stringData:
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:SpW+1GpaaAxchdfTHId0J8ct2hVEJTtz8Irp9HFdnxUxMfDIJtnTpWY2YH+otvm5mNiwnMBmcwzQw+12yj1Pzw==,iv:WsKFOaDdVoxf8UXYH6wcKTFymy1tj7V3pdadgy+MyOA=,tag:3isvWQ8rNrL89yVUXiZfvQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:tTuWLcEm7TM=,iv:EU60+nrdsGheKi/0ufUw4ysrMafrkfFnR0PUYDsTGcM=,tag:mcPbNBkrzThWNjcAAVi6TQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:xemkA0xvDsu5GCBmc5SzFesL/Nv9L5gVSczgAgUuI7YY0teYazak3ds=,iv:vCxzy4iS1JtUHXF/jmk0XmgiXvl6AEEyrFF1iPmX6hk=,tag:syYWfztkz9K6rFquXm1SoQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:7aBCVva/wU8=,iv:4G5c2aJxQchmOROgNRNwuF3en6zk/SUVP1+iqpa/FwA=,tag:M97EKudyE3P2ZsXcEBeFeQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:CqlYGzOox58utJZq2mg=,iv:ZheZUCPpHB0sJHBaj3FC+b8iDEz3EOhjo0Kb1tv9wnU=,tag:rwEvBdnUw3nqThkMExhjBw==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:MYasfcHU1Dg=,iv:Ewqe0lm2tSqGMC8DWVCUE1v2X07iBCUjmIYmuRYm5/4=,tag:a7basR2xrXl8b1Qebx3GPQ==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:G0FIMiyNoipPiDryWCaO5Q==,iv:LcSzs/CzecUdoo4t16Y+ZHdt6u05w+OzmaejBdKkl/g=,tag:Mf6Bbg7gklXvivTeFOyVbg==,type:str]
  IDENTITY_VERIFICATION_JWT_HMAC_KEY: ENC[AES256_GCM,data:+7TXipBQgDprd9WwRCNLmj1ZTLO/9U9toU8y9aaFE6lslASGQ3tOTsoeS+OYCgAKLbIveLnNks5E+gn476RRJkTa48Z+oC4KPHaVA/RAHM0znzGmo5oH64zE5255ZOhc+XB6uE2IhnWTxVPwonXNt+ysC2pWSygWt2JlJKw4Yl8=,iv:Oq9K94D4C6hTvGzCT5IC/UxCSwP5rvN0hUGmyaf5FN4=,tag:IIG/n7R3/XjJ5cc4Q/t93w==,type:str]
  SESSION_ENCRYPTION_KEY: ENC[AES256_GCM,data:GpwusvKJ7fs4nILTrs2rgJyAGMzzs2lDnuByO6BI0kdChQPwpFiEh9VQyY1m/Cywydez8s6FVfDoyTuC/aUpEM7vWQlyP1aE7P1z/tcdE1NaiF0A2afIXS8XNkYnMsKfSY0oGXWn8Q+kzsaCo1fldbzGxWVVDXhXjIBwzlzP4X8=,iv:YCJlwqv7t06XV/jFRFe0UVwD0L2h+aXo0TKnrzk73w0=,tag:aCJL3o5A4XkidlVQzAsadA==,type:str]
  STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:guQAoN7AytOmF2604q8UWRSk51gs7sdinJjS4jsmvylSXm2ynQDwiUAO46NvQ8bYACIy9ISHI7AvI0kVTPtf4Bi5Q5CxnOVFbs8CQeQ8sMMRQSUuw3P7oiDnCQJL5P6koFfdCimfrPPZ5YW0vcU6DIjAJdHaaHxgI9utbzoKD5o=,iv:bdSwuueQ5i5wvKJx875CCwLE8NH1B4Ln+y2wu7lICjA=,tag:1isEdZKNdsJyxRwhgaCVIw==,type:str]
  OIDC_HMAC_SECRET: ENC[AES256_GCM,data:YZMqjy1ko4wydmATfWik/aOUyZKh81elNL44NX2c/7/y7haj8EmX9D3j25P5PgIosPAPaYfdzycLwHRmwXNHXrYMT5vQfw0nkSqmkOn7Dn6pbIAOxvLvl6OCA8w0w7nAJMbQcv78xCBz/nHhy+JnfgGDmw89Irw8IDUBPikdPjA=,iv:aP5UdVVlft1tFRXB7gkfFIyA2yGzMAaFZUqbB9ELliU=,tag:qtpsRyQoJY7NQG5Tyt/sPQ==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eGN6SHpJclpaZFZjYjND
        VUVIWnVSRVM0clRoamhuZm9pUUh6a0dKRVZ3CjhyQTE4aUROSkk4Y3Bka3F5QTRF
        VjIrdlJHeWlqOGpGVktSWkhkVjk3ZkkKLS0tIHFNSHlZcm45bzlzSXlmY1FQQW1t
        L3hFeEJPWlJnSzl0SlVRR3BNUWlFenMK36mJ5pnmah5bqyp0DNkl49LL/FFXoAWf
        0c+0ba3pVx3s5WT4Xv8OHereeou498kKrGhIqg9txga/KUrrAsI8AA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-16T16:24:34Z"
  mac: ENC[AES256_GCM,data:eq8sRuOOVsV7Y0G6RJ3iXCGj7pr6xvQVNesgUh+hXhu0ON/gYHa65+CLej9/xDpAtH0de+zjpUUzD0bKBCdu4crLDB1RANja0LZEZVmz1cgnuklbboLkY44JM3fT8EIjqs6aJ1gWTHoRXxhxroX/5KLnhGMTAo6zrWk4rcqw6K8=,iv:IxDO07dha+A3BQSLC9XPLOoU3IX8/I/5REyc7cezNVU=,tag:6rJXdBnpwU7m/hjFV4x+Pg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
