apiVersion: v1
kind: Secret
metadata:
  name: authelia-secrets
  namespace: security
type: Opaque
stringData:
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Kgt1alfeWpXjyzpwZPCpcQTaMG1lcJsqStBy52ziH0x1WGG4t/AvsQF83LqYmns2br1I/t5ag8TU2+poc/6aug==,iv:j2dUE0cidbzvKUG9npnOYzKchEH3irQW5/Evdehqyu8=,tag:7/Ffin+rUjZcGFawSqFQoA==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:o5YAISJZEPg=,iv:UY0S+MUEivK70LOT37evVl87NVo95o7FtniOcTFTa7o=,tag:RVhK81Yn4y2V1QVkpqh7Dw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:lSVaHYzyPz/VK+WhouD4Pg6S8int6Au9VNEOJyd8ggzUjgwG9S4ULS0=,iv:Flwe/vrrw2FIZmlcziKhRRQT23ZCd7Fk37nSUnOUJyU=,tag:QfSBv0CvUplSOoM/JLfB4w==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:wTO/EAeJ/zU=,iv:jVlyGmwKKwro7gNQKsOPmsRSVek/LJ7xTy0oNy/RItU=,tag:ByYniPBQkA+mIs4cJYUMlg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:ip1P8GbCNMfDkgzbWMY=,iv:zh4voUBW76WCP5GMBAxkmDBf0wUHe9rHe9ZWe9PHnJ4=,tag:DUjfxS4GjQq+swUM+SZP/Q==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:2hQUgzJ8xqk=,iv:5DsR6DEftKyv0QHnVwaLkomewo0sZX7Rn268cyucEUE=,tag:N3huRo97Driyc5UI2rGJBA==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:p/F4/ajT72PFKzs0DKOUxw==,iv:XRnR+9FqHGFkE1VMAXPOjvPpXoJkMdEyerB9dpAh4Bw=,tag:QcVVCQYO9WqwkF9YlOgLiQ==,type:str]
  IDENTITY_VERIFICATION_JWT_HMAC_KEY: ENC[AES256_GCM,data:WcxHvuFSarOxp0PV8WVIpA9hfIolY/TE9liS3olT5+VMF7lpNjsNaELyXW4eXxQuUyhIw3b4MFN5HVU5Zanmj5EQLzgwXrRIzNBezID++cU70ZvoSqmni6ypF4+95v2l1vz4as499CsqSBfLLPrkkv9yNVcAa3undZCS+auW1Yo=,iv:Y6DcTvtfq0m0i63kgVybyX8Hktt3WcSRmDGmJJRjO5w=,tag:iRHQ9mUL0AxC38epp8a5hQ==,type:str]
  SESSION_ENCRYPTION_KEY: ENC[AES256_GCM,data:oM5+JQoffW6WAig2R/pR6RqPtMuY4jTADJ8wABkSuW4A4r+NeQpCZccRIVE6TowqWhCc3IgUlv1FF+mKsAIym3539btLw+EyvJTU0YMXUIVIsRL5PJqIOCY0CbeTPuCMEHiPsBlYyw6gdAaam4tAE+QglE+xcCqz9VVu3G62KaA=,iv:ClpglrEpUFfdv+JjhAPAQzceIuYzZ2oz/tioCDokVBE=,tag:ti1ViBSRpCpVObr5NC0XKg==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRk9FTjJxVkJSWjdscC9r
        L0YwM25FUmNmU1RibHlXWEZMMnlCM1BmT1N3CjZrWWI4K1dNSzU4NStwSkd2M2pw
        b0FHR1U2d0hVdHZzb1RFcGdXK0FkclUKLS0tIDkyL3ByU2Ftb3V0dlMvL1laNTJk
        RUh6Z1pydXFjdGdPS3N5eGlmdXpscFEKGBWNqmJEPuGYC1GYqfa+gErzrpZwdbLf
        sRYGQVLBLO/X6cFMkIgaYm6+m6KH3i7i1Wj6no+Usl3YXoigrcqWLA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-16T16:08:57Z"
  mac: ENC[AES256_GCM,data:rVUzqkHuAFluUaQ7jlLRgUi174fZx4SVaTLkCOjc5RkLBUqRrf7AA4FxLMG+86l35phSG3/K2audaIHwqNwsYlY/oQSqiKXng3Qyrt8lTJnWf8O5EIdAChLwF7pP6yWq9Dt2443JcjksXTuY7my0K6muj08pizL+rmiXGpzOaf0=,iv:xESLrjEKvyHaGx8Zp5Vyy+E6URcr5VarukYPUuUDRVg=,tag:uI3UWIphg8bE2Q4/P4lDag==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
