apiVersion: v1
kind: Secret
metadata:
  name: authelia-secrets
  namespace: security
type: Opaque
stringData:
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:kJTBKO3gxoJ9edi7XhdLrPrL2FmQ7miWeHRxxUq2iVwPa0cSzF12RQ7nZxvLEP2gBQ6EOcmgYm0CwfO/F5SYaw==,iv:oiLen1wFk/l6G2eNE6J0Neocwo8yAozhDkEEQACzlcs=,tag:yyP/BkVF3Dw6msqzvm9OCg==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ksw5sXCmsLQ=,iv:bZoEq+tZYOxIbhzGp15KOX3h6iNa9eSyR4X0wK81xyY=,tag:9Jgp+f6AjFewIR5GJzBmhg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:4sEUq1U7mGbmo6PX4kjh60/nm/ZHck672m61lGBm2Q0wsycZdFzrFds=,iv:DZj/hIcIp/TLoio4YRbOjfeXFPl1pRX8D0EL2lVt8q0=,tag:HfbNBfoSy0uvS+SHMDy3HQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:N72cAlIbqJs=,iv:6z9oDx2SVi5Z3SOwvxjm00rjz591CPZhAHYqsfqQxcU=,tag:FkYGjyLKZSIPVtgmV/kzzA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:a+AJJv8ogD0hpb/uCC0=,iv:okcXMCYN10KryqAR4HGWByzArM0pg+rJf9TxtNKW+fA=,tag:HH1VDnlVQVmjWuhlqCus2w==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:c5XYdwTmqto=,iv:JcgecgCTvcSeatps5Men37gCPFIUSs4lXzJBtoujsqw=,tag:VadRKNWfgG4vimKNBr7pqw==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:uWW/C7SbJ9feHtZCliqoew==,iv:/nW/FULEwPVDItqPug3oYT7iRWTq5YWmR06S51VXGU8=,tag:iEl3+uU5qakw/no4GgUsoA==,type:str]
  IDENTITY_VERIFICATION_JWT_HMAC_KEY: ENC[AES256_GCM,data:Ja+WUMkOh7lbp5AntDP/CeQHzFbrGC2rt/aedPnnjDICIEbMnQWs4d2pUi8IGDzptPvJB8vhJz7BB9XexhwXn9OdSgX28i7mOEPMIGTsTLFvIVPtshG35feUwbjyR55QGxUfUabZJmdw4wjC+BxLFGSwid6s8fddoUFcAWdLSmw=,iv:M7VZgt+hUo4YBbfsFh1CEuYBOkr9YEFFpt0Waj5bSuM=,tag:ebpLz1X2cnC4VKlifyqLJw==,type:str]
  SESSION_ENCRYPTION_KEY: ENC[AES256_GCM,data:mA8/15xY8GKCFkdkQljUwKXWuok5umYn7Ql0smHebVfn8UMZe8I8ZfJF6g3LXXOnfUHBNAyhYqbIkYoVi4ouqOw4iRA39xxdDJX6aD1x+QkZhvU7e4b0Vjdp+EoqXJTIWgvuPtZwxbmO5Opsp1cHAarq5SQgDPyFcgxXOwlcIvk=,iv:9ImFWJHg+nVOu/CIz2liwfjWitvSf4jdVEczLZidHSA=,tag:XrHT7YpH7nBaxO6PjgNJfg==,type:str]
  STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:1KU06jgZzhR0shFWBP2w9Tv5KIktFgbC5uRu6AhaXPsWedzWJOYYAPe6awC2qvHDoJoAGwhp4WJcaQU/q1iENjyMnHEG0EkqA/QooGC/qQfhi3aJtAGdprncX5zH594JLLbnatoLMQ7jDTX86ykKY4wLXSd+VFEkysUAqvJQLjY=,iv:Qw3rjG9CX53xs+iwF3PcpEmctTai8KqyVgjUR5e3Rlw=,tag:HWYvdbOB0QhhlCQMGHiT6w==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXT2lpVERnb3NPWjZNVzJ0
        V2xzMnR4cHdrb0ZOU284QjMwNk01THFGaWdJCnhtRVY3VURwY04zWVJvcng4eGJv
        TGxXZUVhbWtadExYaWlCVmRxc01SZk0KLS0tIEIzQm1yQkhYSkN6RDlMdFRhQzRx
        Nmd4a2h4Um43emV0VXJUdzhVZGE0SWcKei5M4bxsX1tOle+wkm6Qa6ZMX31kd7KO
        X8wXbGrXT8R9s7d76+I1mP20xMATR+awjxoQgYeRfUcexsfj0dOH7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-16T16:20:36Z"
  mac: ENC[AES256_GCM,data:yaMJ2tBIJsM6kzxWFUm+4mtq9ktmKZwWzCniRb0ZbKt4QyZx/OaWCNeeQT73oIU96woiWVMnQwjXa5OaU6hfL+91hUIOapNl7EfdCS9qN4qacVagE4yVRAHZBA5xFH2NZeq/f+IcBmSVi9hC7W6QqrEPqtdo69SkvBEbKj2MIwQ=,iv:ErLf5mApL4iCEBbX/ypHrmpZXBxG7ty6IvqDIpP3cOg=,tag:PCWdfsr51ErzGnbdDre30w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
