apiVersion: v1
kind: Secret
metadata:
  name: authelia-secrets
  namespace: security
type: Opaque
stringData:
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:90sHvN4iOetf+xiBbY6ihRoHOsUQjSnplxZpBYLh5Rqw63sh8WTQLgJIj+VqZ99bwotSe7/6XcJhYbJtDpWIBg==,iv:b0rYZQcZdWESIsqZXukx64IgOT67voi2fnrgFFGS7wU=,tag:A/o5uhSN19H6MvfkexJgEQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:naRKv4Rv+xg=,iv:UsFM82rfH5F+rYW7EnHy67Oizg830oKUyjGgU4Jt7eM=,tag:mLiOWYMDtMu1HUvtEpXJdg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:4mZWSDah28wJYPmiTp/nLnoRnLjpsd4H970kmIRuvZlc2F23gtc4mYQ=,iv:p74w8/z6q6PV00TARK/ABzZVT2XDu2tIxi2TNxdiOlA=,tag:79RcGSEgHvyaDGBVoZqGuA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:+kzrdp9vvT0=,iv:6P3gYELoN24xdrthGhfZB/d/4plQD7jD0nuQkjjKQa0=,tag:B9y3bRbj1JWB3pzuYqdKyA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:/VCM8HmIMQk7OPHREDg=,iv:Av4mq3wDSHkHk5d2MhdfEmia1rvzdTl3kAMjf9odkTQ=,tag:+lkowAmnKfAnSdJ/Yucg9A==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:anXDpyT++L4=,iv:IMFpTfBovIfUV0uMdTqG3hVWUyw/C8CCmkoTcf68zOc=,tag:Ekls9uzYdDTvjU17RqtoLg==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:pfEgaToi6JOIExLfQnmc/Q==,iv:Atlgapnog+/MO6bopZf5R68l24c7MPaQGoRLT324TzQ=,tag:5ibJ5ZyrQXKA9Jv/vUZvPw==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBua3dCZFpYbjJPVURxMC9S
        eTJ6RlJ3dlV1cU1tVHFCT1pKM1p5a1VHWndRCm15NmFFMEFOZ1VFY2g0b2Rpd3RF
        MXN2KytaQTZ1SlNhUWpHY3Z3Rjkxb2MKLS0tIGRxNmxWSWxnNnpZNFRUb0V6MWZ1
        YWhOVWlQYnpEZm9SK0VhR2hWMkxUZTAKKv14kgjufQM4neQTKzP23uTlSespNZd6
        Cgwojggmsha7X70n4zPgXsAg3Y9kQtQC35oomE9E3wtu5MmDWoNbTA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-16T15:28:13Z"
  mac: ENC[AES256_GCM,data:8WBRfETB6qiiSc6axLT9AlQRWGLUJfYMmHTr8eoFDdgh0405LL6/wMuM1LY6cVDyTJy93M8faLbAQTe1qw1DEuHNgtXTkSb6nsKqhiLRsXgAfPIFUWJ3ALScNpktAmActAV0ncxxN1hBH2ulAbpL6416bqIcp8Q4HtuDLMXbBKA=,iv:aBDg3cogCF2uFoEf0DQ/gQiWKQXNwG3NGrJ3OVyt3BI=,tag:p8i5yM0dxPP55SryA1en7g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
