apiVersion: v1
kind: Secret
metadata:
  name: authelia-secrets
  namespace: security
type: Opaque
stringData:
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:lyix3MYmMxgwXkkLItw/yVNTREQht1bduEfPPV/x61/DR924bFvMrfznSygTvkORy2m7TjQe7jCcHYw6ACI30A==,iv:sPQc1yEBzY5ZHSOOvo6cUoBSrpHeusamkO8Z4SdhuAs=,tag:gt0bFaXXDsDv44gfVr5g7A==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:L79jbkAI9Y0=,iv:db1YAGpsV0jhpeXbMxd9vk6N9lbVW25HTLMVwgqaTBo=,tag:eVe5wkU8+DGA6Ki8krWJvw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:BmtXiOOTDrSWUALFo9j24d/3xFoFxvgYsx54quLA8RPDaXm6xkgqeMg=,iv:HX3jWT6Bk6GOlfxv81vO4D6dkTlwqmoOZB5DsjRoeng=,tag:SqNuvENBUfc2FNk+AzFixw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:5NKbjriDu2Q=,iv:EX3H/LpLvx+uoNeqesGysfCOmBWI16MSTw+kdhWuMNQ=,tag:YM2Tiw9vnUwUShdP/Wj68g==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:5AgGc8kwpopEjsDLuJU=,iv:Gic+lWgoWUW+ykHammF/T7V8If2HAo2A/+ghSYMEQnI=,tag:VpWKII+4qnrHsJMu1KExgQ==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:xW7eAW5SmZs=,iv:lfe7b/Y0lMP7UNE6GeDhTud3Qa52P3p6c4H7APjZliE=,tag:YbEO1Ax0Ljr2OcoDwsRJ9g==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:yclbBNc18SFv3t2BJ8pR6w==,iv:7JiQ6wCWd7Ck+aSgWVkiX3Rlb6ic5MuDHj6iKv0ueJk=,tag:+14kDBJCW9dh+aifNlgicg==,type:str]
  IDENTITY_VERIFICATION_JWT_HMAC_KEY: ENC[AES256_GCM,data:7qSTyMyoDa2mweqIEDCvyfRQWuTllVWXkbY/BuuyJhBDzBq6IpfexIg611rCdoSPIKs9tePBENZel56o0ngZDHtvIrITLlBeXrjWHY2Os38dhoRE6GVRf6dY2Uz4Fv79beft0ycXYo7l36U74PuZys8lZbSX/uAAFDl7WhMGz0o=,iv:PS0z6rQcR31xjYqIf3QIPONL1ym0Ed7JuKWNG5EshIE=,tag:A8GH6wt9oNnsCKZAeHEuMA==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NVdIQUxKb0d1YTc2WTBt
        aFV0ei9Kc3BhamxBQ0hNOTZQNk5zMDBBUG5nCkQrWDZhVlNFNnhaRnpmZ1RtZEZp
        OEVGSjR4Rm5wdytGVnhRU2s2QVVUNmcKLS0tIDBZbStLTVp2UFFjVzREbC84VHdj
        SjEvQi82Wm1IR0N2L0RoUUFzTktUT28K1KhM21Jml/cR4OG9eU8jVHf35Pm7JAMb
        yU5kzfLBJSAzlGyrdeApDQVOJ+tWVuJnlgispEtuB/6BvRzqOC64dA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-16T16:05:53Z"
  mac: ENC[AES256_GCM,data:z0lcaflZN7cDfTBg+u8eeVV5VvtYMBzqfQzZcf41H436TBYr3PlfajwHCQb0dKr5eRSS6wuth4QuehsZUS46mws+ac+QJPEbWh/XMh34Z6h0ZWovXeCXWAzKH/MSoiuK8kliwd770LbSOo6CrCtKRwYevotOWUu1yPffxPuJ6IM=,iv:Xw5i6Q+v7/7aGItNoerMW6Sd7UjK7292UiYC2vWDmg0=,tag:oGZD1o3d9/vCdLftLsnT5Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
