# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:RG47Ecvl25fHimxItExzGnF/jHi+Rsyh7iXfHgamlGW5A4uIcgdGPQ==,iv:5f5iDE7rHLVemM4PcvP/m1EzJ7WdieAKDnUDiykzPPQ=,tag:Ij4b+Xm5cmUpgVDlw/GLSg==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveGgzbmwwMUJ5Z0prK3B2
        N1VMT0ozN2htcU50RmxHdFV4dWxMeWVxdVMwCndWV0JQR2ZSUUdEaTBNZ3FCL3V2
        YnN2T1VaU3JjWXhQN1hvZXRTVHIyaEkKLS0tIDFMTHYzclRTZW9zdzVoSVJXbVVM
        NGtKd1d2TnBEbXgxZW0wOFBjUEo4dFkKvzFEmIVKJvwcHYT45LsRhQUW3fBq4von
        NXSPzLMmX5rkzqJVZxX+AnASdzq5O6ngZ0HLuqtYCKL/079V5kckuw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T01:05:18Z"
  mac: ENC[AES256_GCM,data:KwP6TcTRoi/9sr3nYnlwrcuRGh+NXA2AoHSKcZyYJTigh/BH4R9A2zP3oFzWSmqkTEBmITQgXE+QWiWsvsgMJ6CkBuashx8h/FUxSLXnHH1j1C5dTyMzlPN894WNhgPA5+2UiU4DDcXuVHPOApo8X2nJjvpkOMuQ8kf9TW5bI/o=,iv:5Nixeb8Ke8HamyRw0LolRTuIK7+zDhbg0VxOfOonD4E=,tag:3kuMaE6c2zJbMvogKVi8uA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
