# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: velero-s3-secret
  namespace: velero
type: Opaque
stringData:
  S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:L0LVZEBGetH6d6cFoQ==,iv:SBbnzlwzRlFVb99j2B3Ph0KuLilbeS34TbCjr1UlQpA=,tag:c16widG7nAdE56YxgI++iQ==,type:str]
  S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:/noTGti93ojzgPv3LkeKGg==,iv:mJtwoPJanCPUMkuSeKtfx6/X2CkSzX16JrUy+dkb5js=,tag:HxF6eXEvKS+8W22z3tbwNQ==,type:str]
  S3_ENDPOINT: ENC[AES256_GCM,data:H60iExlFYtdpihEP/MATVy+w,iv:X4xACtVSKir5j9G/8OajZJDtQjpPFcNBoe55g2/i/qg=,tag:JJ5GLKU7TG5BF1NHfuLHAA==,type:str]
  S3_BUCKET: ENC[AES256_GCM,data:3dfbt+Kp/GkOl/wsJdaT,iv:zvmZMGP3zKfcI/FVDvHuv4qtYS77cF0gJ1AGmaGRz2M=,tag:acuRqq65Kpz2ifLLA2lK4w==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5aG5GS2VnQzRmWjM4Mnhy
        OEJZS0pESTBjbEMyZ3R2eE9FTDlNVWZOb1JBCi9VSmFwYmFlZW5QUWxxeWVaMkNj
        TDl5YzcyanhBdUMySmJTY1VqblNQdDQKLS0tIFovN0lWSENNUEVIQ3phQVBCWVpX
        NHI0UnNyem1EYjF6RWVRY2dOYUUxZUUKmFRfJlYKka2+/dsEwadGpOMu0teQUtgi
        Tao5JzFbiIvGFRwNH5CYscZ9C2RtuylQ+UVDr6f8w65Gr8VHBHpZmg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-08T20:32:11Z"
  mac: ENC[AES256_GCM,data:q76O5DvMDmUMir0Me15Ih1VQ/ZCQY6qt7T9LSy0w4pTkmwPpLvmtqfV3Y2h2oui0P7VjgkpoKUwGJFbUDkhQ6jeJ7P5iacg/saUeBpBVAC5NdNy6B744iH+E0VbMc28eQCiDejsbiDiUvzv2jCKo6SfctJ6sA2AII+RPu9pHj0s=,iv:4Np2eFXUuykjwlm3f0F9TWvarTTW41B+trnOFw9urIE=,tag:GycGJF1DKgPL+J4n2ynZPA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
