# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: tempo-s3-secret
type: Opaque
stringData:
  S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:5/P6crElXh7kX/WWyg==,iv:vDT1Wh7t1wgVFUrcGABNNnXWyWaXwOWNnMmuQOJ1fk0=,tag:46cvchUHIu26qrttMx01EA==,type:str]
  S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:inXi7pB7Gw74I4LozREd7Q==,iv:DD/AobRJnm6N/jFozXF3idZW5bf1Q7k54RW+qz0gINo=,tag:/Vh5Qt4OarZQ5a109Xrlvw==,type:str]
  S3_ENDPOINT: ENC[AES256_GCM,data:GQjnwyxD3D9JvWl6fldxj9Bc,iv:LHOa66J9PjL+7AhLmOrJofa7eCKBlf3o/3XHvapCIhA=,tag:Sd/kGPMavwxUibrljdpH0w==,type:str]
  S3_BUCKET: ENC[AES256_GCM,data:Y9/e8bgdNIt7XZGl,iv:wHhWq2uZVFoDu6OglttfCr9HGcRXW3bXOVX2ecxpu3I=,tag:msLqJrti7Pk2P6nwEVyFkg==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbXRLWWYwdzZyRkMvMU0y
        V0hNcHVpMmppbU8xTTNnR2pIbFlXSHdJdURjCm1IZ0RZNkFNcGNqQ1J4bE9ic3dj
        cDF4enUwNTkyVGFZOHlEZmJWUWVVUTAKLS0tIHd3MVoxWFRNWCtLSXZ6anpiSFNH
        MW1jajI5NmNaQXZIMm43WmdveGVvOHMKzk1JHyTXQZdhiu3VGyeC6W1E6xMs5SqI
        838mZ59s/AAkTPsSY3ovgDJYZRbT1PBpRTVSizQjsJn8CMEOzxxTsQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-11T15:34:45Z"
  mac: ENC[AES256_GCM,data:21N/LcWjfMPQE51+M5ZMeD6JLuwan6H0XV77/gxRTQZreJZx+Kn3IAC+/igt8iaLDNxpAwHD5FyjqWKbcqsFhMtNUw5ybquPZ5mEgReGT/yZONQxzeHoxYh8iauGsUogLJLxI1lPqYMGLSTOPlgZsH/3FLOyCmIlaE3ywMbkrQM=,iv:GefWavvZgTvaCNq0WicvgxTSjNEOxDscfU+B0ekNuOk=,tag:Ng7HTxHNRavmsHExe7ONGg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
