# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: tempo-s3-secret
type: Opaque
stringData:
  S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:aHyk0AwKbOVNJQfhKQ==,iv:SRahMsrUeNnpSKrgG8BWaWUMZ8yLcAQEC2i9h6q7Fxg=,tag:4sOYM49eJiLq+PL6+AbyxQ==,type:str]
  S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:YSlRnaIWW2dD09Nci19EPw==,iv:dQ1vGL1wbYrKOfsLf2SPuk2B+FkRwYDvCkTsaN6lzC4=,tag:Tn0272Uwdn45o+npWZ/OXA==,type:str]
  S3_ENDPOINT: ENC[AES256_GCM,data:28bWPfY68ug+apTZur3U6ERX,iv:/XCU0hnZ0kHHBMnFVtee6ywhyHWSIpmO3M65iU3cBZU=,tag:oOpqIfywQ6vp9xqOnJX3vQ==,type:str]
  S3_BUCKET: ENC[AES256_GCM,data:GbIeZD8=,iv:iuV4KGLi9Srepr/LLnYyaQ+TRtpsLqcF0Z4bREq0ZfA=,tag:2ULaAc2lVD6JubR3FMR20A==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MjZOL2kyUkN2R2VoUjlt
        TmlWTFdkMmVVcU1Pd2x4SWw3SG9ZaWdmalhNCnZZMjZ2b0FjZnUzQkVNMjhVemlj
        T2x3VkluY2Y1YWlyRXRwb211bE4xRTgKLS0tIEk1bjdGOGQrcEZVY2VVSlkyTWlj
        dk9taUdYZEg2MGhRVW93dWdicVB6WmsK3+jAg9hpZLGvHY4RP4PIchXirL+7a33v
        HFUj481IvZlXgjW8egPVTtk4GX70dKD7I4bMc9g4R+KOjywOcpPoug==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-07T14:50:06Z"
  mac: ENC[AES256_GCM,data:DLEED33Ho6h9avjVp+RWkn3pZs+eb0d+4d5VfItYshq1qEDKuJ20IP4sbhXPjsiy3B4NByn6c5rFc58N8nzOJGMuBEkdp3xKQFnTeA7Ax0u8VDN0uAs54DVo0AfRACuEt1Nfnzc4ZFyPexxtNKFNHToI7zTdH7OqQq81HOkPqfA=,iv:wDDUIwlLLRPfml1neObbXTdlxVeeQAD4v4Cfo8h1dMY=,tag:Zduudl7MZ6wbcydducXMVg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
