apiVersion: v1
kind: Secret
metadata:
  name: gha-secrets
  labels:
    cnpg.io/reload: "true"
stringData:
  github_app_id: ENC[AES256_GCM,data:IXjcmD0i,iv:/7FidmSOnv5kZ1wad8PakGtqZffAV65oGVmCGwP/pYw=,tag:eFx2WDj7ARsYBBJHrpokZQ==,type:str]
  github_app_installation_id: ENC[AES256_GCM,data:RVtFrjqZj+8=,iv:f65O9rWb2qDNuTLQggSilmSwfa2E+FmLXchfYyAbyXc=,tag:GxN9jnWMS7d4LzRNF0PYtg==,type:str]
  github_app_private_key: ENC[AES256_GCM,data:zKtRwhFTHxocjiAoGOngfz+T1cyidZj8pbFHJ0YaII15rIth1gyK+3d07xINpqT5tA4C9layDGxSdnZvvdNCj7l1u3ffEO7Kg4Kdk7CzXvWPH4/AJzWQpkzboiaNYP13tRZW31eSR7I+tdCcGLNSuotx4L9WpnHVuc3uoHYMs+Fu+haoviz0/be0yKMkzZiqdi7MMh/EA79q0yDZiqQ6zRKj0Wu/zg1k+kzHUndVghLIQxYnvp5e/yW7hjpZ4YIGbay7nxhZ5LU2kAFg+ZH1L8r7O9iMaid+cNdUHih++uznS9yIK3e0SwwMlPJIaIrW91d6zEuOdd1I7lTBSXoOA/ZF+/0yiuBl8o98dDzcfAAerQlXGZJWSEvoVHN3Vu2ifVrsT2MFORPzb8/vCF4AYJvjSZZhayso4OPflWXVWHXYxmyoSdKa8r0YcFHeG1M8/8eRrnwjeWWF2GhCkVwQDKrXGTFXnQuBDwFOPBwGFUJwOANAB8NpeqhQDuE4vyeSNZBYUwhKQulTC+iaIi/TFnl4Db2b73FK0f7a7xpBWMW25ts0XXoQcL4Du9VA+MrGJD9tnLVaaKD48CkRuyspvY9lFQZqI4jJZglEpYN+j+K8eT+0bU7JvBlfVNdInvbBZQjWQdV1jJzKg0TcVHd7qKlQ1gNs6Kiae7gAzZ/qz9/w/mLfynPAHBzTztKyOt4cISv/ZwYLoLUKZkzFHgtfEgDEpW3plmW8n9ya5HVxq9xvPsjCpe75WvM77iKMVJq+9Nn4bF0PUCN9Byjk1qxpwz0kXtj+Src8ICXs/If9SIJjHU3DFzzSq5BynDVu7ZfK2bGYeZ424UuyVSGxWeNZJOA0poVQwgAWp9eWgWH00CmkdUEAy0cwLqosiLH398fLdFSKu7T5gFdTrkTUeJQDVnP1TR1XqYr9edi5/8OgMrnjX4FO9A8ns9PbZB3S0Rz87jkCrGlPLoIaztwOwdLjEgCWZN59Z+fTg1I5QA==,iv:gpUbNRKccxIxJKBhlzWV4cdOERhsCsVueBY+jASO+z4=,tag:A39Yi16mMZtFmT8hRsdQRg==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Z0xUVHJmbkRBVjZuN0JR
        Qy94Yng5eGhjY3ZabWZvVk5TM25RRXozUURJCndDbm00c0ZucnRsdExtZGF0N0hW
        RWpuNlV0YlNZTzRwZFQvZmtHeGlmNFEKLS0tIEU5Z05LS1VXdnpCUFNZL2U0Uzlo
        VFd4OTdmclRNbEVTNEhmTlFJN2c4akEKQ0D7iavh0ioV3Ec78Da0iP639CwNlI9f
        5zdnvkhYGrdYqjfL3EcNbq4x+JYrLC6PC4XTVPity9AKg26O6+5lBQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-28T17:16:34Z"
  mac: ENC[AES256_GCM,data:1niN5R/Y1yjx5O6whnXHyJrXMgKZLU5P4IhMfh8wcxG1llROqbDRG+ifC7QU6883SzAt5f3CUvBUsqbjsla8quNo0hRAdY7dcCPeRZAd3U0wj2lRY955XTeT/mjRM2ec5GdviKpDoI8GwPFGplaXtWeMEPNINlfltMCXmrUWY+o=,iv:2cun2ncwBWRu9hfVrMIgju88gAKMd+ZgFEC3l5tSrCc=,tag:oC3rEfcfRo2Ih+bTtL0iZQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
