apiVersion: v1
kind: Secret
metadata:
  name: metamcp-secrets
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ede6w5Gzcru72Q==,iv:07dOzdDgQ6ZVpj0VEaJSWmxmy0eiB5uZt1R4KcNlzTE=,tag:UH5c3gHtrqLvFrePmb1Ysw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:BBnXIlPo/56i9uMm0aCUkGgHFAM9/4UWLAY4Mlvopfg5xfel3c3VB6Y=,iv:01SGOA9OUmYJuzrY99yQU26j5H7W9Zt9TCtQtY5NAQU=,tag:HtF9rggTPJVVvmRsPMUipw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:1MgyqXwHIQ==,iv:GWnQ+Bju1TLwZMTaU37psGjmwYyVarbT3GX0B8T9hJU=,tag:ORTWX7UhTUz7HEzXNQIC1w==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:fJ6yMC/B+BqSEhF9mXymjuAgURNCDf8gpcRAAZ6jm3I0Sk8fnQN2r4blYsHVIZRPBumMDKQdwSObjETcfNAe3A==,iv:DHxWWUhGu4MxbiytoJavwNK/6ubGd3xUXdLKd5tx8r8=,tag:fCqiUO0V94wsryIQi6GYkw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:73MG/9oGy7wegYiZ0ts=,iv:s14QtR0hW4qhtQOFIX2g33ecxm8IiRCyvDgMUwrAqQM=,tag:sFGDa8FQOyXcZMrukzekMA==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:kMtv13NMeBw=,iv:BQKBWwvH7jZGqUIPIDUEU/y1GrBVlTLai2frhmdlU50=,tag:ksMpMosW4AEVnNXaCwxzug==,type:str]
  TRANSFORM_LOCALHOST_TO_DOCKER_INTERNAL: ENC[AES256_GCM,data:spSyngg=,iv:kCIdU/PS0q87UuDRmg9V8NlY02sCuTisLF8M7AbVcHY=,tag:ErXQx583tUjIqdC2SrmDdQ==,type:bool]
  BETTER_AUTH_SECRET: ENC[AES256_GCM,data:NPPGz0uQ/BXbyAVoPQBFaEoNSRcSyLMhI5LzuWGHAnaaDwgdnY9bGUkyz9LAp3KGNelPat5c3t+6DmsEO7AyvJuuG/RfjNLWDBj/fEs19/NgJd9FZuGWuw==,iv:q30Jj/oI67acDGz4+ei5KkZ/wVBLfmzbOf4Pdw6v7OM=,tag:fMvrGSJHg7iQOpIHgDUpow==,type:str]
  NEXT_PUBLIC_APP_URL: ENC[AES256_GCM,data:vNhCkxg7QBMZfAcFCs13zzK/DA==,iv:s3uZKsRQNnWt/3tGczYXVpItQLLU20lq/lPnujWT5ko=,tag:wtbyW1vZFWvJDOdSJuerMQ==,type:str]
  APP_URL: ENC[AES256_GCM,data:DAi7Nnn2Dc+TiCRiaf5AeVzI2w==,iv:TcJLZwLeNFTJBeonPKK0yDAPS3g151TenVZz4bmN3Ho=,tag:xvTSWM03CB9iMkH6mV4AYg==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:ed/M+pHow1c3qqH6pWE9F2P8zp+vf+O2HhHbraAv2WBISvFJ4lpe2W8RKf9ICh0b1gzYLTRTeQiiPAQbcL73bh8Df6ZLNi+IPbsBMe13Jpg3sxfWTHgWbh1guJZDajuDpmFWTQC7sTY7UHI/rFx3VLKdiN3meDm6JDTyQuSeVnPabY6KpN1zLFPdbyCHS9s=,iv:XO/HoBK8PiRc8cOGXDoKYB2dp2w5C2cBi5sbenmW6mQ=,tag:vdO3JkQRQtDdfEC2BUW6Xg==,type:str]
  POSTGRES_HOST: ENC[AES256_GCM,data:MH472yr2HK1ePgz0ItFqsQkVqeMmysb0RNj6PAPCP/kbtrL0i+jFxPI=,iv:F1x9yD0PDBoiu7PLLCiC95W2CLljxlC12Kqv0hYkxh0=,tag:DsoXppH8j0werlWUGGguSw==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:ctYHkg==,iv:Zlu6oOqPz5sX34t9jDhZ+oSUBaoc5M+GDIBE7Sk9rhg=,tag:dn41USecPGqwXxgPbfDkTA==,type:int]
  POSTGRES_USER: ENC[AES256_GCM,data:YBP0sG1+Qw==,iv:C804DczMlGmkFRIXmv+LHOp9sZ1yMnHUcbv3+4CxEs8=,tag:D9HSIo1AsR6Wj0m6zivZUw==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:4Q0IiA3qgaU25+WXznLfH69f7hbPsjac2+oEofT3GQR3Xs95uxiAj3JTYpQL3UZhsI7hzNDn1k77SUag3GZONg==,iv:9ozDRTqYXTo46t/0iZSIoBbNOqvv1h1e+QTdX1MMkRs=,tag:qDoehxnpO2cpdak5fEMsJQ==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:J8A8uY6CvDX6EA==,iv:21tQJbupsmXYhuupoa/7PWE02ayjdWroGAueici6H/E=,tag:iWVDTFQ0x3AYbDTGa6G4UQ==,type:str]
  NODE_ENV: ENC[AES256_GCM,data:k3yE1dP6Yz3oaA==,iv:0dWYjK3GaAaKg9Vs5iAilzKvNF2sGVXZR4UMkT0ySAI=,tag:KESc1lEqFZkax6sqmyCvnw==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbk5IVzgwaVJZa2h0WE1v
        aTZKbFIrZENoOFkxMTM3TXVHOUZGc1FQblM4CmFGZzNLbGlDZW1IcUREYVc2T0t5
        WTF1dS8rUS9BNjgyemxiVUdxOG5nVlkKLS0tIHZjcjVKRmJRcm42eHU5U3RDV2o0
        TEkydjc4NnlLekJZb0UyRmhVd3NEcmsKQlMgUfqP0Ic2V5aniZYEQArUm0CYuCdK
        F9iQh++dMmvSaP62bXtXaoGfBZE+v1XK/L0lngjLeboTKyr2XjkvFg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-02T18:57:12Z"
  mac: ENC[AES256_GCM,data:US8Yx/Q+QhBExRy8BjdFRTf7wXCWrhDdFQPdzxAhBjDM/b3VBVRGPkMCAbaSq0p8iVjCuLC45HASsFomPJfKe4tJ344s7uxpm5X9EfaxAe/c6zsEiPKRtZgQZ2ZtVnb1pvBZPY2hNl2cl2OBR79ggbe/UVNUEcgPRXkcLPzmD0E=,iv:TSy4Ao4XFJxa6z/7SeN9o/5t2l4N3MOlRH4B+v5Pdx4=,tag:DbK53p41NLpu+g+ZbazCgw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
