apiVersion: v1
kind: Secret
metadata:
  name: metamcp-secrets
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:702i8ZSuST+7vw==,iv:72hSHCdxC5Smx+nbQmhYjKly/wqvZlKa+VgRssVT0mU=,tag:3I6Y8qPuzp5UCSAxHyGs/w==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:9Y/6iDv3XGu8IgCzksFYUBvp4qnDTvrJs2mVf6kacGT1fWNOnCTrgNQ=,iv:RZHuop9gNIKESLPJFUvAMuZBrENc00nzi0b0OlaeEkM=,tag:K65HYJqYnhNRmVfwRIB7HQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:juoIs3zYfg==,iv:4rotOOMU5FClEHE5rqiA9bMu3n/vTzbez+eu3LBWpfQ=,tag:8Qr8o390PhQOVSgs9XRuag==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:JqEcfgFE+ltg0Uez3M6DUc5U3ZlB94VsDSQiWmv/zW+Qp3K9pK62gQKRkSZBKwLZApNSmQCMArsYtD/H3I0QqA==,iv:90MwM0L9v7FuphCXwSUGdApXVBvCA+Uiyg/5MurtFIo=,tag:D+ndHjcEUrZSQdGaLGMzsg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:iEXOBz37nYlEak+7788=,iv:spiK3IJUY+Ik1E2pzQNWXLEjAKuiwGp5WPJ3VnASVN8=,tag:jHjXIdUZaGg/Nd1SfNAHmg==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:dUUbrY/+er8=,iv:o63q2flYKeE5vWRCIPB+SGqUYLlAeo9w+v2nURjY950=,tag:ol78LnM2pipxz2u6ptTBdg==,type:str]
  TRANSFORM_LOCALHOST_TO_DOCKER_INTERNAL: ENC[AES256_GCM,data:nIl7i9s=,iv:K8vTinXkPdRysoYM00vDMZUd5wQE02ywSOijCisTEYY=,tag:Brs/8Q/KG0uFkhWGFxTjrg==,type:bool]
  BETTER_AUTH_SECRET: ENC[AES256_GCM,data:kgA2J3Fm1VZhvNpjorISxjSVv8WC/sxvqMNzi8QtBfTmpx1qsnHUDaCNyMDgO9BN20NyTDJCbZVLGoVCIr17iZpLTqU3GZdezMZhz8P3ursYQNHbcpbCAw==,iv:+0vuYbpbFJOSaZ0RzRaIFXnZJUoZ9iTU2HqSgGFDmpc=,tag:kIsnhtFtS5DhPDByVqhj4A==,type:str]
  NEXT_PUBLIC_APP_URL: ENC[AES256_GCM,data:EUQXDFSsweKEDaG1J/44Oq7ZNA==,iv:I6K3x6iRh3wI1Qrlbuo7qIzz7Kp2NWCSW5SanV0ohFA=,tag:tpbIzR0RX5Z/2pi0obIvow==,type:str]
  APP_URL: ENC[AES256_GCM,data:HgGEhMWFixzJCYLx7glaDumfdA==,iv:EwD4CjRx6+KhaRBSujy/fgKVQ0hREyjynFZot+dfO8U=,tag:DOo5Q2tZ2bpR1g+uTqAEHg==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:MkuOUY/yt0OBm5QmYeJ0nrXgDBz4ng9LfN5MOkBzZuH1fjUCr1ZJCgnLgyR4kjjWNGclZAAURpZEbnpJMVzjtsjlWra0xurf7kohJaqy3qNmfwdlnE4drKS8cIguj4Ds+IW23jOS6NBaGAn3t18I4KcTAklUhSh60syZTzkuqVsgoa/6eKD2mqeQ/ih8ZRE=,iv:avTlnN87Jy/6S3C1J7EYZzHrNCaSZjxsysbfkDoBebY=,tag:A7GCotnsvJ/Nsa2RDs7kUA==,type:str]
  POSTGRES_HOST: ENC[AES256_GCM,data:NsU5119qNLjL2IxU1tmQmqje0pVRkK/2x1v9CiJLLq2cvh+IRt0tsyw=,iv:A0BCnUNNSeAQ6ryxKPJ8RruHWooLYYj1vX6WUmysbeA=,tag:5R7BKAowqAxdXxFFu8Qjbg==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:I7mYMw==,iv:Bo1yfP08GP+nTDjCCsMSN6oZi6lb6CyTYeCF9TKpto4=,tag:O02JfgWsyOL6Y2UxBlNijg==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:k+K+M4Au2A==,iv:afZ+E4fM/JqaasFnhFct4d1YxtrWMlttc7q6ww3S0x0=,tag:02nUPRTM04kLb3KVb4ikjw==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:F6zhD+sCQnBTzETc6DO5TGwB06KG5/bhgUq3AymgIWbg99Qfc/lqRsJyyvSvrkEBtxO13WJWCxjkHxR6HKCTnA==,iv:CnOtyc0hv6UcYWN+Oo7q255uY+Bwd39N1DZFy+8FeJQ=,tag:g71N32gaEmgEBgBHMFOxFQ==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:5ZcMK08nymwHqQ==,iv:O/G/IN8fYsKwOGsyqqG9orkvJhYBs8e6G4Mb44T/Y/o=,tag:mPO5qNljG8W1looaUXL3Ig==,type:str]
  NODE_ENV: ENC[AES256_GCM,data:pjr94G/dF6GsGg==,iv:WV+B7HTpG/OFwXo6sCMS/CB4/g1lKemmrc2xkeI+otg=,tag:iUcVMkqyqQ5N1F5KKAoyjg==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINlQ2S0lsbE5CcE5rV0Na
        TEw1ci9kZXJTR29hUHljeTZnVDgrcDdiUlNBCjFoOWpPbTUxYkJ6cGJrMHpTdjJX
        aWRnd1FnVlhQN3libDIwbzhud0JLNFkKLS0tIE40SlFUZ3hMWHB0bkdOVStVU1FY
        N2lHSHIrVHNZUVI3dW9JN3ZpZFJWbjQKflPcClubR4AAkowdpuSZIoQ3CEM3QdrJ
        mWtOL49PxOO4yUdi/tu17uB4gdE0QoPPc90yy7jtXkiFJlM1HeYDoA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-02T19:02:50Z"
  mac: ENC[AES256_GCM,data:j415j4AzTxKMGOGiWNrjClZ7k2GsnUxgS6wFGxeMa3dpg7sHQolNEwSiTWfAe4TJBCDqAxXZoQIDp1Tp6INjXFh6CLRJI3fcsgBMH6OV7VlwxPKzzx+iN/6Ya6kDQ+Khaa1ntLrpb1s4CtFHPX9fMjxCo4Hg4ZHOn9GrcqoCx/Q=,iv:Dqy0h1iG/cRzqrPtl+kTxvoqOml3fANFWTABMkBnLfs=,tag:DtRg9DEp4s9/h4RlMDHBqg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
