apiVersion: v1
kind: Secret
metadata:
  name: metamcp-secrets
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:mFwQOiJ6EOahGg==,iv:H8x7q3wXjZ9gz6eLSrj5UcmxDK9WVQ8Ns7LFZ9fJVPU=,tag:PtL0emcS9ad13cU8dSho6A==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:Dp56/tB6BHhTRw2nJJTK0JUidWAIPcOxZlFdkHp+YrGqYXwmQVmKBu4=,iv:J9PU6zgHJ9exQo7EoDmLF2T5Vo3Q5hpV1jVIOQHh650=,tag:cxMUza6ZPvzcAQPxdb8xEg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:vTsqBo3bOQ==,iv:V0VZYXGvHXTzNsmRkd5MB8fJWD/ocJJ+anhXsiG3OME=,tag:Znb0oL1EmPnhJYdP9zA7uA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:OmBWpc1zu3XaR1McXt0D3UR+xa1C5jfRBDRJakewOnJKFDimgXUx6N4O14R8s6H3gQC2lULvoJjSA820aizX3g==,iv:wW2jYKblcNXi+0QgjaL/R0g/askZTdUbtaB71oJSOpc=,tag:jdz8XSTdoYu6bQyvTnA+5Q==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:3jnPbqbzdFlNcK/U9Z8=,iv:MT1tUpZvUQ1eUvsI1LqqoZpGXxbcJRFq8/cNvd4J2s4=,tag:Be2ad0f4kBEQByRD4hb61A==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:EO+SNnEBaEA=,iv:XpSXXxSot7gVJcVeujWUYCGZi3MsYb41fEPqlSOaB74=,tag:qzNxX8/xZhZlw9hD0hw4Ew==,type:str]
  TRANSFORM_LOCALHOST_TO_DOCKER_INTERNAL: ENC[AES256_GCM,data:i9zNshk=,iv:RG4SlVwlP0/Y9D3PfLt6bjYaR4OWiDdQU0aJhrHOL2Y=,tag:SgaibtI2C07wuK1HXBsnBg==,type:str]
  BETTER_AUTH_SECRET: ENC[AES256_GCM,data:OpiINz2RIMYW5PAWhy32HlPhXkpJqiY+nl6qfCZKe5Y8j5NQCldF9t86eKkxfuDSaxEVZxAiHe+1pm55fdImZjATohQnDSLjoRIbpzGZ8NTCBnxE49ZoKw==,iv:xNwVkO4YN95KtGRcA1HDVZXDRVvF5ILf9BW35mW0ViY=,tag:CI/J99UMyH3e2rusXK6KqQ==,type:str]
  NEXT_PUBLIC_APP_URL: ENC[AES256_GCM,data:2mEp65lXS0XL8lnxEr8ZtSuStQ==,iv:/5AMydXVEMjR54kuDQ9GG1l8ORiTTJT+TEmhvujl/0Y=,tag:xwNV3hqp9AVDc9J8Mlwdmw==,type:str]
  APP_URL: ENC[AES256_GCM,data:ZbjXCDSQxIAF6UvfSQVqXwwSrA==,iv:ZGRWnXderYBIxRKvpfdMQqDuoTbxbhy0AskA59Nutoc=,tag:PV2kJo/KwyieAGaju+6gXA==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:8HecfTsDAc7aotzDTRtuGp3E+mhw8/eAuej4vcI+GM4GbCoY481xOGk/jPN+uSaHHumWNnlEivt9wSt94LEEF9jv5pzbyj9boqw5DSef2LV4yU6zRLwu3GHC1p2WYfJnyq8cP6uGWQPvvAT9FApehb+g/pmhkS3xit/PFb48CLbvbaKDEMDlrL0MDb/xEzg=,iv:vu5mBflIOmsrH8G6wQ2bi0XtW2jHDju91kIvsDcRR1M=,tag:7oYe9pIhLxnsbdPLH6WSaA==,type:str]
  POSTGRES_HOST: ENC[AES256_GCM,data:vWts3t4NaaBWm5g0MYD+tkVPLFrc28fOKzMr8JeJ7FC85QCjmw6Juzc=,iv:usPGafmsR/5WXD7yWrAtF656Vwu6LouTffWnoZEDyLc=,tag:jzFe6vKdWWBaLx0TZMunxw==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:TaDD/Q==,iv:2irxqDTAlhX8j1XOIK5Kl+EX4/czOoqByoO4e2T9Z/o=,tag:2Lq/vMlvs2c+AJEv+/qrEQ==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:dcboduIwkg==,iv:w1cYTI8kI/E/d/mkbGNOBLG6TL3Z8sXX23yQ3MNK4js=,tag:gNf8syS0vhH0gtRXy+OOVg==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:CK1nzG96JgwKRb8FnOWk93VT5rYyhLg1F5LKNnkcaLi+nFnJagmbsRKV+dRuGqY09bTeG7rq57W7yM0hC/pqBQ==,iv:a/ZFV5FVdhcvu+WJq04l3zKWOmNo/bs+QaVKbPmiX3I=,tag:2cZO4qBm8KvWjUORAwDqSw==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:iPjWAnbsdaaMVQ==,iv:5aVMEXmeq5OBCT9ihQYMCgT8W3fK0lkTqYzr2rLJ7UE=,tag:iZt9r9VAwRfd1mAn2K4Fgw==,type:str]
  NODE_ENV: ENC[AES256_GCM,data:w9OzFbxlRaOTCg==,iv:VnoGhvwudFdkJNkKudR1BKO6NB6cpa8wlecOaJOA1BQ=,tag:zxUfpU+woFkOy0tdjwA9kw==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDS0xoM2I1WDFaTmdvcEFF
        aStLVHRTekdSbnlBWFNXTjFTNCtNYlNSQmxvCk9pZmo4bmZ0NHZBUWtnSWxxM3Rm
        MFVMVGxLZkZBNDhaSi92UEFNcG5zWmMKLS0tIGVoWDVwMHZveFlyOUViMFRWZ0Mx
        Lzc0K0pUdkR1ZVNJeG9oZnNrb1hQS28Ko3s+rhuOSxVg2fTC/3hYdAYyaM6daoGJ
        z2pCqA61xwn9x3a4ksG2wgSZlOibgYq+StiWPx1LF8kVKvvD7aieFg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-02T19:36:05Z"
  mac: ENC[AES256_GCM,data:YQdwFz+l0/wRjE8ccrMLvjKDXbD3492h5nD5Gm16OSX1bbeuIYZuupnUeboqGxMYnOF2+6RyhUXpJiz+zxzFJrxnbZstQGUheJZQe0wVnjK+LY9JaZLEO/Vl1MT6raNdNsEoqYREsvjIJ9v8fePUf/e01lpBDYU74O84qw9MAFM=,iv:qOV1eNoHiewEfw9NLwoAKrwGZqDQYsrOAhijgBCrAwo=,tag:ikJLmBaTiGE6RE1i+xK+mg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
