apiVersion: v1
kind: Secret
metadata:
  name: metamcp-secrets
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:EbvejSlLc8mKYg==,iv:GbkavGLxKd25YvR2Ez3qy4c+RXd6+bikwLV6AfqF+k4=,tag:ARzmhxcLjLQFBSIUyhDdVg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:XH39C80yo1oj56S3rleM5PGS1UtL/gDzdH5Tjh8zCvmxfGeHRhrjOHA=,iv:VDstn5JIILnTxsgwB6sBO1T/F00Wv4/onl1en5imRto=,tag:8/z8I7r0G8z0NB3tqOU7Dw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:3PVsiMlpMQ==,iv:vGLlPSZRIMkO6WncwZPVJeeX11u7gvR9rVcspUtT2j8=,tag:mLJXV7M2v+e8mPXlzX0YEA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:9XDRw8hiNNeT5KlbFHRV8wAn4EavOFtYBzzZY8d4jGaOLsIfGQMwYoRJ3Z91yuTaPb0MHHHowzy+tEAb93OyOQ==,iv:C/R4ZihXp++aVyS282uPvHHAxVT8yRpBZQrXg5lGLsk=,tag:ruUAPxicJav9RW1zbmVwUg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:9ol3Ve5Be2sf7isUIA4=,iv:Zec0xNORQrNZngS4EDkfgNMwg2TDMM7VDXVxMlGEn40=,tag:33yU21+KHlVTUiZc7nEs6Q==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:4GUee+zXXZ4=,iv:WseUmfJGuJiuv9h2N2P3I6/TOBW1t3AsCSB7ChRNABo=,tag:7zkRfCBfxqTebHwyZVo3RA==,type:str]
  TRANSFORM_LOCALHOST_TO_DOCKER_INTERNAL: ENC[AES256_GCM,data:8LFTa34=,iv:E5s7sVmjyy9p0TJlQ6H8OhEkYpHHQLHKrr1nXQCjhZM=,tag:tW9s+5APQHPtyI35qHsa3Q==,type:str]
  BETTER_AUTH_SECRET: ENC[AES256_GCM,data:7d9MJSB0SG37IGIAjAAgobDYpAXfkxLFx+dVbSgX6zzIkiC4P/BMDD/C4GSfF+a0WLBJuNWFDU4p8zEvhBPkOq4cvROHD+Sy/0uq0ceSL//l/iUgEuLugw==,iv:7h28REH2VpsI2Lantu40Iu26DfOmSIobfW/jkFMj0Wc=,tag:Onb7DTjXHmWMT4EP2ZvuWg==,type:str]
  NEXT_PUBLIC_APP_URL: ENC[AES256_GCM,data:qLfcOT2ZI7/HlNRzFUf5/D7X/Q==,iv:3fP2yXDwPUGYGkL+RTZbsugpVPeQRq//3+sWqFOHZAY=,tag:ozIGXsMpgl6RGvf52dk61g==,type:str]
  APP_URL: ENC[AES256_GCM,data:8uiEgtsEvsQQYSFAuBYvNQUGpw==,iv:rLFisom3lLuwdUnmso6MDVWNabcT70qS7TQvphra4X4=,tag:Ffr/YnG2ftCJBzfO0iAJJw==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:6CY4f/w0rByWKLs/JAOsbxuEx231P9TBevgK7PKSn4NQ9Os9gybb8Io5gNyH+kT95aL4Q/whm2H8LEmT61SV5aqmZlYMHJ9DkzlCQebOktCDP88SvtIRlPaqFxqBXE1C4KW9S2J28heYMitAbUKWjbF5M9/WfBFP5QzsFTeE+ya0ccqgUc6z68C1VfbclN4=,iv:QSrTD9opyjeyy4XKwP+ANXbCbh9LWE0X+KFbyDYkB2c=,tag:MUsr3Nxje5io9qb+F88uKw==,type:str]
  POSTGRES_HOST: ENC[AES256_GCM,data:SjYVW+lUEdhqJkdsDtN+rlBMRRC8cI/xOQn2+NiDZ9/NsonuWYC0evM=,iv:qJ7O2V01NjpdiUypCYa/pfSXBvgVAu+6uBq4ghdnlag=,tag:EZGPiRmzNkoca5x41xpHug==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:OaOxLw==,iv:/gI+a6NH0UbcV3J5YBunHbaB94NGLRXBzdpko7U2XIY=,tag:esLW5zsYksn9Z6UQ15JMZg==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:tgOQAA07ww==,iv:TS57w2OSqD29Zxxrn5DnJyuICEUBCTSZ2MPTuUw7u0A=,tag:NDPSfFhg721b7WG92NCTvw==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:bDiF4XIQrozd7a2mYA5N5spDVNx2iT/S51PyZ4KmfokABG9xj8LOeuouDZNwwjk/ddZg0RFJRLRAmT6tizqzGQ==,iv:Am3EroZgtkZwyk4h4DnL99EpMTdlhkDJ9Hy98SB+1qY=,tag:QLR0Goq2kv8oxfh6mK+ZHw==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:ucXJcPjMrCnBRA==,iv:vFN8BODDYqrRvPOa3a0xVet86FTh5GHXR21taMT1zns=,tag:m9b2+FGmT31cLaOZSbHjgA==,type:str]
  NODE_ENV: ENC[AES256_GCM,data:Fp/VMXjhiwXuhg==,iv:B4n5Y8mG1AeXYKEyU+IzpxBWcAKukWc7uA22Cu4FXt4=,tag:DSt6NAJMh3Co61DSxUm33w==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzckkxblVDR0JGdnNtaWx3
        OWVSWVIyRlpaaVorM2hFbGZ2WXV4Nk03M2dRCjFIMjQvd2lFb216MXhhSW01N0oz
        SGNpS3J4RDlrbGxFa3pyU0R2T0tDS3MKLS0tIGZVZ0JZbXRKbVhZTXJrck9IdGoz
        cVBaMkIxZ1d0RHYzR3A2eFdiaXhmdHcKZoaq4+syR2A8MOV/RS8RpObG79ax2s1X
        HsZTe2uMfVC14R2BzVWm3sHHXkNT3Vaxf51pQ7p6UpeopgR8/9r+IA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-02T19:38:32Z"
  mac: ENC[AES256_GCM,data:fHX3KmTjACwnJ5OV2mDpuZSSiOMwqhvgvWIjjCzA3ujiXni6En/Zte17Ngs8la+XaJivF0Lrzjx7A8cIYe0tt+naOB2j4lpQAfpz1shOpuVwmWGGJ8HpNaDD1zJJfg3FkULQa+c1CVKO5uwE2z/mdcUxLRE0v2ArjRxYl20asSE=,iv:4SNDVGElDvlDKDQEENuTHAFBp59IMWiiGXVSWN/G1EY=,tag:vSpOMG9letDZ1nOeTuLSkg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
