apiVersion: v1
kind: Secret
metadata:
  name: metamcp-secrets
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:pHVhnmVHwrIFeA==,iv:H/0hxZlEGVxwtoK/nzEjhjTkQz9kgo2Ea5cFKbPVOzo=,tag:P6i61DIDkL4P5JaQSEVrNg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:N+LL0F+BmFTCGJJYNw63WavDMhH2bOykwMijVtz/ay9/IPt/dNhMR3Y=,iv:pCdvKnvDACEtsOMoQAeWxKfde+PJXgNRh8xGO+NRcIA=,tag:wtc6ew7GWPrQalEYtU6MRA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:np3jSHZ9kQ==,iv:iOQmoMWLyTZhgYFQV58O9zGRkoq0R1ajeCVc0OmJPGs=,tag:IWdcm8nbHM47Rk6EhLxEHQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Pe1P8odsIe9ChGQIAvGJpik2jc7u8y2NYenJSHqnU7cYyGZG5TQQHumkIvt/P2glzd593xMGHeY1XkjqSUWUzA==,iv:brxoiTIg8k9+sg7SNJCrbz8nmHzaybPYL4EFwtexjVk=,tag:/3SjBEuSSjFLWIeZAFJcYg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:AIWS5+u8cs1D9vF9PW4=,iv:7k6DPXpfukqZCiHsru/W517JQB60IoEHpavU3cbWpLY=,tag:SAUay4MF4qIgcgbPtheBSg==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:TpEoXi4NQr4=,iv:Ut0DISX3iyOHLU7bI4bLniF0aw9c8J3Jq1JE0uvuNMc=,tag:3Yo4eYkVRxqSdgwy0liGfQ==,type:str]
  TRANSFORM_LOCALHOST_TO_DOCKER_INTERNAL: ENC[AES256_GCM,data:VcpoTro=,iv:zovlaJGiqSg1nLe4TbEMtNQkFa9EJDV2Yv9GR/UyG2w=,tag:fz6aXRuaRPLQWN8s5P55aA==,type:str]
  BETTER_AUTH_SECRET: ENC[AES256_GCM,data:K8pCD26Ygo40oxF8iZjEpqmo4cYNjnD8n5QZqWIT3Z3HgaDyY8uVdxu+qiUVscXgqFAGQEsxLQyfTDrZgkKjsH8Y1WFLnGYAZCx0HKNGbJ6C8iWj3M2nQw==,iv:71mCXKrsAz+j6CsS7N+0Xj+gZ88XynMZpuIBnVUP8Ao=,tag:YV7oSdU9VTBZ3RseYJMRmA==,type:str]
  NEXT_PUBLIC_APP_URL: ENC[AES256_GCM,data:4L+EJzZ0weZtzrHsywp2YesS9A==,iv:rartKjL/3rkWHl6Vu1w0lJs0sOXupC0kZ0NThv1HRlU=,tag:s7s/1uFidZaglfxmZJaTOw==,type:str]
  APP_URL: ENC[AES256_GCM,data:VLRbxAOkWbstbkvEVm/cntiEiA==,iv:uE0IVYFLz4/C6fSq8GgXG3B5HeHq0fjk5ZBdy5rIONA=,tag:f1iRFhopW0BBE1oXV8jIWQ==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:nk22A6cDK1KubitZLRgyDSYuV9K8zfYCJ2ozFZZtzS4Jy9rPkATZpygUvGbfaNmJy16WiiffHB3nr8XozbiJA1QDHYV9OaAFGrMTZMhU32b96ZYzqFfI6AoRwmSzgEMYqGNHDV55jituLrt8xKryfxU1qJCAUCaXTaCDUVG0Ie7n6tjfIe0Lg7W5jSu3X3k=,iv:WDPmQ655IF+rx8iFe7DUq/7+yk5nUxcbP80whZSnUhM=,tag:b/Nvi4GgEb4BuW+8yA0HNg==,type:str]
  POSTGRES_HOST: ENC[AES256_GCM,data:4yqRVkAfr3/6u+/By+dMUbN9PQbuOA8w1LGu/FHIUE58rHwVAFeODCo=,iv:SrFw/M/SUSauh17c3HLeBQUFORAxJiMdKCp48N62anw=,tag:yYtKk+7PDr5KKd/VVpg7Hg==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:/4m8Dw==,iv:5LSxDqtto8OgWfKpLiCQjhxxG/7OtkHjSk3EIpZz7CI=,tag:L19WC4b38INDJ4kqEUXS4Q==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:EcwVTd69Hw==,iv:icQlQsq71RV3rZjcrduJ0JJalqZRX6GN88KbTkywJ4M=,tag:5ZBE+MvpmMf6lDeLeaU8sQ==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:IPCxaJFhhV4leF7EneKV84SJAHpYjrBdHyBiG7rRrIUZhOeZGCkTYh4qk8AYQkZlSnYn+i0dvXQhlaqcJ7uxeg==,iv:Un+qpWKITv+9A7HXKaBX9uybAiV2yN5DAlwC1FcPzf0=,tag:GrMF3AqhgfBtUsFKKnCAAg==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:mWM1gHlJQwIplQ==,iv:Wpvz2zSGTtynPSL3oR+vsi6sVSaGP685NkPQvMYq3NE=,tag:lGrmM+tuk1rhZiuUJA0sMQ==,type:str]
  NODE_ENV: ENC[AES256_GCM,data:3Hg/DF6wRCZ5iQ==,iv:38JIrlfMVLvIyToN5osbPy3O12KMeobQcuBEoIaSZ+4=,tag:nyBXEeZx9o7F1a0ymqIxXg==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcmI1R3RaUDhRaWdzTTlL
        RGlRRGtyZm02MC91czduQlJEQzBmbjJaVmpRCnpEWTJZblhOYjUvZ24wbTBuWURX
        U3diR2U3SE9WMGZ5cTd0azd2ZS9zNU0KLS0tIDd5blk1bXdQTlRWNDQ2RGR4RUVX
        SnNhMGVsbVN6QVlSbXNGSnYwSm96TXMKKNaiw4CjEtmJ2uetRA5TUhO17sYVyyqd
        6b3nQ0fSLBkEziF/eNOL2xVEkBoo1O9Gcxs2nx6uSIHxo0t5xEhgZw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T17:19:01Z"
  mac: ENC[AES256_GCM,data:P1n7CUkWY1fCT4N121Z+cXMmPMQoxH9qT4fEIJZ6Nt9CI3ZXzv5qD8rqd25qqqq473/JNP0f4yxuBTrwla3zvXV3WDorUxFux5ECrdhoYWN0X8f2MazDaZsOCy0UW1fYNtTRVWRC2/9BQ9YdregHg62puG1kGbU5GfYMAI9Lb5s=,iv:t5Mc3S2FTzma3iCylFBxN5dHbbCTzEY0UP5I1PYACkI=,tag:0E9f/OZViPkQdR6rp1ra8g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
