apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:MPknBWpaM8DP,iv:MlqxavJy29SNVQoiWxzR72Jip7wmLHDjmYLHExgJukY=,tag:VaXPwbOfddHZAdgetLWBBg==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WDBwV0pIdDFML3BBVHRJ
        U2toalFadGU3cUVqM2svakpVQ2pVQUd6RlRzCjNpSDZZQWJ2UWg4TERXVk02WGpr
        aUdINngrS0xUdEEwbWdRZGd4ejVKUG8KLS0tIEFKVnhTMjNtaGVvd3k3UnlXVTJu
        ajIzeHlTZEFKNmVlOHpOQXdYRzc3ZWsK8H/34ogwWmzjp6QUetAgZVaWZGFdfTvF
        EfxsDtEzVPn73Z2uaJwvvkeooFJWYc3iCoUtaPshXm39Yl833egPZA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T15:27:09Z"
  mac: ENC[AES256_GCM,data:fuTWuxK2XLBIfrhb3InAGCEqf/Cde5SqPWEHhO+GeTp/ZkuVvecwWxy76i6CfIw+hCB5y0jKN/sYciPRVP8slUmoHeCj0fI+TfaZA/H9C+B8loXPX2p6IsusQJksu49jEqDJKyqfcB58VvlE8Ku6NCRJnzX+44g4uvoFmcq+mZg=,iv:StP5xZxHiIRsnzSaFhSLSOVJcwcFGtt4vei5G88AwQI=,tag:WnvS015mmcRhNqgRzWMs9Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
