---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: parseable
spec:
  interval: 30m
  chart:
    spec:
      chart: parseable
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: parseable
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    parseable:
      highAvailability:
        enabled: false

      store:
        staging:
          path: ./staging

        objectstore:
          enabled: true
          type: s3
          endpoint: https://s3.68cc.io
          region: minio
          bucket: parseable-logs

          credentials:
            existingSecret: parseable-s3-secret
            accessKeyId: S3_ACCESS_KEY_ID
            secretAccessKey: S3_SECRET_ACCESS_KEY

      local:
        retention:
          days: 30

      resources:
        limits:
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 1Gi

      service:
        type: ClusterIP
        port: 8000
