apiVersion: v1
kind: Secret
metadata:
  name: parseable-s3-secret
  namespace: monitoring
type: Opaque
stringData:
  S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:ErWuyMVT+Jy7IOVXng==,iv:OlFzMIQ+v58SRyr6L+S0eUzrvA7vs1wbYsh8cDFChS8=,tag:dUxmdbtK0+UOVTz3eZgC5Q==,type:str]
  S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:pB08C3p6qkda5/6edoH8LQ==,iv:xfv6RPix5Tti5z4rW0Dy/RkRiaZW4rOYYw6Uz7swgDY=,tag:zLgTovYfrvV6y8LOLqqHgA==,type:str]
  S3_ENDPOINT: ENC[AES256_GCM,data:d+oEfaDxvcYROGqbouDWBsSe,iv:iWhngPE+SesQkbi+NQGfMFOaggWpiJZxkjGV0rdVPSU=,tag:qjxM+OaAJUv5UqoaSOIwUA==,type:str]
  S3_BUCKET: ENC[AES256_GCM,data:F35xhbLvVaKzdZgaz0M=,iv:v3XJeX+EdGfHDqtrDjNVIOvszFfRVFHxbAAIypNIKz8=,tag:r7HqpLXxa7RPRxtnNw/cCA==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRU2FBcit0ZVE5ZUFtSmpE
        d2hzWXRTTCtVVmx1TWFKWVdyR0VXUjFKcDJZCnFaTEo1SXZiVGJEUmdYL2VSaHpH
        RU5MZ2VIRDVkbFhuaENXcFIyVjRWdTgKLS0tIFJxZUJyUnd6U25YTEVGQ2FiYUR3
        STZuU2tacHRXUlo0cFRpcXFkMEQzVEkKVd8kK+qI8NS2DbWGiw9ABi/gpAwbLc9r
        YREUfJmQj2s1Py5+E8P/OJTerjbR5OHAWvTn43rx2Kb719I4ishejA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-12T13:55:05Z"
  mac: ENC[AES256_GCM,data:gPSwX/Y/3XrtJNgIkHMlIrEu9k63352JNDwghukJdIVpowxRXz1HQwa60/h4jn+Q4/2Li/JoybETtJz4PZSMgTFN4DU8c9z20LDDue7a7GDkL5ZvR+mbDxuyInK27wGoFhS23/B73eQEsjppbvE6/vjv7cynIwTOzdfB/N4SULQ=,iv:wFJ+RfVSC4GqLgNPvbOzoOjOkRc9t2S3pGYskhKkfsI=,tag:EUuz8ELt3n4HGMA8QbReVg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
