apiVersion: v1
kind: Secret
metadata:
  name: parseable-env-secret
  namespace: monitoring
type: Opaque
stringData:
  #ENC[AES256_GCM,data:nxoYjfBMQQWZ7kXom6KWDeo4qhYYa66o4eZrUvPaCw==,iv:p0eDOKdu8CthsZ7nCbBY1XXppXekNOGfS0PD4SV1yHs=,tag:I8lUirDydgb1xXLqhSppwg==,type:comment]
  P_addr: ENC[AES256_GCM,data:sXBvqvGbv/8txYEg,iv:xnW0PYJkAoqlvajA5tuCieTlBQLK5gZ+FcrW3tKk4sM=,tag:rZBsPPobXfjMXkB/SFPeTA==,type:str]
  P_username: ENC[AES256_GCM,data:swqfC18=,iv:WiivIHL9tIQUIR4Bs3IiWjqNcf4tB8sl2YX4FlDp/0I=,tag:9KL2DG168Ev4fOX4oRw04w==,type:str]
  P_password: ENC[AES256_GCM,data:DXJjqjnfCcXJ5U0jXxReRL8DHseLn+I=,iv:xoLdZTMTBAY/ykFEsHpqaPQQuJHueG6iam611Q3aP38=,tag:zI9SyKXQKZF47SBO83Pd/A==,type:str]
  #ENC[AES256_GCM,data:QCakvgR0q375Yhd9jCf57W1yWRg6DtgW6HUV1yStegGVQmk=,iv:ThUOxSig2rjgWczyJ/6aQ24mFeAGuT99htBBDtvezNg=,tag:7sBQA71tXAjRsHrSeXrhZw==,type:comment]
  P_staging.dir: ENC[AES256_GCM,data:VJwTyDb2WMWn,iv:wokWer6lwkHGKY7JUQnoC2j5/chks/rjNWkpkxBQa/s=,tag:7JXCKN7a1K5NALn6Hy9OqQ==,type:str]
  P_fs.dir: ENC[AES256_GCM,data:E+dpiqBJ,iv:1uNlGAo4KTsWWcHxpqgg52z2qdSdR8pLUFl8RwSXDEM=,tag:DK0bB6Ni+lhli1+1gS1FJQ==,type:str]
  #ENC[AES256_GCM,data:E04hR582XmHUrNQrE8HnriM=,iv:YhR2Hk14OLr1U/ZpID1HDjytqVABCHakEl1bga+p7ZY=,tag:kc8ljpEk6m5WtCvxdvk8/A==,type:comment]
  P_s3.url: ENC[AES256_GCM,data:L0BF9Xt9PGAgbqThF1dFK4X5,iv:0ydXbxEMf2Zhy6mcYCReVZteRlAK77i73Rmm95cTkQU=,tag:IqO72KirY+G8yERc5OOn+w==,type:str]
  P_s3.access.key: ENC[AES256_GCM,data:xj9CUQyaiAeJ+YXFYg==,iv:n5cOEqHN/G/s260UdDNDjyLQWxU5GaJNeHCh/wEcfEE=,tag:0KvEFvUyRlKjhZEXL2si7w==,type:str]
  P_s3.secret.key: ENC[AES256_GCM,data:+xs55URsJgMaBQ/B0oI3xw==,iv:CRrUy/i48yFSt0dJ8CjayEXteh9rLsBofIUs9jXHNe8=,tag:chAtgb2s3UcfNZohCr9viQ==,type:str]
  P_s3.bucket: ENC[AES256_GCM,data:dJqOtYco4klqwDNAV7I=,iv:gXf6reRg5hFHawSUMmvZgYXsK24rTn9E7waxQSpuXMc=,tag:veU6Ukb9CMBjIi8I3GtBcw==,type:str]
  P_s3.region: ENC[AES256_GCM,data:vHhn9tU=,iv:HdjxsdfJUQ/NXEkMq/GELJUSCUv26ht7lDY6hTQswF0=,tag:Ejejb0oBJW+6SFhPsxh6yA==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bGVnZHc0UDZLVmtpS0ND
        RmtTV2NVMit2aXYzMmRHZFhucGtwYVdHM2xZCit6Vkhoc0tuS0JqMktBcExZWXZC
        WDBKMXd2RUlxV3FJRGN3NDRkUUFGd0UKLS0tIEZhMlNuZ0NGZFE0b25pZ0M3NCt3
        V001SFgxWGFQM3JQb1NxNUlyRTV2ZkEKqC7kceXmiiPxjvSJP0h8rAmOswMHcmgY
        LmGbsTrqvSJZn4mN/Ugtj5yYadeNOUewMfCombJnjbuv6iYSGROx4Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-12T14:30:05Z"
  mac: ENC[AES256_GCM,data:DKeJY3IiL1BWUKJS8V1CaCDuphAIqwGequVY6T6A8yyfg6njlJRCBZAjdyJhlYCvmW7HRmYw3PsAQkXs1DmVm0FMFWUwoeS3lpiW8UbwDWx+7jFty3iFLFc83nS+tFUG33zs5sdrv7s8+5J7EhHtBO0PIkkILW4xB8Th979IO8Y=,iv:Vg/aOLY52X6vprgvwGXzvRuZy62L7p+o2tA//8JdKO4=,tag:DIxP57JQbvJFmR0L4hQ3yg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
