---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vector
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/monitoring/vector/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: monitoring-namespace
    - name: parseable
