apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
  namespace: network
type: Opaque
stringData:
  UNIFI_API_KEY: ENC[AES256_GCM,data:LRcTzewk4F8QO3ZykNwZXYSVZnbZCi5p9kHjvRvme+I=,iv:At3d74jaXYjkI/NC2qnl26xm7ypBj9bVChyDhYIXVfg=,tag:X5bpfqqcFraFp2N+6JBE9g==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZVFzYXF6UGVrNHhyQytz
        KzR6RC9GZURDUERFald5RG1mSFZQVjd0cVZ3CmlaNmVPb0hPODNWUnBUSmlNOGx0
        bkFhb3JFVGVxcmFhaGlFZlZSOFlkRHMKLS0tIHZ1Q1lBUU5SOXFUYWZHcTNXNUM4
        Z29aNWdXcmZUUHF5ODIycjFJblc4WncKWL8fhC9uRPIJWHYmJl6OBY+X64AkYAMa
        CikB5Zi+G6xR+AIOLBTx3qlURdwvLgLkuAMtgHUTNzodtNVfO4smtw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-27T21:22:47Z"
  mac: ENC[AES256_GCM,data:85N7S8jcmcdFA8avroVWgVNUMiXE2s1nzLAHWcqh819w8Jdl/l5aSV0FrBC7Smfl5eFrPNUj2mUXqWFHATbC4zVNVA2JBxDDZawwA4dOaTE8Ka4a0a4xbrLYVxCDVC8/Z9jZFulBau6Zu/9/Fr4tHMOQoJ+Eim+8yViUsv/gTXs=,iv:gCUmQXikThyqIdrYGML210CwdxNW/bao2DeA82uoloI=,tag:iKZk0M9n5nIBVf6omCnlig==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
