apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
  namespace: network
type: Opaque
stringData:
  UNIFI_API_KEY: ENC[AES256_GCM,data:hAt0xi5B2/N5A2UIXQNGb1oSTzZMfCa5IVTux0nxVwA=,iv:g8ejn0wqdakjuRXY3wegUhYIkAXu3pOfZvi8KKeOd/Y=,tag:queQxBHFwGQq1RApFkPb8Q==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNm94NDlxNU9Zd1dudUc1
        YUtPQ21KRDNqM2hydUh5T0lES1lZc2JzRkFVCmkweStndW96d3VZVVYwMkxYNjI1
        b2ZhZ2RjbjhuVGllbVJiUFhYZFNIaGcKLS0tIGpVcEtTTVBNU3hMYUkvMFZ5YXpN
        K29sd01FN2FySkNXWHVNRXI5RUtlYXMKYwcGuYRhUFtRq/iFDQvyM3bvkiSQDUMJ
        TH4oNi3qyE060vTPT9Uz21IPnyMcmnVvJ48NAztTMLFwZH2Zqc1HTg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T19:31:13Z"
  mac: ENC[AES256_GCM,data:4CsDgiem1o4Sh7gnPcZs4rGMTt9tOa7noRfilg71oOpwqFYWKERudiD6bPuCauI1rjDEguei6yfuNOAjCC5c486xTIDXJQ/zxx6Cw9jYu1qvgl0stvvjhdGUwUxwC7oDpzxB6Qo8R5e5p3PxUX7bOfpvjHgQoys/+WoyaM1X9Q0=,iv:B48kS45HzCmHuCzUPYpjY7vWTQ426N9aIaOhRTmupto=,tag:cMzAUXRn6XR+R4APsgPr2w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
