apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
  namespace: network
type: Opaque
stringData:
  UNIFI_API_KEY: ENC[AES256_GCM,data:DRVzp/dA7Mf+WXp3xjfJZ2N8a9oXdrVDFnnuaZn7hZ4=,iv:QR5hW5lLxU8rANxICndpZRbXQz61v8ZcMjRIiqs40vs=,tag:InZ1KFYwLT0KPDlMogY10A==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRUVMVVBZc2dWUG5CYlpt
        N3dYdmhKdnl5TTUwaEgyTjZwbm5zZDdyRjI4CmJRaXUwNk12dDVBWG9qbmdjbUlF
        ZVJMdzdua2czcm81RnI3cHNwWEUvamsKLS0tIHp5bWNkNE4vb1BoSUtRdGVVTUdm
        UFJIZHFGSml3Y0FEM2Z5QVJXMmxKZ3cKiDukxRQ7+eg6PQ1vCJXV2uWfaSTv4FDu
        gZgD10I0PJObS1hmAkAV5WxMfnAH+HiW4R+krBGdwLa6CbzulQ4ToQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T21:19:48Z"
  mac: ENC[AES256_GCM,data:RqCOiXRyRlTYwH+GScVhC44LjEbZsRmPONrs7+mPa/Ttn9/3DJalrlnpyq9qzv+H9NCrlFGwgREDFlIRfvywUQVNEiDUEeEfQY+AVQW3FKkNmuoM1Q7RAgNbmpAdIOtzW6THlwxWU0j8tdb5oxthwkJIn4D0mufhn2XdByJYtZk=,iv:2H/FjHuiC1C24TJBUk0bOBbzZF8L1rLxT07+1wwhXQw=,tag:5EquT2F+1nchyeb51JngkQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
