apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
stringData:
  DB_TYPE: ENC[AES256_GCM,data:WDw5QvszhcPDUw==,iv:kpbVKr51w0aVkZRjnbZJUWX/tnfxvsqvEJyTENakIhU=,tag:+I/05vlpgzZuM5YEHrl25g==,type:str]
  DB_POSTGRESDB_DATABASE: ENC[AES256_GCM,data:kkhv,iv:YXqZCRgGEANFt49v34DKYSNjqf6J/f11Y0KYy5BU30I=,tag:n1fektJAOuRlgc3InQX+0w==,type:str]
  DB_POSTGRESDB_HOST: ENC[AES256_GCM,data:2HIcdTTyvPpc/wPJb856dQeZdTMpNZw=,iv:jhF7rbuULkf8X1fTbTlYBRpVncCm85sBwTkD9taZinY=,tag:nyZjc3CdxpXZtfsxg/8RYg==,type:str]
  DB_POSTGRESDB_PORT: ENC[AES256_GCM,data:doE2BQ==,iv:QiT3qqw7Z/kO2TUwUy7ezYLVPxB5Yc0CUHRtRR2DldQ=,tag:98cPhXfam2COMJ+xI/DT1A==,type:str]
  DB_POSTGRESDB_USER: ENC[AES256_GCM,data:GgvV,iv:ayCE2Se2CkwzIIgQY6ceF0nrIxR8lhoeGbl9llnQAF0=,tag:EaYuA8SnzMVO6asro8ML/g==,type:str]
  DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:3wkCucYzbjKiV2E20eH/d4jamPy3AwtcPNzJFCFBIihteB1uArrnOYTSkvjVDfuAulVTIdIkYxN61+kYXjoroQ==,iv:IjfHe3Y1V50tDdBSjrdJjJQCwNSwMEfGrrcR8r2ekWI=,tag:Lvl9vwIBqfdCNSx540NFUg==,type:str]
  DB_POSTGRESDB_POOL_SIZE: ENC[AES256_GCM,data:Kw==,iv:t91u4WvCzRIyx0PKFPvITmTdHHIj/cLOuVIqaiCykTs=,tag:nm5R/c2XuwDDcjzpDQai1A==,type:int]
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:iJL6a4Qp6klPUTYqYaLzeZWd+BINLVDkUZQsTDP4DKAQubKOKFaaoFHGx3NysAjgDqC6cyuPnQkfATDO4O8uSA==,iv:PAKf7RMZjhNq81kmEPzIXNNoM0R/ki2q4efDnxuWEx4=,tag:JcbwDtJN8bTwF3uF7DD47w==,type:str]
  N8N_EXTERNAL_STORAGE_S3_HOST: ENC[AES256_GCM,data:pQuShsnFVODvZfSIwNIbZNYI,iv:bK8vfrWJPfh3bnQ1CnVYAq3IQYNaVtv3rqp3XjgAmwE=,tag:RF1lJGo/6VHRbWbspEUzzQ==,type:str]
  N8N_EXTERNAL_STORAGE_S3_BUCKET_NAME: ENC[AES256_GCM,data:pqI7,iv:1NqYBQQjMF2FFFY0Y/3OBS0fRt1qdPOStAtPxxehHtk=,tag:MroumcMg8DcTJeCnf1jdlA==,type:str]
  N8N_EXTERNAL_STORAGE_S3_BUCKET_REGION: ENC[AES256_GCM,data:MLuM/TrtnexK,iv:iagIcNRyLsO+XTGGNkNwWgMGOCxL0TcyRuzONrhna1U=,tag:Hjm+nS5XQWZGb1QKfU5KIg==,type:str]
  N8N_EXTERNAL_STORAGE_S3_ACCESS_KEY: ENC[AES256_GCM,data:9T46,iv:QZ5L96Hnu1hOBycGb6jGgTEGtMJfoea0Jip2fPJ7nG0=,tag:uXsntfri0xVGikFfFEFsiA==,type:str]
  N8N_EXTERNAL_STORAGE_S3_ACCESS_SECRET: ENC[AES256_GCM,data:2X3UxOpqPng9,iv:eFOq3pX7ffV+Piiams+Z29qRFmo58yYwyf6n89A4Ce8=,tag:g07vsSF4hTES4uy22QGjlg==,type:str]
  N8N_RUNNERS_AUTH_TOKEN: ENC[AES256_GCM,data:BnC/ki8XRnWpq9IjK9WXeVOnplvYt1NWOlO4UZ7SLw27jB56mhsKmwfFdqnGw6iaTR+JF17AtL8yA5Bo6fi5sA==,iv:AtIUhD+LsIXlFKlCTdg6dWoPgH3V8FnN5x8mvPAYkZk=,tag:+rxpSOdPKTHaMeuhiSxRgg==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:NkOR,iv:gcYxgn4MSGfahqgF0N5IK9J85YpfnvZNRL+DM6nHcO4=,tag:yZgwHhGdyzQZNPsoHeW74Q==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:ahXYV/OOaTZaWJ8NnT7XsXdhzsHwPXjX3U6iMZXQl5UB7ihmkogZJQc=,iv:Wfr0Vqc8LGdUxWnIGDXrkdWfY1O/I9zCaGDc/frtIY4=,tag:hakgVExfdtVYZKwC8JONlw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:d0aK,iv:Z2ED1EfVD6vmhjPCMSlsAMm/bEeuecayHJqtH2+sbXA=,tag:DOnLkO/2glnOstTR3Sxhhw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:h0VjhpDwHDF+mARhC68qAd0vsoskw10Ngsz/02usZQ6LWtITJSk8W0YrZFoggECuVk2aWEWYrpwcNqxWYFfFHQ==,iv:1FCwHr/zH2dlDrL9tsAsFobnAFb75Rmsl7ft6w1cyXM=,tag:xmIHImtaXdNZFPCDLddUvw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:P+fzPzz3+UZSxdjk4G4=,iv:29m0t4r10izB0ryl5intMMpTZVw0MITdgTGyuYyrdj8=,tag:OGv4+l3E1AON2ZwMs57ZYw==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:6eiiJ2GNuRs=,iv:OezfXQC4VdKKkcCtRNy5jQ9u3uM5I9++FVF5NY+KltA=,tag:6v9yil3OcKER0jeV5c9lwA==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdmY2UCtTNGgydXJac0hL
        aGNKbjIrZ21Nck0yOFN2Uk8zN1Y0OWVSRFVjCkwyMVQ1UDV0ZDM5emlGa3N5RVlF
        aksrdzlkUHNONjJuamtKdGkwN2JpSm8KLS0tIEJ0blRmRmdXbmJTZDI5TThYT0Mr
        aVNZdHZOV2FzWHAwMHlqQTBXdFk3Z0EK7XXpIXLn+t7h75AnY838uuZau/Xh18X5
        txr6hjHnK5F1R8+jb3mDD1IUJB7K/JAkyy/Pbmg/qWkFhCEaaMwfMw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T19:47:52Z"
  mac: ENC[AES256_GCM,data:Y6QpT+VsjSShfm8EAd1gjthtfB5AeJH5JCESETdwfUNwSB80TayHwiUOSqXQ+Bow3QLyE3P7jT9LTaCXmbX3IwL57uYdXSdY0wEVE2wpG/cKIlBNzmDhE+KlGsRxYjKAQCIzb1XcpDgYoKFTT5QNxoemM8gLdcGFn34gTSzFA7c=,iv:/hwOrDfTwljiQYGl566WLexAB7hg6anrpyNfiZS9WZE=,tag:on1Tu18D8opX029tN2J2cQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
