apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
stringData:
  DB_TYPE: ENC[AES256_GCM,data:eBFIsvZayoUa5g==,iv:ZkHv6o9QCLBdPvmSaXVLtqbZUjWUfQfKYkz4Rxt4Ddw=,tag:qjgtraKm7am8Bhx13c5PLQ==,type:str]
  DB_POSTGRESDB_DATABASE: ENC[AES256_GCM,data:XXZW,iv:oPHZtLtytTdE/eY6+MyoncKV73G/g/R3OdJ3Q+AV7cE=,tag:RVIsAE6eor1wUWUXYflB/w==,type:str]
  DB_POSTGRESDB_HOST: ENC[AES256_GCM,data:Xq84WbSD7GKGBNwIWgzVobWh+ekHVxI=,iv:Bdj/8+2/9VDFCthyQ52RE0AnRUwid4NIrGt68F55A/A=,tag:yCejbjhkaTEdpbxt0+8sWg==,type:str]
  DB_POSTGRESDB_PORT: ENC[AES256_GCM,data:icFUiQ==,iv:r9KLcge8cHT57mtELn0C0GEgx5i5jYn4dSruqro/FIM=,tag:4BvEq1Dc/IwFqWvJMadx5w==,type:str]
  DB_POSTGRESDB_USER: ENC[AES256_GCM,data:aiPI,iv:IuzM2xabxoEjugjQce6uINZ/nEHArzV8mRmGYBK7BmU=,tag:IpPlINphfUr9a67GDf7yPg==,type:str]
  DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:wHk7zmZyk+Sn0IoXuu/G6K6x0EbgDByMLnzSMVvDmAYD3FWw2PeqQ+hkTtGHt4lovAWmAA9eGUS7BpYgpe+yGw==,iv:4/8jlbm+d6n2MXL+lWteoKOsD8DEh+x9oGezke5m5+w=,tag:4cxC92uFeBQcGJcT8enCWA==,type:str]
  DB_POSTGRESDB_POOL_SIZE: ENC[AES256_GCM,data:9g==,iv:BZXzI8cOw6D3zWy/tj0xkh1Sk98g4adwo/z2h/HwL1w=,tag:gte83U/EFCS/2sW3CGBQhQ==,type:str]
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:iDlMbPuxU8HMLPxRFhKji4hXrCCfSjV2xBwlyIN4OwKkl4ISViPG+IGuQHHWfBBOQWrPNVr3P2MbrvdPsv3BRg==,iv:/I/0p7tKIAnluBbI1VKfjZMGlR1IRuSQUdXyDi/d6Lk=,tag:utL1C6hUu8Ox0xK8xzf2Eg==,type:str]
  N8N_EXTERNAL_STORAGE_S3_HOST: ENC[AES256_GCM,data:VY4xv4g8aDQ8wExfkEIwN+ow,iv:/+RPDeUchhZ9HGUKaRhpSXLchIqGMnuauumZBCOXSAc=,tag:X888UxM6ofEUzurlsR437g==,type:str]
  N8N_EXTERNAL_STORAGE_S3_BUCKET_NAME: ENC[AES256_GCM,data:aLq1,iv:RAJ+KL689S23UVkHpYt7I3l8e4mNuzKPIcV+kTxTNec=,tag:MS9q4A6R2/miq1sbZA9ydw==,type:str]
  N8N_EXTERNAL_STORAGE_S3_BUCKET_REGION: ENC[AES256_GCM,data:SQpfnCriQQs0,iv:4NEyMLBJc7aByW7Z3gdf4sRe2vFkVv7EF+HGABcg7SQ=,tag:w8IlwsNoy/ULZNgAU74WuQ==,type:str]
  N8N_EXTERNAL_STORAGE_S3_ACCESS_KEY: ENC[AES256_GCM,data:l0PS,iv:8eKoIxexWTUuDtJbLnxCKuxJd4CjZBUq63o+Z6NiKLw=,tag:d5sqDzZlOWUhlEfaXSh07A==,type:str]
  N8N_EXTERNAL_STORAGE_S3_ACCESS_SECRET: ENC[AES256_GCM,data:zB0pGJldtEhs,iv:3/Y9dvGLfwmTWPQuSzrO0z7dBx6E7jqgfINGeHhbUvE=,tag:E+lgL+UxR1nqVxiea3UCcA==,type:str]
  N8N_RUNNERS_AUTH_TOKEN: ENC[AES256_GCM,data:8gNmLLjsWYEdw6m01t/oJ1akrfpSXe3BCfU9v3UyCjVbiGev4o1NkCtwL0BlBLJGfaUcyd4xs+UlTPUh79AEZQ==,iv:RHrULUYbG3uMYgAYkEfvTvvgXJnNu4dbHYyY8fcDKEU=,tag:m7Ra/F8ypq05YtibctqwTQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:DkeD,iv:aodDD9I66ncwnOpqoMxZLC3dGiuB+WatdkE/cByk5Ug=,tag:8mtZaazFH3OEFPkWNsnm5Q==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:NSz7lkL94TocM0zHL9DR/gABTc6JwtjdQMOz4ey2OUn0ksWzLEG774Y=,iv:2QKESOa5IDewLTBaP8lS7rqPjRbXKu6D1SmThV0x0hw=,tag:8FntBHmE8I+vGr6xUkXj3Q==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:mqbM,iv:cfbGVnOb1Iag8DlORWQLEoUpctjHN7JUS+g45vwqDBI=,tag:joGXb1xdBO/B0L9TtU7nRg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:7aLRw7WJS9SUlIGlGWTALU4Bv71Ek+DYzQqcic16cizSsn94jQetZxeNOAtEBXAkzmESxI8NYMzGHuZvU8wrmw==,iv:ZaRqUTuhJt7fxVM8scZRoZjfSKC0Bmf7WjmnHkzvORI=,tag:+1zpyhQNJ1+Q9U6Yioz2Ig==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:GxFppF0oduOB3+3eDl4=,iv:fW9gYiYU9sTnXwkvAdTQRIDAnLediDv93/iUfoeaUtM=,tag:tsgkTXbVcGKHWRWVXX8rTQ==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:fMcvPQEhVbY=,iv:wfwX0qvEu80B3hgpvCexoWmFgPFwOF4FssF18xSCBUQ=,tag:Y2KEf2Wmq6DsdMLfUTlNEg==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZll3NTFMTEo2cTdrWllP
        cTduQmtwR3F1OHV4cHdnU2JHd1ZwOXVXc2pZCklUOVk4OGxkWUVPUmxJc2VvRkZC
        c2h2RFlkMWlwVlRXb1ROWldwUUt0WmsKLS0tIDViWWFNZFZEYWd3TDZkNDY5ZGt2
        OE1BclhyVVZXS0J0N2J5cUdSMWlWZncKmHWvC+8p9aatLQnAyjB3hZXD9ZfA/Ygf
        hvNNWVjTDLMZay81bFaEJ76kAzVLTwqUO172caArX5DyQs2YxPRewg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T19:54:28Z"
  mac: ENC[AES256_GCM,data:fKQiVbwJJYDlD47RQmd+biyQYD+9sWP8AXbR6FrTZ5xEHe9Y7ZcGd0VLhRjLCHATotps8oe7OxHeAXL3AB5K9U0YwKNV9f4N+aTnRhvU2ctRobejiYqtZIu23htyrZG0//LWtM1x4BKNkb/HtQFjSZlLts/RqdnG2X3j9IaO0kg=,iv:d/COBfi30+dPwzXIuxKcOvhDqLWDbIel4EK9NTA/ENM=,tag:7FySQ55EF8AjCSX8cHyP8w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
