apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
stringData:
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:gdXPSlHvgm1C5V1xdHMvF6J6Nk4Mw18+HotIB8WsHdQFf6hREsdJBbdIVZT2h8GT/R85QQjvkRN9jTr/ifHwVicjcVAjzDV44SFoES5EO1c/4r6HHJOR1GUuidktzFPj/MrOGwBfMTlC+UNWjkZnWGz+irww6p0V,iv:Z7dp9Toujmiv9GDtPsVnjUF3IZ/tCmdbJdqS8yn7BPs=,tag:bxd54VVLuVUZRGBI/1AU4w==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTzlOaktEUGhSRi9WaWYy
        MC9UNHRNSGRZcURWS244Sldpak51TzNJaWg4CnFwZGV1aTdTYlRmWmRHNzZNNnZa
        OXlBWnRyMzdDTXoySjlSYTNMazliVHMKLS0tIG9VN09ZUHlSbXhEKzkwTUszRjhL
        SlVXdEk1czkrNTNDbnh4L3RKOWEvMUEKxtzFdzbdopdgCSyhqtWFwO/5x/pQrnfZ
        LB+gsibotyRRH8S51M9bKnLLTWcAs4zHCdO3y5XV3HAGzi9IC6DzuQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T15:18:48Z"
  mac: ENC[AES256_GCM,data:ZGZ/lJWJgPOVeC0UvLaepOlkdqRcWXpZsDj0O4Yrqm4T0JN+yOFO57yQ3w57+bTN6FYEHbccuo0pBQnmaUMI6gXZEzPwPA7ZUxOCchT1l3TWtlT2hEjJ9vrEm4czqWOB+cCvZpVC4xctDM1d0MlupwTbuOg0Dhh4QQqkkjFkIMg=,iv:ItUGKPRyTp8v9b2m2I2uwk6OTHZA2cPh+gQoEi/ffJc=,tag:RnHx9RLxeLJ0KCsgjyc27A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
