apiVersion: v1
kind: Secret
metadata:
  name: linkwarden-secrets
stringData:
  SPACES_KEY: ENC[AES256_GCM,data:jvipysIvzawNRg==,iv:yL59ABcpjPKRDNvP3HVwqcjtZwTSvG0k2RibitTvMAs=,tag:quyiGB6B/vvVk4sOMA0S8A==,type:str]
  SPACES_SECRET: ENC[AES256_GCM,data:P16v/cuDttOmOdvd6A==,iv:u9FzebNHPW/M63yC6Z2+TvKIe3DPu+U6ZmcBsa33gas=,tag:uaeEXcWoSdDxvqiM7wZHSA==,type:str]
  SPACES_ENDPOINT: ENC[AES256_GCM,data:4AiawqGS3SzPx4PeZvMhmRXE,iv:ob2IdU8WUdWQTFhZlv+Ea8aSlCx5NWJzjZ5VX8zdtFM=,tag:cvslbI2oLYGObVj8zYdcig==,type:str]
  SPACES_BUCKET_NAME: ENC[AES256_GCM,data:W+QuiQAiFmpmMA==,iv:8biw/51cfY2vupEVwPkPzK1KNCRJthoohQ1S+mOzbV8=,tag:p0441jeV9FLNpT1gjbq+9A==,type:str]
  SPACES_REGOIN: ENC[AES256_GCM,data:MM2a7AImcuAF,iv:Y6JSRyDZWLp+YYflZ+jMqx5gueG4u5pdDUpFGW96uU0=,tag:dCiqdrWA0gTJw/afSRwm5Q==,type:str]
  NEXTAUTH_SECRET: ENC[AES256_GCM,data:Smv9mchgXhz2HCh0O0CjszA38YzfLrLxspeXjbAduyQ1Djzn47hP16fwrlY=,iv:zuW9ztd7FROVHfP769rQIx354TD7+r16mUn1yQEYgAI=,tag:Pnoj0qCk+AQnCpRgSBP63g==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:twAalnDkUNI67yUVCF0x2CQ9pT0l0Rpe6fEThjyCSLYvUK0N03EKGpkll4Q0SqKZhKowNQbpuvUtgmRkn9iw/Bt/yy4NJLDGgrDFvyyXt/spnMTU6pT3drau4zD/06X6nt/9JtTf3l2gG20osb4hYxfX2bduHtAxTo40XRmlUQs=,iv:mzBcmSyLy6xy0F0Jnx6LrhPt1IBPz8tErJaF5XWVUlk=,tag:9F0SraQyxEWOWv/cAeQWWw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:OMQHzy4/WUSqjQ==,iv:9jO/eAL7fv6pukFvMT8k+6Dg00S2CIql5kOs9/KDejQ=,tag:CVM43nenxYDX48E+ZwvQ+A==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:EXgj6fAPsVYZbnQGWOv8i00C9jK74LfrkkIq7VBKUJEBpJb+PMtloGw=,iv:aChI4xrKceec0RvEGYFHtlAgQ6Iovq4k/Q0mC2w6EtE=,tag:iDcR/O10BJyRnUVqQACceg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:DXPDlf9tBILgHw==,iv:O2Lt5SHfI1UgT5lt++s0gUs1JlDn6ol+y5mKYffx4Vg=,tag:vJfzwTG4mHB4iZwvJIBYHA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:M2N83XzS+OB6faMaZRJU/Q5f1nHMSKEKC4oC8mbyCjNiWYW0JHaID06au3IIuPpI+7IXufolXHg7GaSWUFPlpA==,iv:sGcR7//qN8QKlLacdyq7qXSVtGCcNL+2wBM3t4V7tPM=,tag:JAVUiTF8/keO/Tsv/gBIFg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:gIiCA9cN9HAUblQZ/eI=,iv:isFfY3KX4q1OAc4KR7A8W7430an3mgutLHX9yKTbngI=,tag:cDabiOlFaQyN2ngYnnHNAQ==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:AkrGy6esnyQ=,iv:/ljzoFAiuFl5sU7aFzdOZzAeeErlL2Y6RtBcmZF0gR8=,tag:DFqJFMmtEpe9N60olURunw==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNGZ6L3kxTGdDaHl5c2Rl
        d0RMMCt4OFl0K2FiK2VEdlVBUmlKYjVVMWpVCnFFclFBWlJOTGdpZUZQOWlzRno2
        cEphV0dOc2MxRitmeUw5YjhNMzMxcmsKLS0tIGY3bW8yM3NOTmhVcWI3Nmo2OVFB
        aS8zcGJzMTFGd3gwazNnVVR5c3VtM0UKSmM3Lu6lVg9I/CJN2F8/5PP7Z+uPMb9Q
        2sf/l7iYbG+Ex61nGMLu1LDDhay/YKNEbwyKShURJhRankVvZlGX8g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-16T15:28:06Z"
  mac: ENC[AES256_GCM,data:5AhnnHu5jxBhx3SbyxQvP5+nZxJByqo5TgmiTWT9sfTHqPxknOLsE7U6bdNlPqeYDP7rMorKvkJY91H9IQdd/KWjOnEkyPN7/1y5LlM03Na3rgdoGT59BnI+8AbDZKxaLu+45/Myzzi5i41hZT3Cuse/dQ/XIgtw8v5eYqIeMOc=,iv:/CtaHhxU8tDnSNwvjoVluK1ezeKj1mFwan4OF4BKXvM=,tag:Exp8kx1uiSmgp9rba8rBfA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
