apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:1Urfu4CbhQ==,iv:7uIGIJuRt9dXnGV+OA4CQH+AoK0Ld9A+fkRPPP04Kt0=,tag:v+m9SLP18IEOPvNJyVw9XA==,type:str]
  GLOBAL_SMTP_USERNAME: ENC[AES256_GCM,data:GuJLyvyuHZWUaVacykY=,iv:EEOKN2TWK2MxwEUUghx6NSjt0Xx9U3f7zhnOyT+6pzk=,tag:1y3NfOsi/GKbk//aLY1m1Q==,type:str]
  GLOBAL_SMTP_PASSWORD: ENC[AES256_GCM,data:II+wcc6++zfqWhJSpUdz+Q==,iv:bVXHR4hqMsxHwMZ9i41uR3LOUJ9HjYttUOw1cWDUyy4=,tag:eYHWkyqoV2yVyAYV9Lvu1g==,type:str]
  GLOBAL_SMTP_PORT: ENC[AES256_GCM,data:pt6q,iv:+bgF6g/I0XQM9PGd66Trn23Nw7GOmAny7MTdujtvmVY=,tag:i0QdtgPV09XWiUby2uT61A==,type:str]
  GLOBAL_SMTP_HOST: ENC[AES256_GCM,data:f2B8qeQuDSpj6D7x2Iyvx7DU,iv:gnpw1wmmG58vQ7VnzxQW3Vn/3nIkNubzvqkYzCSqqDc=,tag:vTmetZP/eCNP9VV5f6IhAw==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSitZRC9NdUN0dUFmaTNH
        RG1FM0JWb1ZrTllmR3ZVTGIyTXAycFoyOFU0CnRpWTZEOHljdFRPYks5MGl2b0pI
        YklSQVNCUFZrYWIxaGg4cTI3Q0RnYjgKLS0tIENvakJvMTNkK1RlZWJ5WU9WUWlh
        aHlUYlBXZ3k3Wmd0TzRPaGZ2Q1c4K2MK1QHlfxDdWbNdq7ztC9GIoIOtt7jyvFf/
        EvkBEt4zaPHFq9ComrlxJSiNZce/AE0NZseglci++V8MDox2iwRssQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T15:37:24Z"
  mac: ENC[AES256_GCM,data:7ZgeBgr7nK9OGv8NYTkAQtod5MPgOY53Fr08eUg5DbwBHmRL/oKDVXELODZNttI3jhtM/wPXNZAFRA4VwFtA47xflc09sVtc19b3JGfFOcp8ppQOTbAkZKiaJcvdxq0VZM/YVw/NdpXtTVbMNLx+OEI5pIIrB+k72QeIRIhWM1s=,iv:bWz/UpMGN7Q9NfJ35D8ag+gKYeWtbj4QA46+aFUpg38=,tag:XYNXtu+gp7RCsIMfwfT3eQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
