apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ATHaeVkvgQ==,iv:A8lmwVLLz201sJRUiWyvWMGCkLURtpnzl8FU+bmxzXA=,tag:zg5i4B0w6gOOHEe/+KLCbg==,type:str]
  GLOBAL_SMTP_USERNAME: ENC[AES256_GCM,data:XZp8wY6/Dzf4G43GMXA=,iv:5E+q6fjHMBGFGHfbiKf/C1xzH9KGilf97rh9VbiwuWo=,tag:vkBvsR8nZ7pmjx2LKnSPtw==,type:str]
  GLOBAL_SMTP_PASSWORD: ENC[AES256_GCM,data:M8eiSxRbKKKFDeaytL6fUQ==,iv:IsBftDjERn0d7p0P+qyZzicc/XSp0KJ2Isq0QSkP65Q=,tag:DIENT6pb1+d3RaDMRMVgGw==,type:str]
  GLOBAL_SMTP_PORT: ENC[AES256_GCM,data:q3un,iv:WeUIVP33qdRQnbVGguMCCbbk4MF9aUUEdSH+/ch6Exc=,tag:hq0wiVbssrgOjC9wvQVwJw==,type:str]
  GLOBAL_SMTP_HOST: ENC[AES256_GCM,data:7P22xpkSyygrg2zC1+YJ15z3,iv:/VDcipkEtyqOmZtHAAuQ1KsmsFCg7XYjiQz125MHepc=,tag:2Qlv0+XLJQMvNb8YnfG52w==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbHFPQXdHOXptdVhEMDhN
        VGFzYWhRQXM0RWI3Z0pLeUQ2ZzFSTmlCSWljClRlY2RrMDlwRGxhdUk0NU5TQTRC
        MldsRUtaKzZlNDVKZzh5cWNIa0FFb2sKLS0tIEh6ZnZrTEVteFZCc0xiRHZXaWNU
        WjdQRWNrVWc4TXRkak8rNW5DWGxkS2MKONGxyIayLqOwdXJi+7xIS7qcIvhZpVqZ
        BIrUXgzN5QDWgwXvQmMz9IsJIVOnVouvLnVoskTdp54GZDd0KAwhsQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-16T15:27:58Z"
  mac: ENC[AES256_GCM,data:7VU8tg1UhpoMOfwVXEJJT5jZO9ZN87HH5YZIuGNpB2j2wd9mrP4q5TlcLNMO9HJY1upMK3ngOE5dTKlla/3asbYTaSQQDmQX+XfqLdUozlvoR9UfsNCwUERsmJm3vdZg+CsIiUsnw0C2Xq0d2ZTmdRHCntsRQHXq20dZ1DOfVGM=,iv:KonTSEEqixdKEZR1FlcqmMSpab4gxjw8xDGpPC7i2xA=,tag:C3eUPKKeKYulyM30RczWmw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
