---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8tz
spec:
  chartRef:
    kind: OCIRepository
    name: k8tz
  interval: 1h
  values:
    createNamespace: false
    timezone: America/New_York
    cronJobTimeZone: true
    namespace: null
