---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./alertmanagerconfig.yaml
  - ./prometheusrule-infrastructure.yaml
  - ./prometheusrule-security.yaml
  - ./secret.sops.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  # - ./scrapeconfig.yaml
