apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
stringData:
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:ixXzF4EvXUhwQY1WDDlzLCXm3YRtFB6ZLr0NwDZrnPrrqhhTudKilozeotVgRJCYWD7fJd7e8JXj+s1wnO4EnTe8weRQzsNuiDFklcBQXL4Mbaq/8dTdiwgsPLoH4DuPCgK0K6jknTYOz9awfeSyn4cPRwht1+WP,iv:GmoXoQ09IrJa1ztB+/9RU+ZYMfBfrNbz3Y+2vK909Mg=,tag:9RsK/1ckubuSbTnq52zX3w==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VytZRXNEbkdEdGROVExm
        cVd4Nmx3Y2drcFdwYlNBdmJPcXkxNXdodkU4CktIM3dEWEwyOU0vc3dpSHBJN1pk
        S3JwaVI5QWZ5ZHFHUzhEQVBzVmx0YncKLS0tIEppa2hLeERKMm13cExUVkM3SXZI
        QjhZMzZiS3pHY0wyekpZVCsyMWtXeVUK7QoLCEow06Xw9r2B27XGnbhh47lGgBYj
        PkxdO1+BbiPos/DzWGxrMrbxgl6frp+VyTPi9mKzzatS7YG1VqAsYg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T03:47:04Z"
  mac: ENC[AES256_GCM,data:hUx+N4a7JPqoQfZl6VWUZr41/4MsZBfz5Pqo3UGNffA7EAxqcWQWEn7b1JhjCy3m5CmT5+Vb8tqPqDN3T44jGVKtLem1s3QNgn6Ur1RrTfdLvSVz4eYv/F771mzci6XTqaqw7KgscOlSd95By4i3Pg6EFE8H7ulV8FzbvavGdVM=,iv:bu4Na48n1gIQy+GRUVwhzns6VzsF73O2HYLM0dkYoiU=,tag:n31wcEFAL5nsxsQ9u3IE4g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
