---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: traefik-dashboard
  namespace: network
spec:
  parentRefs:
    - name: traefik
      namespace: network
      sectionName: websecure
  hostnames:
    - dash.68cc.io
  rules:
    - backendRefs:
        - name: traefik
          port: 9000
