---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-to-https-redirect
  namespace: network
spec:
  hostnames:
    - flux-webhook.68cc.io
    - grafana.68cc.io
    - mcp.68cc.io
  parentRefs:
    - name: traefik
      namespace: network
      sectionName: web
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
