# Auth0 OIDC Configuration Secrets
# This file contains sensitive credentials for Auth0 authentication
# Encrypted with SOPS using age key
apiVersion: v1
kind: Secret
metadata:
  name: traefik-secrets
  namespace: network
type: Opaque
stringData:
  #ENC[AES256_GCM,data:DcbKYxW2XvIkIkCmB4NTTtnNlJmYE73GBwlsvx3s,iv:qEepwyQU7VIO5AI9+NvOoHXxMaHhMNE732vdy9GWHAo=,tag:JOC1JMvhusNbebm1YZp/tA==,type:comment]
  #ENC[AES256_GCM,data:iTsp9ZDv49airptqJzBhGsoR3bOvTi7CSNuvWbVocQD0/ste56g=,iv:LxEL1WaxqvQM4onANanDq1I5PGJNZqN9SqkI7XGa3bQ=,tag:Qn5W2Yk+mkjx5rVLUgt/eg==,type:comment]
  AUTH0_CLIENT_ID: ENC[AES256_GCM,data:Jn2LMBPcCXscwlexLZNiKkUfAmjCX71bgUb6VNVhuGU=,iv:McCV3WNKEeGwLXC9zAB7EHqdzN2OXgDHH3cPVBucdzg=,tag:zhiIEM9k0kdkQTEuwRZLpQ==,type:str]
  #ENC[AES256_GCM,data:78rAQFCT4kT1qulFv5dOno7AFaP/yvNwal9luMV4eAWTVRo=,iv:qD+d7cQxmHWvC85ff+XsVxxy0uBAJyGExpCZGQ13f60=,tag:cPDwI0SxOx2b6/mu7G2vEA==,type:comment]
  #ENC[AES256_GCM,data:5sLGGbvdKVOd7p3CujtL297fzlseC01gnD0ncQ6JGE2Twt+JWuuK9Km0q8aVw1Icax8yxwaPrEZF7QmhVlu/7JA5+kOzGA1Oog3+HjPE6M3jeFRUhCQ=,iv:znDikU26T+aZEpQW5f74z6x00UOdpGFHOTPjPCFgkFU=,tag:RUlfwu5PEpD3WeQwzs1YFQ==,type:comment]
  #ENC[AES256_GCM,data:01tA3eB3i8u7HrKqry9Uv+KFcrbukRO0TzEZmnxnftfkTWsclSqgVzvxQ3dn3XXVpl1qqhXV+1qS5bY+QutMsHFORe8qDmGZceLX0idZ,iv:vYF8o+W0QZqdMpwry/+wN22OH+fh7gKRvePyKZG4uuc=,tag:YFSEzg5lv/kyRXWAH3w5Bg==,type:comment]
  AUTH0_CLIENT_SECRET: ENC[AES256_GCM,data:gw1lCNfT8mgSbpUsrOK92N3UIpMn1y5gOL388lpjBNUCGg==,iv:NMBE61vlW+2R9BeW+LCIqyOYkPrrrYKET06jcbM5+/Y=,tag:QncFdnq/nkXr5lloRwG3EA==,type:str]
  #ENC[AES256_GCM,data:J+hsoL99JfKwILk1a4TDCU7DwnCncDdih6mOj1N4DtUHDUrBE842G406glCaAC5fuJY=,iv:2y1iT6b1lTNN00H2WrCLFISEmSukx2aNmG9lhOeadXc=,tag:6kAQjZXGbnAjUcxedBXavA==,type:comment]
  #ENC[AES256_GCM,data:KGh1Rm3NgbmWjUWcibdEXSBtJ9M4Wastp5j3thecrVigcmzON6OpSpotw6An,iv:Y5AIyyX7lBpTVZi+g8Cv4DMoo1eeFddiSugrFEYmuDQ=,tag:IxRCpFw4RinWh3i/QeCFkg==,type:comment]
  SESSION_ENCRYPTION_KEY: ENC[AES256_GCM,data:+XNazIRRFNGoymzZrqeVqwDRm+jK1w/80t5ap8mnW8Lo4vXUrbkmQezlkJQ=,iv:tJ/JJJLRAi4xMU1RAmYzSY5MvKUz9TLO5CTuQWny+DM=,tag:8ri5V0cEN8uVr4zeupQViw==,type:str]
  #ENC[AES256_GCM,data:8R63H1veki0nJe3pB5o3e6CZj5k=,iv:ow2FoaZpQZwP2KVfse5yJNul3fWox23Oe+J5rgOlSWc=,tag:8fakjf0pEnNBfAjXJRo/bQ==,type:comment]
  AUTH0_DOMAIN: ENC[AES256_GCM,data:ZKMHRQEcT6Pw7QuBMHqHhaAldA==,iv:XFV1+7rqcPY1mgDwTprwMwPfLkAgUQ4wpg5k9QXPH/s=,tag:/V23jgOlXgY5gtpZEK7qHQ==,type:str]
  #ENC[AES256_GCM,data:QXo7Jv+jFSwpnOp6PWnd1d4u6EPoEWS/tv/NLLRYNcM=,iv:XwkA/ACwJK9AJwm4zomPayKy7JWhOE3yfG9r7HT8D3w=,tag:LQVYI0hAxz8SQ+aiX3hEnw==,type:comment]
  PROVIDER_URL: ENC[AES256_GCM,data:b3OB9sclZ5xH10b8ATdFKwYaWJknlGyG50Er,iv:3sDJflKAC8/xspoznRz4P3BtBmaUpA2RDNbJV5F6Ny8=,tag:2o6GcBR1mBJhHcPYNbOgBg==,type:str]
  CROWDSEC_BOUNCER_KEY: ENC[AES256_GCM,data:/znMNwWS4AuQ84S+NykHuIXhwJ3ZB9B3eJEgX51IOj1yFDH9NzTEZ3vMGnUH9hhTzqdcNF71805Fc56XWT6T1w==,iv:/nCpCQJi+W74K/S5yaUHwOAUOtYGLt0XCK80vL/L7cI=,tag:U2E/JWS0cw6kR3Y8rxP8Rw==,type:str]
  CROWDSEC_LAPI_KEY_B64: ENC[AES256_GCM,data:trhMoRE/CLpoQ6cWzp/iJn6SQtYreUrbyFEUOHa/NY8n0L14EfqmgESGsQKSkDklmc26F9UfqShGzg1PbTzft+dptHT62R1C8GLVWKpNhPf7s67U+w71cQ==,iv:ub4go2i/Lc62+KqLk11wdkYKnUHrN0DAeNSCSQc2qeM=,tag:PGgcoGvLxgtOMIO25pVFMA==,type:str]
  CROWDSEC_LAPI_KEY: ENC[AES256_GCM,data:PAcOnB+40ziPg0T6oqbCuoN1g/dANv96vfqvZOPrctWQxDoAV7fwJOK5bjzZK2WKOMtrTupqlyeBQJMUIRiZAw==,iv:CLrBlGMF9o5CkwE2pUF9HRqwa04XdFzAAwVrdiq79nw=,tag:B8KY2GryNmGd3P6MhUeg6w==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudFliWTl5bWJHWkpYemt5
        N1Y4bjJrODRKOHlEVVdjTzZmeWd6aW1YWnhvCkQ2dXdRYWJMa01HTXgvaTVkNUM1
        UXcwSHdoWURiU01zaC9LWll2QnhjT1kKLS0tIGtOaTMrTnRNRzBRai9Odlp0SFc4
        cHNuTGRyZjlYZWtyNlBPVXN2SXJaYVEKQ1sCIHtFLmBcdCp/VdD18NkEf3J8eh13
        GpyGDMLN7szGUAQxJbSA+6yoQ7MRYHsuhkIKoDAPGwYmhgMeYbZozw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-23T16:23:07Z"
  mac: ENC[AES256_GCM,data:A+jqn7ielrBvK6F/+SSlA3CC9JFSnmQItfP/dClqNmBd5+vTrEJPTfijkhz8eVV2itKjwwB1okG4DEZPUue4Aqn1uAkkqRbmjndWxWsKI12HZwiFm1iTcp07tMpO+ENuv6oC4nppb2JQ1OJdvMlT2PhEl6WtDo7LKEEEoNMimR4=,iv:fa0+JuqqDhiSrvw5G9hW4L87oTf/y5fBUv8wF6BWg5Q=,tag:RQnDUvYn5qY+u+RAX2kYOg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
