# Auth0 OIDC Configuration Secrets
# This file contains sensitive credentials for Auth0 authentication
# Encrypted with SOPS using age key
apiVersion: v1
kind: Secret
metadata:
  name: traefik-secrets
  namespace: network
type: Opaque
stringData:
  #ENC[AES256_GCM,data:9EpaQe1TIBaSP6TTQ1sfQNigRmbo70jGAUNpoSW1,iv:pGP0qsj7zKRU0HxHkeq+wRrNabnkEwcrO8NrNtf7YEo=,tag:f7vr6BDVwi+SRV/Di+on+g==,type:comment]
  #ENC[AES256_GCM,data:EguW2rKf2eOy5MPmj4ezojF7sa+pZU+5QEshvXopJy6hJtmsLeA=,iv:Y9kZbYKzsyFzmBW7OtRH48oxvR1hp65wQraNJRsApQM=,tag:J24vpcIPYFZ4qgsCfOZYXA==,type:comment]
  AUTH0_CLIENT_ID: ENC[AES256_GCM,data:D9plt+fGGNXyxrhdKKmHfYK/cASH6vuJjNYon+lkcaY=,iv:x87n3GsHCNFic+pHJmqw+TmqhWq0l2bqyaFgick2IgE=,tag:4D2QvfH5ra5gLEf46t7C/A==,type:str]
  #ENC[AES256_GCM,data:7DOdw5s3DC7uJlUC9321vjP9ihuOUuOa7YPEJOu5sNHQEjw=,iv:qp+qhDUGGq9NF+K3hkesRpw3JXqE8rOw/GMy/n/FhvI=,tag:bWdXvG26HP1rtHo2hq3yjQ==,type:comment]
  #ENC[AES256_GCM,data:T2QNAsbrX7pFR4+MSw4Sl2KvMH/gZqqoG7gWKCEnsIkeGnKSGEP+inADOjnqEebWkDSmTGvxPaKD2ch46csHYykWUQRUENrZY+qytmkwDJ7s6u1OD+Y=,iv:DtOakxVY6TvannhglNca/7SF7rCU4p/Hl9allgd7j8o=,tag:AUeYQ4JsnJ28DupizZB7eg==,type:comment]
  #ENC[AES256_GCM,data:GmWnRhHPTkKEcFisFOB/HCurGBputkVmBF2AKDvGMDUE/quxtfdbm9CHQu9D+qebalZ1XvoqpExkmE3G3cNEJKoSURsGYolEgpPT0bkk,iv:z1GoQZcZ2kNGaw85fEC3BjZpiSsiRNsv5R0llxKMSLk=,tag:bBtqrUmhUpBfBntPl39Lsw==,type:comment]
  AUTH0_CLIENT_SECRET: ENC[AES256_GCM,data:F4ioDwL40BRe56hNDwZhr1q9Bj/E/uUnF0EFKRVHyAmReQ==,iv:ecq9JAbFVixZY40tBehsAOOowXDCcb3n5YITOhUiPew=,tag:Fsl6pREk+zPeCwQsxa4TTg==,type:str]
  #ENC[AES256_GCM,data:rWkFysN2sZK3N1brVd4bRVcxPEfK2HiOPg2GNSnR8ec4C52Fw0kvZOkHiIFaq55ZJ44=,iv:SMHSdUpzC3XXKaDx9bOaqXdDxPxiLMK80jc38Fd1Akg=,tag:fBH4oVtw7xWxHFcn2pnn9g==,type:comment]
  #ENC[AES256_GCM,data:QHXZ25sZGxNV6EBu5Hk4gWtNuid4bRtMRiNvcKla2lbCq6dnTFKGR8vpAEsD,iv:Gw6sguVu61WPSTlWXKTfq30LQHIV32A8ytLlLq1yzio=,tag:N4nTfQounDaElrSl7k5l7Q==,type:comment]
  SESSION_ENCRYPTION_KEY: ENC[AES256_GCM,data:0f88y0RSarK+c8s5Arp+t815DIzq+TOFiBF0iSFtGKai4kvb1Cmscu9cN7U=,iv:SiJ66ETpYYkaoeru8yx1lHKVj5svSWi9HYliAgRBsJo=,tag:S4uR5CwFJr97/gcIs9WJtw==,type:str]
  #ENC[AES256_GCM,data:XXtrd3Qj0Tz9+dH9R+mmJvH+6Xk=,iv:5O14sqvQrJkOIZNlMveqQHLoI5FsP3mTsiuhfgJAfes=,tag:b9Er2vRBUODP48C4vRlj6Q==,type:comment]
  AUTH0_DOMAIN: ENC[AES256_GCM,data:qJvC5PEhvzd2yOGhV0LX3gJ0VQ==,iv:vxm578syXhjSzT2jLHVpg1FtRpLo9S5+pmr+zbw/2FA=,tag:cvwZDd+4W9BLRaZkk202Zg==,type:str]
  #ENC[AES256_GCM,data:E95mVkL9aUu6Dlkl4iANzBR/GD4htqFd3JLi4m69H2Y=,iv:6wnPAg+QAmrR/hdGB1c16V0gH2/PkvylxPdTVykDzFI=,tag:UlVpxj6wplukTRJtMSC9SA==,type:comment]
  PROVIDER_URL: ENC[AES256_GCM,data:RNhayJXYDvN/LuxrUpV6AeEtwiZ1jWQz3cYR,iv:9FcF648qVGLiNbcHbWNcdhthinTJSZ7GUdGi89KXBAU=,tag:ivcywo+pwn3zQepUwiPNMg==,type:str]
  CROWDSEC_BOUNCER_KEY: ENC[AES256_GCM,data:ybzc/KqTFZmdqwv/re5cAPqdG2h+3/AzOvKWF6qRry2Eg/XIshp/KiGV3UNT3ZD01CLIZW66rkeFtgJGascivw==,iv:AiVob+n2U+8D4NgDtTyWWpO/bYl/8o6UP+yGlkVQijo=,tag:taC/tUwNMREQSuUpIXN1xA==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVmtybm1PTFllSlpzME0r
        cWgrS09XTnI3LzJYNklFUUVXTkJhMWliWWdjClROb2ZsY3gyc1pjalU0RUN6MUlO
        QWFDOUk0SGovM0tlekxCM0FRTkd6a3MKLS0tIGRTUHlJazBQRGZ5Uk4weEMzYTc4
        L1J3VnZRVmJkb25EMmpBc3JmbUVsMkUKl6EDJPAXuh63QjmfIzfcNGR0hANvUIB1
        A0rDBV0ifRN/o/GRan2QPorA1qp3qIVs9Ol91v6YPKohc/kg4ZBVGA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-23T15:36:12Z"
  mac: ENC[AES256_GCM,data:/khQFhbMu1B4pGhdbl3NQheKV36WGkBsr8jgFx16WZwmEKq4ynLbQTAVBryAqtti5YJaGD0Fh/uRJ967wuVuX6xQvMunzGwl+V0/a6Y+rTXQ4lUqpR5IYq5SEnOWyk87Kof9ixjhxIEYEwPvEY1XwFZyP4XXcv+dlUOlOR88Yow=,iv:i7S5sP5QLcgjG444Vt+2f4s5J6q8zDegAkhUuH0ketQ=,tag:eFfX98ThgJ3dwCrqp6NrRw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
