---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./amd-gpu.yaml
  - ./bjw-s.yaml
  - ./cloudnative-pg.yaml
  - ./descheduler.yaml
  - ./dragonflydb.yaml
  - ./external-dns.yaml
  - ./grafana.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./netdata.yaml
  - ./nfs-external-provisioner.yaml
  - ./parseable.yaml
  - ./prometheus-community.yaml
  - ./tailscale.yaml
  - ./toolhive-operator-crds.yaml
  - ./toolhive-operator.yaml
  - ./vector.yaml
