---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: toolhive-operator-crds
  namespace: flux-system
spec:
  interval: 30m0s
  url: oci://ghcr.io/stacklok/toolhive/toolhive-operator-crds
  ref:
    tag: 0.0.58
