---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: opentelemetry-collector
  namespace: flux-system
spec:
  interval: 12h
  url: oci://ghcr.io/open-telemetry/opentelemetry-helm-charts/opentelemetry-collector
  ref:
    semver: '>=0.97.0'
