# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: loki-s3-secret
type: Opaque
stringData:
  S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:NvmdCga1d5BOycSqWQ==,iv:3e+RbWd8v4we4FOtcJw2Ny3UohPxkchrQJOCpoko+Ng=,tag:xi3z4M63JggQhsBeym2JHg==,type:str]
  S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:pSMGVsn6zNnKOP611uiCyw==,iv:gdRSkRTfey1Rp2hXc+EWSP5JG8NjlKEVgchmDcegFIk=,tag:54YSygEeXWRivNIKM7Zayg==,type:str]
  S3_ENDPOINT: ENC[AES256_GCM,data:KXInf1e/VEynFCQ6AztDCNnd,iv:dZpGoCRJ5WJBvagBVLKedgZk6/ZtkibOQJKeACkPz9s=,tag:dA9pGT0K0xV1fl/J+hV3fg==,type:str]
  S3_BUCKET: ENC[AES256_GCM,data:k56gAg==,iv:z8YZFwBfPuKkwO+G4tuqRMmB1M6PQqAFNaYaTGPoGlw=,tag:nG+qF1/JQZAgY/R7B1RfqQ==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdjJEV3FIbmkxdEhhMTc5
        ZVJsdWpSRjFaNlc4bThReWhCNHJTUTlCL1g4Ci9YYVdyam1iQnczQXVLaFMwaXI5
        ckpYTHBsb2dpSDFBV3NoaGhUb3hXdG8KLS0tIDdXYXgrcndKR0NkckdjYU9rblBz
        VFYrN2F2SDM2eHBVencyR1pHSGNVRDAK2Z6K4ohJ5G4Rwj5VQVKfg0WG2JANzpPz
        WXIqaP4yjYfNTxMdElJGd/Qgq9oUQenAGLV5DTcy5Opq3xrDNWYn5Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-07T14:49:48Z"
  mac: ENC[AES256_GCM,data:MY8tKNXOJDmMv8XvsHxrqO+7DG6oEbU97OK+ZE2H4VpXUkvHbCZO6ZF8pVU1fEaQkHraM5YYh8SNgX2XqxvfyVOKJCYk2f46TwewWsA3SmES9gjBboVT8/2rvySjJJUQEPRsRC9dT5XqRwbximSQMbvclO3Egh3Mq5weZbhVM6E=,iv:nwnAf7jWDgePEZptGucO5ch2GtGdlSSoK2U3VFlhoOE=,tag:nnGxOlLmELoq6QUZ+I80Hg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
