apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-config
  namespace: monitoring
type: Opaque
stringData:
  objstore.yml: ENC[AES256_GCM,data:uHO48leI6m7518537UlCT1iOy0VNMCqu4oEYcJRRSzbMyQsonB+o/mZ6eB6DbzQ+xWPwowvkK1Z4nEiL6/uRAq4knixKNdl5UtTtxWFwGy5isQ5zMrlnOlU93giUcWvPvPEzyiyGvfsoTfrrzvOInuLCyJnkz4HIpZ+VzHpTc6N5Swfq7jyT6PyCw10vfkdQNO7JmSeQmIdoLaRuvH/o7lXzMwtteskEt2Azp8LjL56gNUWZsbxlGYPMP7YC,iv:SR+OF0EuTWLjbbMxbLmS+43l2EKRcXNc3ZljEookG9c=,tag:jB7tey8+7Z7BKj5Yxe1law==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZGRqMmlHTlJjWHBCQUN6
        REpVYUY0ZUNvRTdGdURPUUFNUHZFOU5DZXdRCnpJVmNjMU5PRzdacXdZejhteTJx
        dGhvZ05CMno4ZG8vWExFZ2JtaTZpKzAKLS0tIFhVZWlFcDdNaldQTFBaV2NkOUtG
        MWlFc2d5NzNKMG4waDN5VmZNVlJyZGsKHZrHVRZumKOfEx+hFwz9RvrqaAxEQaWK
        7wucxlHwiNUiOXhgBrLYSF5EuqjExlW4QSFvT3n7h8+/JsgPs6FpmA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-22T15:59:01Z"
  mac: ENC[AES256_GCM,data:DgwVhT1ttpfJBfDl56ViExGkPdDUBds423MKzU/+iaZXVKcbQVb2dXO8BK27ol3TvHBy6Lr/9Ap6ziayGRT0a0BmRYDw0idkdvcMxmYPqGkWubedXP+b0AY03s95Xaia1cADdnt5vatBq+OgZ+sKEy4mbqPwdQJGaxCxkCZD5hQ=,iv:9zuJdGJvD3ZaEjyTjxRwTvSJpB979i6IBjQfaHFcBN8=,tag:fzfYKm5V5/br1zY2m1CpJQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
