apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-config
  namespace: monitoring
type: Opaque
stringData:
  objstore.yml: ENC[AES256_GCM,data:gnM9b6rOWru8F3ZxiUJ2OZcyMRyzX9oeHzbiOi1Hb4wNZmVFr+O5c+YVbqaLVNIweYbcFEPuWX84JRtOasO/1kCfcaOqKfatSJUhFmQXObWRzIb4AiUoqzd2ryoCkQacukWXivwd6ZhPIpQbuSHXix2dfFoC0a82Gs/M1cFGxMNI1MYj57TBxqrzLB16czO/eTeAhUTlFuW5dRwLEy65gNv1dUgb5ae25bg5VQalR+a+DZThnam8eKfJrlynA/xg008P5ETXpRL/+Ro=,iv:XzIj1+T6Dnah4KYWp9W+7uPdvPigWqCQf5J6wI8ZET8=,tag:0kyt64/YEfa343qPd7nb6w==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTb3B2Yll0UXFIeXdqNDdO
        QkNLOTZUWVdsRkNTa2l1ZUlCclJjcU1XUVIwCjRRU0M4U0g1bjJhdU1keEViZjd1
        RkxQZWNiNWl3SUhGSDJpWUVraTEzZ2MKLS0tIHVzeHZ2UGIzNW9IaFYrN1JGWUF5
        cEEvcFJWMDNpekY0UmtsK3ZVQUVNdkUK3QYudWM56CSYT0/XfTG6iTs89bWbiLmR
        uJOnzd8bSCEWuRS++iw2ZyYfltkSXKw+uCzDq89fjI0tpm8PDiLI7A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-21T17:02:34Z"
  mac: ENC[AES256_GCM,data:do5ddztYtTI3oxSH87IY8P911w4uwEhDwtuYutB/Jl5H2ujiRVH3Fwr7mBq9DYUnszl5TpUKej0UouXFX4nfHAiEr+9qE5AJGhslyy2g4I2kILU0etPF9jaPMPG52wotBBVNscKouhXNjC6tbIxjfQNl1cAkgXZpAFjCWJgFWLI=,iv:Cxs/MCwn2nJReUrMZrkzQMrm0YXDx0iL2EedSWYQ7I0=,tag:+xJmMbu8yU8Kc9FqEEY0og==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
