apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-config
  namespace: monitoring
type: Opaque
stringData:
  objstore.yml: ENC[AES256_GCM,data:CH9Noc3bFXlM9sLjifA/T8VPHSNxn3y3IXOAlftWUwizl81i5SQ6o/5wrblpR3X7FCxreMUjIyY2ye1HZI3K7Bwg/FyOv9BlykTye89EmthN2ot3O1p/vRHcPIyQR2VZt2qakB1HizC7xkY3fEojY2nCi9TiKcD/NxzN4/tFZ3rl80DNIZQE/vC1r6P0vG3zldJf0bv6hbZgNN2274uw8MaVALKKY3x174uKx6xLYA9AB5S3i9104G8A9Bu8,iv:GE69YgHjIdu37+GebUov1ZCMKZMnyWQIhfWIA66OjmU=,tag:q69OEK9zgT+5tvVgs+9rEQ==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cENRWE8vR0hNdGNybTEy
        SHRneFF0bG1Xb1ZiTXJOV2N2Y0tqcTh1UnpzCnkyYjFjdHBGamhvdnp5Z2xKUHI5
        QWF5VzhFaGtUSzd5b29xejlTd3gzbFEKLS0tIDhXSVorbFNuRytwQVlqMWxZaC90
        SGVFUkZQRzJQZWp1UzIxdFptOHVvbVUKligO/AenMVNAz2SDdoE+BX6GnXcvV/ER
        y6R94RG+lcZlDO7zOI+XRcjFIAMJuVtzZXFU8lGbN0UsPTymYmBd2w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-22T15:19:52Z"
  mac: ENC[AES256_GCM,data:iBFojoWSHTYznnlaqA79sggQtmtyXSmiVkct9NCP4CGJA7rkbb7S/u7T62CM/h9YK6BDeKj2ZtqyEyfagd+bjVRVNG8jIll2XJNSv6yXgsncCd9Krn39F4X3POgRcWCxelqAdH+fwxAFvz0IIHeRyn3JQoeDX94C/3VN1NAJhdY=,iv:SbauTokHrWXarnbMRzAcfwGj/SB3r4ieQ9euVuQGnaM=,tag:iYOPJZCSHWstwXCnefpSFw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
