apiVersion: v1
kind: Secret
metadata:
  name: victorialogs-s3-secret
  namespace: monitoring
type: Opaque
stringData:
  S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:h/rvybt7MNWp9kGaUQ==,iv:qJwHI8VbePZC6Et+aDszuPS9bgWvkoRs2TkZN1206/A=,tag:CMDwHw61CPOquGiLk0f6fw==,type:str]
  S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:wOF0ADr9TwTBS2zOwdCxlw==,iv:BYY65WhM6ic1H5ygVEUW4XpXEe7+tPTkd9KAL31vuIs=,tag:C0Q7PJnEaIxZj0EG1YyQlw==,type:str]
  S3_ENDPOINT: ENC[AES256_GCM,data:VTs0EEthzjO2DpW1lT9eegTI,iv:46Fymtp56w+axRZhNxSxM4eu1752Rj0q42a/qpQwV8Y=,tag:B5zVsos9msZrA+ZKz4hNVA==,type:str]
  S3_BUCKET: ENC[AES256_GCM,data:4lqJa4RrwF9vFngPNtmGrVo=,iv:DVi4Rb96B/Z6jQ6wHXSBIDVy99JEKI6IOBH5gUkuh9A=,tag:A6htPZhsKVUA7dWM698stg==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTEFhUENMVDlKeU9qa3JR
        c0ZBZ1NOeXh3NVV1SzVYRlV0UnQ3d2JQNmxzCnI1ZVZYVW8valkvMHdHaGYwYXJs
        UDFrdjB4Y2dKN1JMN2o0SzJmQzJ3a2cKLS0tIFRlR2tGQjYyVlRoZFM0Um8xaTln
        dzR6VVc0OUJVRjhxMExLU1BZdDVCSFkKf7T+B9mnDPcmzIxtB6NA86AK+YR67RQl
        uViC7aHMnYA9R4fT5DV3O2r7TvzMIq/+DCZsC0cgtb3E7IpgGvtXfg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-11T22:24:22Z"
  mac: ENC[AES256_GCM,data:I+c0lBBE+TS0Amr/spaUJhQ919t8ahTGRCZTk/403m2U73WR6n6X5FxCk+Xi+kyt536beKXf+gxavUurr788XF4FpazfJxvD4CBVfkdBe+r6KOryMIDstUaK2TmegJkki4Odx3GPgqWoNyX7wwV5pDe8Q/l4ZUJLBte4Z3tD57k=,iv:XGUimY2mwowEM6vrPi7UggcrS48EOiVdgqARnaMfC+c=,tag:9GfhWDQOYWMKtixNxELivw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
