---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/tcproute_v1alpha2.json
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: victoria-logs-syslog-tcp
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: network
      sectionName: syslog-tcp
      kind: Gateway
  rules:
    - backendRefs:
        - name: victoria-logs
          port: 514
          namespace: monitoring
