---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: victoria-logs-syslog-udp
spec:
  entryPoints:
    - syslog-udp
  routes:
    - services:
        - name: victoria-logs-server
          port: 514
          weight: 10
          nativeLB: true
