---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/tcproute_v1alpha2.json
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: victoria-logs-syslog-tcp
  namespace: monitoring
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: victoria-logs-syslog-tcp
  rules:
    - backendRefs:
        - name: victoria-logs-server
          port: 514
          namespace: monitoring
