---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/udproute_v1alpha2.json
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: victoria-logs-syslog-udp
  namespace: monitoring
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: victoria-logs-syslog-udp
  rules:
    - backendRefs:
        - name: victoria-logs-server
          port: 514
          namespace: monitoring
