---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/tlsroute_v1alpha2.json
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: postgres-external
  namespace: databases
  annotations:
    external-dns.alpha.kubernetes.io/hostname: pg.68cc.io
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: postgres-tls
  hostnames:
    - pg.68cc.io
  rules:
    - backendRefs:
        - name: postgres17-rw
          port: 5432
