apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-bouncer-secret
  namespace: network
type: Opaque
stringData:
  CROWDSEC_BOUNCER_KEY: ENC[AES256_GCM,data:mw6KzWpbHIbkmrrWqjvK4W+hxbUfLaNZE4pOYtf0Pnky5YTUpLEwlVlxVlIc6/dr9mguIfl3PZjBYAWJn/THTg==,iv:TiLjdMfmh/1jGhNKtCJufwzcnXE6TAwubFiPKIPeqYg=,tag:kXXh2djYr7WBwYIzKfvovw==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3QldTbjhiUWYyRis1VG50
        eUtYdlU3M2lISnIxaXNablpzR1RRb1R4dVZBCjBjL1ZVWjNkWnhQTXFNT3JtRWRv
        VU4rYlRiYmJRSTgvK0Npd0w2cnpNQUkKLS0tIEVRVHpzVEswdWRiYWtqVktZRzJU
        aDUyVE9sYlJTT3NDZmpVeWMyUzRqbUUKLRiqosBEJ4PtIqmwUZGFzMnd6on8HAZ4
        GspYIQ0CCvb80/MYyoh1Ht4I7magc1/L2Cph9OUA+Aru/U6pI3DiQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T18:05:14Z"
  mac: ENC[AES256_GCM,data:ATawP4mKAGCXBiF+cWrnqQwlnoZB57BnVXf306viXf5X7xs4+o3czMbED3yEUuHEcniIRjiqjqr8CKzkI4GljGW3ud+thfjXFS18ndJIm3D4GcuIeAcPjLRV2xKP7vtGHvra4320Va1FKrMqDkRDaKIAET0bQ05zq0B1/9QCUuA=,iv:58V8ikBEwyxIYum6o0RrSZvg+4u3BB212Y9H4IJ9MTE=,tag:nNYIju7PzFmGg4MORA4weA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
