---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
resources:
  - ./robots-txt-configmap.yaml
  - ./ai-robots-txts.yaml
  - ./security-headers.yaml
  - ./compression.yaml
  - ./crowdsec-bouncer.yaml
  - ./ratelimiter.yaml
  - ./oidc.yaml
