---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
resources:
  - ./security-headers.yaml
  - ./compression.yaml
  - ./crowdsec-bouncer.yaml
  - ./crowdsec-bouncer-secret.sops.yaml
  - ./ratelimiter.yaml
