---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: owasp-headers
  namespace: network
spec:
  plugin:
    traefik-owasp-security:
      # Optional configuration
      disableCookieHTTPOnly: false
      disableCookieSecure: false
      disableCookieSameSite: false
      skipCookieSecurity: false
