# Auth0 OIDC Configuration Secrets
# This file contains sensitive credentials for Auth0 authentication
# Encrypted with SOPS using age key
apiVersion: v1
kind: Secret
metadata:
  name: auth0-oidc-credentials
  namespace: network
type: Opaque
stringData:
  #ENC[AES256_GCM,data:hu19A1zdNsR/U6zGeGRc6lkuyxgVRRerrj8Q26nW,iv:SrxW4QvLk7wXt0MNONbUOUkCE9CchMvDs/FfVcawuZw=,tag:nxNrZeiGxowLHBDia0rgVw==,type:comment]
  #ENC[AES256_GCM,data:/cFJ7rLIrhxYv2JajZzx692VS+j6+3Fiw3CmuUVglwM1EbxpIyQ=,iv:ujSx6ZUGrdx/Bt7+oVW5CH+BrISfP5GvbvIvI9zCC7k=,tag:2/+vFBc7nxsxJjz4K1dfNQ==,type:comment]
  AUTH0_CLIENT_ID: ENC[AES256_GCM,data:jK0so9yN/DMD+pSGeZB6BtrnIR0YjW2WxCN1+QA3wa0=,iv:XdWWcJiYI07yt3GAA7YlK4ZnilOCEGj5EqQCupaaVoY=,tag:2M5kiDFxjK2+zFvwxagzLA==,type:str]
  #ENC[AES256_GCM,data:LQCCyYZvz/oWQpCaKJU7fMXVPcufBHV5W1bRsCyeOZYGDc4=,iv:GjneDmYBCQf3ua9TES0m+aA9HzFaaV8vdMlU7jszj1I=,tag:Ve+xNO5fq0ifsRmMIKNG+g==,type:comment]
  #ENC[AES256_GCM,data:G6Aq2DH3XIgBrE9FyAS6ar0QIXchKT1PAVPjWo7m52cv8FlCB5ng3nD8yCwepessn/LaxJf4qsY6Ty34Usxn/NnkKMOf5pkaKqKdSjk7aRPb1/EASWw=,iv:jr2R9+P4vbJa55PQp85z//Y3qGSmbe458Gp7EKv0p1Y=,tag:WbgET6HHXq4LQWGv92vi7g==,type:comment]
  #ENC[AES256_GCM,data:k30RPY0CyGUM74mmgbKc1MDS2G1TL+IjDXqBDIpzWsL+HcnhXL7vm/akaF+TsIeuMmkULRjIvVzItbEFpgPe8y8ktvqnTKwVfkFUEqYH,iv:8y8QhmnE1ehbSYZYu2sNU0p/WJYOd94a3tgqoTHAbz0=,tag:WM3qy45upUbNhwhmKfxfRA==,type:comment]
  AUTH0_CLIENT_SECRET: ENC[AES256_GCM,data:Oss4BdHb4L3WKdJ9W1lDafKatPFfT4kfb7zH+FoTEMZXDw==,iv:AHfa08j6scx6xtq26zSW/KxWgxlF8i2R+ZhQiuBvhn4=,tag:gJMBTuwe006tfv6E22I8ew==,type:str]
  #ENC[AES256_GCM,data:XITT20mkksnVADxz0vVwx+hx1Cs28sNO186kPQ4zNgG98CnHB/Lt6nHSF7OsLc++2ZM=,iv:z/LBEdKV5b0jjafPoWdHc8NkX0jGuNvy5eFyQh+dzZg=,tag:2aFKfUCCfVL4iyMygZGE6g==,type:comment]
  #ENC[AES256_GCM,data:0aqKl8FOqoLfS/0BMft/AchlqinxD099tCrHAKQQvmRnunc6fP118SZ/A6Oy,iv:idLZ/4UKBxQr7w0O+8PlNEuVcfQ6SwjKKGtJzr/E9KQ=,tag:nSPnURfooQXqgGw4FIJY5g==,type:comment]
  SESSION_ENCRYPTION_KEY: ENC[AES256_GCM,data:dlvh7796A9I73Yy7KjKTsK6UGxPf0yLhLB7sPvdfSzqSNOnY/T9vPo7MEiY=,iv:ZCgFAHY0RPGCxx7aj2Afk0rzbBwi9AS7BT4dXe06LpY=,tag:szTtbD9tMXlrpE/f1IrLZA==,type:str]
  #ENC[AES256_GCM,data:2isdLiibEbqCUcU8nUkukuLLGEY=,iv:ePrV1HzLxnmfxQls86EUyAWhNIqHvpW9zqh39nxkjb8=,tag:SM7t/5jEWpfG9Dvewwc/ig==,type:comment]
  AUTH0_DOMAIN: ENC[AES256_GCM,data:Xn2R450KF7t2wDPkjigcAKHrAA==,iv:1zAURRttT3KLWGb1FAN8ABh5jYqVSpJYvz5KQD1DiQI=,tag:gdOexHOclCS7aw65YWplcQ==,type:str]
  #ENC[AES256_GCM,data:bg+aYpbjKnKbUXYnbp+Viw2O0cU7LubHxRWu8PjOxgU=,iv:fvMZK7bOsrch+dcI8W167syMiFAOqx7jyb+mrPzoqqo=,tag:sHsaDd+feeXdx1+BjgRUMQ==,type:comment]
  PROVIDER_URL: ENC[AES256_GCM,data:xjV/zu5WD2aFQDVKlhqvSZZbk1ViUjp6kpJC,iv:xp7RTHJsUZJGaQBgYnoBAVXOWfAsWQ5PR+WB/RYTn+k=,tag:oZZ2yxXXFpnT53Z7SPNbEg==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZFMvOExHZVVOeEVjbFNw
        TkxkaktNSk9KWW44MWtqendQUHR5S0hhNEVnCmVMMWQzNUxBNGxScXlsWXEzUUV2
        N1RQQ2dzOXkrbmZSVHhvS0xveGlsdEkKLS0tIDByZ0xVdDByV3hzRWxUZDZXWEEz
        Rk9qRFRHNUlIV2Jwek1QcnJtMVFEeHcK9Dv+RKFlDdBW/OHDJVRZ74a1vPazEUv2
        /OGifspspo9FgYu+sI5sssWr7nAy2ab5KIkkktIjoMCFcsQJDs5mUQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-21T18:52:38Z"
  mac: ENC[AES256_GCM,data:r8Rn8oJafEiwD7EFx+RFh+VuSmZNLuc54WfR66Mt5G7qim4aBhoUhIaYU5Bpr4P27uqIdkuS1R7XuHlkPHZdaJOYA4vX5WYttQr8VotHY0WIb6M2zOkxcRa+h2iRDmlSnxOK4S6SRRNrHKsTMDDgd5mAQlISWojTxhA53hj2cZo=,iv:weNbGAbWGboEJLZVZiuW2efP004a7TRNbzA69A8DCis=,tag:uMn2eA+OFVJfToMWUq2zJw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
